-- Update il_permitted_additives with MOH approval data from spreadsheet
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural, from turmeric' WHERE e_number = 'E100';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E100', 'Curcumin', 'permitted', 'Natural, from turmeric');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Also Vitamin B2' WHERE e_number = 'E101';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E101', 'Riboflavin / Riboflavin-5''-phosphate', 'permitted', 'Also Vitamin B2');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Synthetic azo dye' WHERE e_number = 'E102';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E102', 'Tartrazine', 'permitted', 'Synthetic azo dye');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Synthetic dye' WHERE e_number = 'E104';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E104', 'Quinoline Yellow', 'permitted', 'Synthetic dye');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Synthetic azo dye' WHERE e_number = 'E110';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E110', 'Sunset Yellow FCF / Orange Yellow S', 'permitted', 'Synthetic azo dye');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural, from insects' WHERE e_number = 'E120';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E120', 'Cochineal, Carminic acid, Carmine', 'permitted', 'Natural, from insects');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Synthetic azo dye' WHERE e_number = 'E122';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E122', 'Azorubine, Carmoisine', 'permitted', 'Synthetic azo dye');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Restricted – fish roe only' WHERE e_number = 'E123';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E123', 'Amaranth', 'permitted', 'Restricted – fish roe only');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Synthetic azo dye' WHERE e_number = 'E124';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E124', 'Ponceau 4R, Cochineal Red A', 'permitted', 'Synthetic azo dye');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Restricted use' WHERE e_number = 'E127';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E127', 'Erythrosine', 'permitted', 'Restricted use');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Synthetic azo dye' WHERE e_number = 'E129';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E129', 'Allura Red AC', 'permitted', 'Synthetic azo dye');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Synthetic dye' WHERE e_number = 'E131';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E131', 'Patent Blue V', 'permitted', 'Synthetic dye');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Synthetic dye' WHERE e_number = 'E132';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E132', 'Indigotine, Indigo carmine', 'permitted', 'Synthetic dye');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Synthetic dye' WHERE e_number = 'E133';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E133', 'Brilliant Blue FCF', 'permitted', 'Synthetic dye');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural, from plants' WHERE e_number = 'E140';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E140', 'Chlorophylls and Chlorophyllins', 'permitted', 'Natural, from plants');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Semi-synthetic' WHERE e_number = 'E141';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E141', 'Copper complexes of chlorophylls', 'permitted', 'Semi-synthetic');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Synthetic dye' WHERE e_number = 'E142';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E142', 'Green S', 'permitted', 'Synthetic dye');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Caramel color class I' WHERE e_number = 'E150a';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E150a', 'Plain caramel', 'permitted', 'Caramel color class I');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Caramel color class II' WHERE e_number = 'E150b';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E150b', 'Caustic sulfite caramel', 'permitted', 'Caramel color class II');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Caramel color class III' WHERE e_number = 'E150c';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E150c', 'Ammonia caramel', 'permitted', 'Caramel color class III');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Caramel color class IV' WHERE e_number = 'E150d';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E150d', 'Sulfite ammonia caramel', 'permitted', 'Caramel color class IV');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Synthetic dye' WHERE e_number = 'E151';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E151', 'Brilliant Black BN, Black PN', 'permitted', 'Synthetic dye');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural' WHERE e_number = 'E153';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E153', 'Vegetable carbon', 'permitted', 'Natural');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Synthetic dye' WHERE e_number = 'E155';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E155', 'Brown HT', 'permitted', 'Synthetic dye');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural' WHERE e_number = 'E160a';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E160a', 'Carotenes (mixed/beta/algal)', 'permitted', 'Natural');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural, from annatto seeds' WHERE e_number = 'E160b';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E160b', 'Annatto, bixin, norbixin', 'permitted', 'Natural, from annatto seeds');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural' WHERE e_number = 'E160c';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E160c', 'Paprika extract, capsanthin', 'permitted', 'Natural');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural, from tomatoes' WHERE e_number = 'E160d';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E160d', 'Lycopene', 'permitted', 'Natural, from tomatoes');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Semi-synthetic' WHERE e_number = 'E160e';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E160e', 'Beta-apo-8''-carotenal (C30)', 'permitted', 'Semi-synthetic');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Synthetic' WHERE e_number = 'E160f';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E160f', 'Ethyl ester of beta-apo-8''-carotenic acid', 'permitted', 'Synthetic');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural' WHERE e_number = 'E161b';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E161b', 'Lutein', 'permitted', 'Natural');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Restricted use' WHERE e_number = 'E161g';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E161g', 'Canthaxanthin', 'permitted', 'Restricted use');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural' WHERE e_number = 'E162';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E162', 'Beetroot red, betanin', 'permitted', 'Natural');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural, from fruits/vegetables' WHERE e_number = 'E163';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E163', 'Anthocyanins', 'permitted', 'Natural, from fruits/vegetables');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural mineral' WHERE e_number = 'E170';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E170', 'Calcium carbonate', 'permitted', 'Natural mineral');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Under review in some regions' WHERE e_number = 'E171';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E171', 'Titanium dioxide', 'permitted', 'Under review in some regions');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural mineral' WHERE e_number = 'E172';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E172', 'Iron oxides and hydroxides', 'permitted', 'Natural mineral');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Restricted – coatings only' WHERE e_number = 'E173';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E173', 'Aluminium', 'permitted', 'Restricted – coatings only');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Confectionery coatings' WHERE e_number = 'E174';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E174', 'Silver', 'permitted', 'Confectionery coatings');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Confectionery coatings' WHERE e_number = 'E175';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E175', 'Gold', 'permitted', 'Confectionery coatings');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Cheese rind only' WHERE e_number = 'E180';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E180', 'Litholrubine BK', 'permitted', 'Cheese rind only');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E200';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E200', 'Sorbic acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Very common' WHERE e_number = 'E202';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E202', 'Potassium sorbate', 'permitted', 'Very common');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E203';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E203', 'Calcium sorbate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E210';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E210', 'Benzoic acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Very common in beverages' WHERE e_number = 'E211';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E211', 'Sodium benzoate', 'permitted', 'Very common in beverages');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E212';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E212', 'Potassium benzoate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E213';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E213', 'Calcium benzoate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Paraben' WHERE e_number = 'E214';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E214', 'Ethyl p-hydroxybenzoate', 'permitted', 'Paraben');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Paraben' WHERE e_number = 'E215';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E215', 'Sodium ethyl p-hydroxybenzoate', 'permitted', 'Paraben');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Paraben' WHERE e_number = 'E218';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E218', 'Methyl p-hydroxybenzoate', 'permitted', 'Paraben');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Paraben' WHERE e_number = 'E219';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E219', 'Sodium methyl p-hydroxybenzoate', 'permitted', 'Paraben');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Also bleaching agent' WHERE e_number = 'E220';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E220', 'Sulfur dioxide', 'permitted', 'Also bleaching agent');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E221';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E221', 'Sodium sulfite', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E222';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E222', 'Sodium hydrogen sulfite', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E223';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E223', 'Sodium metabisulfite', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E224';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E224', 'Potassium metabisulfite', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E226';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E226', 'Calcium sulfite', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E227';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E227', 'Calcium hydrogen sulfite', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E228';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E228', 'Potassium hydrogen sulfite', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural preservative' WHERE e_number = 'E234';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E234', 'Nisin', 'permitted', 'Natural preservative');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Anti-fungal' WHERE e_number = 'E235';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E235', 'Natamycin', 'permitted', 'Anti-fungal');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Cold sterilant' WHERE e_number = 'E242';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E242', 'Dimethyl dicarbonate', 'permitted', 'Cold sterilant');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Cured meats' WHERE e_number = 'E249';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E249', 'Potassium nitrite', 'permitted', 'Cured meats');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Cured meats' WHERE e_number = 'E250';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E250', 'Sodium nitrite', 'permitted', 'Cured meats');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Cured meats/cheese' WHERE e_number = 'E251';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E251', 'Sodium nitrate', 'permitted', 'Cured meats/cheese');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Cured meats/cheese' WHERE e_number = 'E252';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E252', 'Potassium nitrate', 'permitted', 'Cured meats/cheese');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Vinegar' WHERE e_number = 'E260';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E260', 'Acetic acid', 'permitted', 'Vinegar');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E261';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E261', 'Potassium acetate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E262';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E262', 'Sodium acetate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E263';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E263', 'Calcium acetate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural' WHERE e_number = 'E270';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E270', 'Lactic acid', 'permitted', 'Natural');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Bread' WHERE e_number = 'E280';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E280', 'Propionic acid', 'permitted', 'Bread');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Bread' WHERE e_number = 'E281';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E281', 'Sodium propionate', 'permitted', 'Bread');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Bread' WHERE e_number = 'E282';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E282', 'Calcium propionate', 'permitted', 'Bread');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Bread' WHERE e_number = 'E283';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E283', 'Potassium propionate', 'permitted', 'Bread');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E290';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E290', 'Carbon dioxide', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E296';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E296', 'Malic acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E297';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E297', 'Fumaric acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E300';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E300', 'Ascorbic acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E301';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E301', 'Sodium ascorbate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E302';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E302', 'Calcium ascorbate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E304';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E304', 'Ascorbyl palmitate / Ascorbyl stearate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E306';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E306', 'Tocopherol-rich extract', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E307';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E307', 'Alpha-tocopherol', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E308';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E308', 'Gamma-tocopherol', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E309';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E309', 'Delta-tocopherol', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E310';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E310', 'Propyl gallate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E311';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E311', 'Octyl gallate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E312';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E312', 'Dodecyl gallate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E315';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E315', 'Erythorbic acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E316';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E316', 'Sodium erythorbate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E319';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E319', 'TBHQ', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E320';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E320', 'BHA', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E321';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E321', 'BHT', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Very common' WHERE e_number = 'E322';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E322', 'Lecithins', 'permitted', 'Very common');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E325';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E325', 'Sodium lactate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E326';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E326', 'Potassium lactate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E327';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E327', 'Calcium lactate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Most common additive' WHERE e_number = 'E330';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E330', 'Citric acid', 'permitted', 'Most common additive');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E331';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E331', 'Sodium citrate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E332';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E332', 'Potassium citrate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E333';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E333', 'Calcium citrate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E334';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E334', 'L(+)-Tartaric acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E335';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E335', 'Sodium tartrate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Cream of tartar' WHERE e_number = 'E336';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E336', 'Potassium tartrate', 'permitted', 'Cream of tartar');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Rochelle salt' WHERE e_number = 'E337';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E337', 'Sodium potassium tartrate', 'permitted', 'Rochelle salt');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E338';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E338', 'Phosphoric acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E339';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E339', 'Sodium phosphates', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E340';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E340', 'Potassium phosphates', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E341';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E341', 'Calcium phosphates', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E343';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E343', 'Magnesium phosphates', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E350';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E350', 'Sodium malate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E351';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E351', 'Potassium malate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E352';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E352', 'Calcium malate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Wine' WHERE e_number = 'E353';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E353', 'Metatartaric acid', 'permitted', 'Wine');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E354';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E354', 'Calcium tartrate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E355';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E355', 'Adipic acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E356';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E356', 'Sodium adipate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E357';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E357', 'Potassium adipate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E363';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E363', 'Succinic acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E380';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E380', 'Triammonium citrate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E385';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E385', 'Calcium disodium EDTA', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E392';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E392', 'Extracts of rosemary', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E400';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E400', 'Alginic acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E401';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E401', 'Sodium alginate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E402';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E402', 'Potassium alginate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E403';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E403', 'Ammonium alginate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E404';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E404', 'Calcium alginate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E405';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E405', 'Propane-1,2-diol alginate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E406';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E406', 'Agar', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'From seaweed' WHERE e_number = 'E407';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E407', 'Carrageenan', 'permitted', 'From seaweed');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E407a';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E407a', 'Processed eucheuma seaweed', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E410';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E410', 'Locust bean gum', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Very common' WHERE e_number = 'E412';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E412', 'Guar gum', 'permitted', 'Very common');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E413';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E413', 'Tragacanth', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E414';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E414', 'Acacia gum / Gum arabic', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Very common' WHERE e_number = 'E415';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E415', 'Xanthan gum', 'permitted', 'Very common');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E416';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E416', 'Karaya gum', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E417';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E417', 'Tara gum', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E418';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E418', 'Gellan gum', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Polyol' WHERE e_number = 'E420';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E420', 'Sorbitol / Sorbitol syrup', 'permitted', 'Polyol');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Polyol' WHERE e_number = 'E421';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E421', 'Mannitol', 'permitted', 'Polyol');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E422';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E422', 'Glycerol', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E425';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E425', 'Konjac', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E432';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E432', 'Polysorbate 20', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E433';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E433', 'Polysorbate 80', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E434';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E434', 'Polysorbate 40', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E435';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E435', 'Polysorbate 60', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E436';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E436', 'Polysorbate 65', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Natural, from fruits' WHERE e_number = 'E440';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E440', 'Pectins', 'permitted', 'Natural, from fruits');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Chocolate' WHERE e_number = 'E442';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E442', 'Ammonium phosphatide', 'permitted', 'Chocolate');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E450';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E450', 'Diphosphates', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E451';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E451', 'Triphosphates', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E452';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E452', 'Polyphosphates', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E460';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E460', 'Cellulose', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E461';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E461', 'Methyl cellulose', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E463';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E463', 'Hydroxypropyl cellulose', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Gluten-free baking' WHERE e_number = 'E464';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E464', 'Hydroxypropylmethyl cellulose (HPMC)', 'permitted', 'Gluten-free baking');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E465';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E465', 'Ethylmethyl cellulose', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E466';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E466', 'Sodium carboxymethyl cellulose (CMC)', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E468';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E468', 'Crosslinked sodium CMC', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E469';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E469', 'Enzymatically hydrolysed CMC', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E470a';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E470a', 'Sodium/potassium/calcium salts of fatty acids', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E470b';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E470b', 'Magnesium salts of fatty acids', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Very common' WHERE e_number = 'E471';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E471', 'Mono- and diglycerides of fatty acids', 'permitted', 'Very common');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E472a';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E472a', 'Acetic acid esters of mono/diglycerides', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E472b';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E472b', 'Lactic acid esters of mono/diglycerides', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E472c';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E472c', 'Citric acid esters of mono/diglycerides', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Bread' WHERE e_number = 'E472e';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E472e', 'DATEM', 'permitted', 'Bread');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E473';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E473', 'Sucrose esters of fatty acids', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E474';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E474', 'Sucroglycerides', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E475';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E475', 'Polyglycerol esters of fatty acids', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Chocolate' WHERE e_number = 'E476';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E476', 'Polyglycerol polyricinoleate (PGPR)', 'permitted', 'Chocolate');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E477';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E477', 'Propane-1,2-diol esters of fatty acids', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Bread' WHERE e_number = 'E481';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E481', 'Sodium stearoyl-2-lactylate (SSL)', 'permitted', 'Bread');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Bread' WHERE e_number = 'E482';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E482', 'Calcium stearoyl-2-lactylate (CSL)', 'permitted', 'Bread');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E491';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E491', 'Sorbitan monostearate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E492';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E492', 'Sorbitan tristearate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Baking soda' WHERE e_number = 'E500';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E500', 'Sodium carbonates / Sodium bicarbonate', 'permitted', 'Baking soda');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E501';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E501', 'Potassium carbonates', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E503';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E503', 'Ammonium carbonates', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E504';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E504', 'Magnesium carbonates', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E507';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E507', 'Hydrochloric acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E508';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E508', 'Potassium chloride', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Cheese' WHERE e_number = 'E509';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E509', 'Calcium chloride', 'permitted', 'Cheese');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E511';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E511', 'Magnesium chloride', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E514';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E514', 'Sodium sulfate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E515';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E515', 'Potassium sulfate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Tofu' WHERE e_number = 'E516';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E516', 'Calcium sulfate', 'permitted', 'Tofu');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E524';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E524', 'Sodium hydroxide', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E525';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E525', 'Potassium hydroxide', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E526';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E526', 'Calcium hydroxide', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E529';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E529', 'Calcium oxide', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E530';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E530', 'Magnesium oxide', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Salt' WHERE e_number = 'E535';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E535', 'Sodium ferrocyanide', 'permitted', 'Salt');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Salt/Wine' WHERE e_number = 'E536';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E536', 'Potassium ferrocyanide', 'permitted', 'Salt/Wine');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Salt' WHERE e_number = 'E538';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E538', 'Calcium ferrocyanide', 'permitted', 'Salt');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E541';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E541', 'Sodium aluminium phosphate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E551';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E551', 'Silicon dioxide', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E552';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E552', 'Calcium silicate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E553a';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E553a', 'Magnesium silicate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E553b';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E553b', 'Talc', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E554';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E554', 'Sodium aluminium silicate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E559';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E559', 'Aluminium silicate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E570';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E570', 'Stearic acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E574';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E574', 'Gluconic acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E575';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E575', 'Glucono delta-lactone', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E576';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E576', 'Sodium gluconate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E577';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E577', 'Potassium gluconate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E578';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E578', 'Calcium gluconate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E579';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E579', 'Ferrous gluconate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E620';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E620', 'Glutamic acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E621';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E621', 'Monosodium glutamate (MSG)', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E622';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E622', 'Monopotassium glutamate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E623';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E623', 'Calcium diglutamate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E624';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E624', 'Monoammonium glutamate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E625';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E625', 'Magnesium diglutamate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E626';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E626', 'Guanylic acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E627';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E627', 'Disodium guanylate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E628';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E628', 'Dipotassium guanylate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E629';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E629', 'Calcium guanylate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E630';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E630', 'Inosinic acid', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E631';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E631', 'Disodium inosinate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E632';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E632', 'Dipotassium inosinate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E633';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E633', 'Calcium inosinate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E634';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E634', 'Calcium 5''-ribonucleotides', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E635';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E635', 'Disodium 5''-ribonucleotides', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E640';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E640', 'Glycine and its sodium salt', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E900';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E900', 'Dimethylpolysiloxane', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E901';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E901', 'Beeswax, white and yellow', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E903';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E903', 'Carnauba wax', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E904';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E904', 'Shellac', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E912';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E912', 'Montan acid esters', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E914';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E914', 'Oxidized polyethylene wax', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E920';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E920', 'L-Cysteine', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E927b';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E927b', 'Carbamide', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E938';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E938', 'Argon', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E941';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E941', 'Nitrogen', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E942';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E942', 'Nitrous oxide', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E943a';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E943a', 'Butane', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E943b';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E943b', 'Isobutane', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E944';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E944', 'Propane', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E948';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E948', 'Oxygen', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E949';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E949', 'Hydrogen', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E950';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E950', 'Acesulfame K', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E951';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E951', 'Aspartame', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E952';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E952', 'Cyclamic acid and salts', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E953';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E953', 'Isomalt', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E954';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E954', 'Saccharin and salts', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E955';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E955', 'Sucralose', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E957';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E957', 'Thaumatin', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E959';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E959', 'Neohesperidine DC', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E960';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E960', 'Steviol glycosides', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E961';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E961', 'Neotame', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E962';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E962', 'Salt of aspartame-acesulfame', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E965';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E965', 'Maltitol / Maltitol syrup', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E966';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E966', 'Lactitol', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E967';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E967', 'Xylitol', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E968';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E968', 'Erythritol', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E969';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E969', 'Advantame', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1100';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1100', 'Amylase', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1101';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1101', 'Proteases', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1103';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1103', 'Invertase', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1105';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1105', 'Lysozyme', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1200';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1200', 'Polydextrose', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1404';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1404', 'Oxidized starch', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1410';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1410', 'Monostarch phosphate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1412';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1412', 'Distarch phosphate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1413';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1413', 'Phosphated distarch phosphate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1414';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1414', 'Acetylated distarch phosphate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1420';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1420', 'Acetylated starch', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1422';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1422', 'Acetylated distarch adipate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1440';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1440', 'Hydroxy propyl starch', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Very common' WHERE e_number = 'E1442';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1442', 'Hydroxy propyl distarch phosphate', 'permitted', 'Very common');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1450';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1450', 'Starch sodium octenyl succinate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1451';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1451', 'Acetylated oxidized starch', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1452';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1452', 'Starch aluminium octenyl succinate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted', notes = 'Mayonnaise' WHERE e_number = 'E1454';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1454', 'Starch sodium octenyl succinate (alt)', 'permitted', 'Mayonnaise');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1505';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1505', 'Triethyl citrate', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1518';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1518', 'Glyceryl triacetate (triacetin)', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1520';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1520', 'Propylene glycol', 'permitted', '');
UPDATE il_permitted_additives SET status = 'permitted' WHERE e_number = 'E1521';
INSERT OR IGNORE INTO il_permitted_additives (e_number, name_en, status, notes) VALUES ('E1521', 'Polyethylene glycol', 'permitted', '');