-- Cosmetic Functions Hebrew: Create table and insert 20 rows
CREATE TABLE IF NOT EXISTS cosmetic_functions_he (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  function_en TEXT NOT NULL,
  function_he TEXT DEFAULT '',
  consumer_desc_he TEXT DEFAULT '',
  consumer_desc_he_alt TEXT DEFAULT '',
  inci_examples TEXT DEFAULT '',
  inci_examples_he TEXT DEFAULT '',
  app_display_category TEXT DEFAULT '',
  created_at TEXT DEFAULT (datetime('now'))
);
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Humectant', 'חומר לחות', 'מושך לחות ושומר על העור רטוב', 'מושך לחות מהאוויר ושומר על העור רטוב', 'Glycerin, Hyaluronic Acid, Panthenol, Propylene Glycol, Sodium PCA, Urea, Sorbitol, Betaine', 'גליצרין, חומצה היאלורונית, פנתנול', '💧 Hydration');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Emollient', 'מרכך', 'מרכך את העור ומחליק קמטים עדינים', 'מרכך ומחליק את מרקם העור', 'Shea Butter, Squalane, Caprylic/Capric Triglyceride, Isopropyl Myristate, Dimethicone, Cetyl Alcohol', 'חמאת שיאה, סקוואלן, דימתיקון', '🧴 Softening');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Surfactant', 'חומר פעיל שטח', 'מנקה לכלוך ושומן מהעור והשיער', 'מנקה את העור והשיער מלכלוך ושומן', 'Sodium Lauryl Sulfate, Cocamidopropyl Betaine, Sodium Cocoyl Isethionate, Decyl Glucoside, Coco-Glucoside', 'SLS, קוקמידופרופיל בטאין', '🫧 Cleansing');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('UV Filter', 'מסנן קרינה', 'מגן על העור מפני קרינת השמש', 'מגן על העור מפני קרינה אולטרה-סגולה', 'Titanium Dioxide, Zinc Oxide, Avobenzone, Octocrylene, Ethylhexyl Methoxycinnamate, Homosalate', 'טיטניום דיאוקסיד, אבוקד אבנזון', '☀️ Sun Protection');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Preservative', 'חומר משמר', 'מונע חיידקים ועובש במוצר הטיפוח', 'שומר על המוצר מפני חיידקים ועובש', 'Phenoxyethanol, Methylparaben, Propylparaben, Benzisothiazolinone, Potassium Sorbate, Sodium Benzoate, Ethylhexylglycerin', 'פנוקסיאתנול, מתילפרבן', '🛡️ Preservation');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Antioxidant', 'נוגד חמצון', 'מגן על העור מפני נזקי זיהום וזקנה', 'מגן מפני רדיקלים חופשיים ומאט הזדקנות', 'Tocopherol, Ascorbic Acid, Retinol, Niacinamide, Green Tea Extract, Resveratrol, Ferulic Acid, Ubiquinone', 'טוקופרול (ויטמין E), חומצה אסקורבית', '🌿 Anti-Aging');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Emulsifier', 'מתחלב', 'מאפשר ערבוב שמן ומים במוצר', 'מחבר בין שמן למים ליצירת קרם אחיד', 'Cetearyl Alcohol + Ceteareth-20, PEG-100 Stearate, Glyceryl Stearate, Polysorbate 60, Sorbitan Oleate', 'צטאריל אלכוהול, גליצריל סטאראט', '🔄 Mixing');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Thickener', 'מעבה', 'נותן למוצר מרקם עבה ונעים', 'מעבה את המוצר ונותן לו מרקם נעים', 'Xanthan Gum, Carbomer, Hydroxyethyl Cellulose, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Cetearyl Alcohol', 'קסנטן גם, קרבומר', '🧪 Texture');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Fragrance', 'ריח / בישום', 'מוסיף ניחוח נעים למוצר הטיפוח', 'נותן למוצר ריח נעים ומפנק', 'Parfum/Fragrance, Linalool, Limonene, Citronellol, Geraniol, Coumarin, Hexyl Cinnamal', 'פרפיום, לינלול, לימונן', '🌸 Scent');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Solvent', 'ממס', 'מפזר וממיס רכיבים אחרים במוצר', 'ממיס ומערבב את הרכיבים השונים במוצר', 'Water (Aqua), Alcohol Denat., Isopropyl Alcohol, Propylene Glycol, Butylene Glycol, Ethoxydiglycol', 'מים, אלכוהול, בוטילן גליקול', '💧 Base');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Chelating Agent', 'חומר כולב / סוכך', 'מונע פגיעה מסידן ומתכות במוצר', 'מנטרל מתכות למניעת פגיעה באיכות המוצר', 'Disodium EDTA, Tetrasodium EDTA, Phytic Acid, Trisodium Ethylenediamine Disuccinate, Citric Acid', 'דינתרן EDTA, חומצת לימון', '⚗️ Stability');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Skin Conditioning', 'מטפח עור', 'מזין ומשפר את מצב העור', 'מזין, מרכך ומשפר את מרקם העור', 'Aloe Barbadensis Leaf Juice, Tocopheryl Acetate, Panthenol, Allantoin, Squalane, Ceramide NP', 'אלוורה, פנתנול, אלנטואין', '✨ Nourishing');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Exfoliant', 'מקלף', 'מסיר תאי עור מתים ומחדש מראה', 'מסיר תאים מתים ומשאיר עור חלק ומחודש', 'Salicylic Acid, Glycolic Acid, Lactic Acid, Polyethylene, Papain, Bromelain, Urea', 'חומצה סליצילית, חומצה גליקולית', '🔄 Renewal');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('pH Adjuster', 'מווסת חומציות', 'מאזן את רמת החומציות במוצר', 'שומר על רמת pH מתאימה ליציבות המוצר', 'Citric Acid, Sodium Hydroxide, Triethanolamine, Aminomethyl Propanol, Lactic Acid', 'חומצת לימון, נתרן הידרוקסיד', '⚖️ Balance');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Colorant', 'צבע', 'נותן למוצר צבע אטרקטיבי', 'מעניק למוצר את הצבע הרצוי', 'CI 77891 (Titanium Dioxide), CI 77491 (Iron Oxide), CI 15850 (Red 7), Ultramarines, Mica', 'טיטניום דיאוקסיד, תחמוצת ברזל', '🎨 Color');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Film Former', 'יוצר שכבה', 'יוצר שכבת הגנה דקה על העור', 'יוצר שכבה שקופה המגנה על פני העור', 'VP/VA Copolymer, PVP, Acrylates Copolymer, Polyquaternium-10, Hydroxyethyl Cellulose', 'PVP, אקרילטים קופולימר', '🎭 Protection');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Opacifier', 'מעמעם', 'הופך מוצר שקוף לבן-אטום', 'הופך את המוצר לאטום ונותן לו מראה קרמי', 'Glycol Distearate, Cetyl Alcohol, Stearyl Alcohol, Titanium Dioxide', 'גליקול דיסטאראט', '🥛 Appearance');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Humectant (Occlusive)', 'חומר חוסם', 'יוצר מחסום שמונע אובדן לחות', 'יוצר שכבת הגנה שנועלת לחות בעור', 'Petrolatum, Mineral Oil, Beeswax, Dimethicone, Lanolin, Paraffin', 'וזלין, שמן מינרלי, שעוות דבורים', '🔒 Moisture Lock');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Astringent', 'מכווץ', 'מכווץ נקבוביות ומפחית שמנוניות', 'מצמצם נקבוביות ומפחית מראה שמנוני', 'Witch Hazel, Alcohol Denat., Aluminum Chlorohydrate, Zinc Sulfate, Tannic Acid', 'המאמליס, אלכוהול', '🎯 Pore Care');
INSERT INTO cosmetic_functions_he (function_en, function_he, consumer_desc_he, consumer_desc_he_alt, inci_examples, inci_examples_he, app_display_category) VALUES ('Viscosity Controller', 'מווסת צמיגות', 'מכוונן את עובי ומרקם המוצר', 'מווסת את צמיגות ומרקם המוצר הסופי', 'Sodium Chloride, Carbomer, Polysorbate 20, PEG-150 Distearate', 'נתרן כלורי, קרבומר', '🔧 Consistency');