-- Add Hebrew names to common E-numbers found in Shufersal data
-- These E-numbers exist in food_additives but lack Hebrew names

UPDATE food_additives SET hebrew_name = 'פוליפוספטים', category_he = 'מייצב' WHERE e_number = 'E452' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'סודיום אצטט', category_he = 'מווסת חומציות' WHERE e_number = 'E262' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'סידן לקטט', category_he = 'מווסת חומציות' WHERE e_number = 'E327' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'טריפוליפוספטים', category_he = 'מייצב' WHERE e_number = 'E451' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'פוליגליצרול פוליריצינולאט', category_he = 'מתחלב' WHERE e_number = 'E476' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'פוליסורבט 80', category_he = 'מתחלב' WHERE e_number = 'E433' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'קרבוקסי מתיל צלולוז', category_he = 'מעבה' WHERE e_number = 'E466' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'מונו ודי גליצרידים', category_he = 'מתחלב' WHERE e_number = 'E471' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'סודיום לקטט', category_he = 'מווסת חומציות' WHERE e_number = 'E325' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'תמצית רוזמרין', category_he = 'נוגד חמצון' WHERE e_number = 'E392' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'מיקרו קריסטלין צלולוז', category_he = 'מעבה' WHERE e_number = 'E460' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'עמילן מותאם', category_he = 'מעבה' WHERE e_number = 'E1442' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'עמילן מותאם', category_he = 'מעבה' WHERE e_number = 'E1404' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'סודיום ניטרט', category_he = 'חומר משמר' WHERE e_number = 'E251' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'סודיום בנזואט', category_he = 'חומר משמר' WHERE e_number = 'E211' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'חומצה סורבית', category_he = 'חומר משמר' WHERE e_number = 'E200' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'אססולפם K', category_he = 'ממתיק' WHERE e_number = 'E950' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'סוכרלוז', category_he = 'ממתיק' WHERE e_number = 'E955' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'אספרטם', category_he = 'ממתיק' WHERE e_number = 'E951' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'סטביול גליקוזידים', category_he = 'ממתיק' WHERE e_number = 'E960' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'חומצה לקטית', category_he = 'מווסת חומציות' WHERE e_number = 'E270' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'חומצה פוספורית', category_he = 'מווסת חומציות' WHERE e_number = 'E338' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'חומצה מלית', category_he = 'מווסת חומציות' WHERE e_number = 'E296' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'חומצה אסקורבית', category_he = 'נוגד חמצון' WHERE e_number = 'E300' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'סודיום אסקורבט', category_he = 'נוגד חמצון' WHERE e_number = 'E301' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'סודיום אריתורבט', category_he = 'נוגד חמצון' WHERE e_number = 'E316' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'BHA', category_he = 'נוגד חמצון' WHERE e_number = 'E320' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'BHT', category_he = 'נוגד חמצון' WHERE e_number = 'E321' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'לציטין', category_he = 'מתחלב' WHERE e_number = 'E322' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'סודיום ציטרט', category_he = 'מווסת חומציות' WHERE e_number = 'E331' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'אגר', category_he = 'מעבה' WHERE e_number = 'E406' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'אלגינט', category_he = 'מעבה' WHERE e_number = 'E401' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'גומי ג''לן', category_he = 'מעבה' WHERE e_number = 'E418' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'סורביטול', category_he = 'ממתיק' WHERE e_number = 'E420' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'מניטול', category_he = 'ממתיק' WHERE e_number = 'E421' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'סורביטן מונוסטארט', category_he = 'מתחלב' WHERE e_number = 'E491' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'קסיליטול', category_he = 'ממתיק' WHERE e_number = 'E967' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'גומי ערבי', category_he = 'מעבה' WHERE e_number = 'E414' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'פוליסורבט 60', category_he = 'מתחלב' WHERE e_number = 'E435' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'גומי קסנטן', category_he = 'מעבה' WHERE e_number = 'E415' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'דו תחמוצת הגופרית', category_he = 'חומר משמר' WHERE e_number = 'E220' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'ניסין', category_he = 'חומר משמר' WHERE e_number = 'E234' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'נטמיצין', category_he = 'חומר משמר' WHERE e_number = 'E235' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'קרמל', category_he = 'צבע מאכל' WHERE e_number = 'E150a' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'ביטא קרוטן', category_he = 'צבע מאכל' WHERE e_number = 'E160a' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'אנאטו', category_he = 'צבע מאכל' WHERE e_number = 'E160b' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'דו תחמוצת הטיטניום', category_he = 'צבע מאכל' WHERE e_number = 'E171' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'פחם צמחי', category_he = 'צבע מאכל' WHERE e_number = 'E153' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'חומצה טרטרית', category_he = 'מווסת חומציות' WHERE e_number = 'E334' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'קלציום כלוריד', category_he = 'מייצב' WHERE e_number = 'E509' AND (hebrew_name IS NULL OR hebrew_name = '');
UPDATE food_additives SET hebrew_name = 'אינוזיטול', category_he = 'ויטמין' WHERE e_number = 'E Inositol' AND (hebrew_name IS NULL OR hebrew_name = '');
