UPDATE food_additives SET health_concerns_he = 'שם מסחרי לאיזומלט; אותו פרופיל בטיחות' WHERE health_concerns = 'Commercial brand name for isomalt; same profile';
UPDATE food_additives SET health_concerns_he = 'מטבוליט נפוץ; ערך צריכה יומית מותרת לגליקוזידי סטביול מבוטא בשווי ערך סטביול' WHERE health_concerns = 'Common aglycone metabolite; ADI for steviol glycosides expressed as steviol equivalents';
UPDATE food_additives SET health_concerns_he = 'תערובת מסחרית נפוצה; פרופיל בטיחות של כל רכיב בנפרד' WHERE health_concerns = 'Common commercial blend; individual safety profiles apply';
UPDATE food_additives SET health_concerns_he = 'מכיל נגזרת פנילאלנין ברמות זניחות; יציב בחום' WHERE health_concerns = 'Contains phenylalanine derivative but at negligible levels; heat stable';
UPDATE food_additives SET health_concerns_he = 'מכיל פנילאלנין; חומרי מילוי מוסיפים קלוריות; אזהרת PKU' WHERE health_concerns = 'Contains phenylalanine; fillers add calories; PKU warning';
UPDATE food_additives SET health_concerns_he = 'מכיל שאריות קסילוז; גליקוזיד סטביול משני' WHERE health_concerns = 'Contains xylose residue; minor steviol glycoside';
UPDATE food_additives SET health_concerns_he = 'צורת D מתוקה בעוד צורת L מרה; עניין מחקרי' WHERE health_concerns = 'D-form is sweet while L-form is bitter; research interest';
UPDATE food_additives SET health_concerns_he = 'תוצר פירוק של Reb A; מעט מר' WHERE health_concerns = 'Degradation product of Reb A; slightly bitter';
UPDATE food_additives SET health_concerns_he = 'מופק מהדרים; טעם מתוק מתמשך; EFSA 2022 אישר בטיחות' WHERE health_concerns = 'Derived from citrus; lingering sweet aftertaste; EFSA 2022 confirmed safety';
UPDATE food_additives SET health_concerns_he = 'מתפרק לאספרטיים ואצסולפיים בגוף; אזהרת PKU חלה' WHERE health_concerns = 'Dissociates into aspartame and acesulfame in body; PKU warning applies';
UPDATE food_additives SET health_concerns_he = 'חדש; תכונות אנטי-מיקרוביאליות' WHERE health_concerns = 'Emerging; antimicrobial properties';
UPDATE food_additives SET health_concerns_he = 'חדש; רגיש לחום' WHERE health_concerns = 'Emerging; heat-sensitive';
UPDATE food_additives SET health_concerns_he = 'מיוצר בדרך אנזימטית; אותו פרופיל בטיחות כמו אלולוז' WHERE health_concerns = 'Enzymatic production route; same safety profile as allulose';
UPDATE food_additives SET health_concerns_he = 'צורת חומצה חופשית; מלח אשלגן (E950) הוא הצורה המסחרית' WHERE health_concerns = 'Free acid form; potassium salt (E950) is the commercial form';
UPDATE food_additives SET health_concerns_he = 'מווסת חומציות כללי; בדרך כלל חומצות מזון בטוחות' WHERE health_concerns = 'General acidity regulator; usually safe food acids';
UPDATE food_additives SET health_concerns_he = 'חומצת מזון כללית; בדרך כלל חומצת לימון או חומצה לקטית' WHERE health_concerns = 'General food acid; usually citric or lactic acid';
UPDATE food_additives SET health_concerns_he = 'קטגוריית מייצב כללית; הבטיחות תלויה בתרכובת הספציפית' WHERE health_concerns = 'General stabilizer category; safety depends on specific compound';
UPDATE food_additives SET health_concerns_he = 'מונח כללי לתרביות חיידקים לתסיסה.' WHERE health_concerns = 'General term for bacterial starter cultures.';
UPDATE food_additives SET health_concerns_he = 'מונח כללי לאנזימי מזון (עמילאז, פרוטאז, ליפאז). חומרי עיבוד.' WHERE health_concerns = 'General term for food enzymes (amylase, protease, lipase). Processing aids.';
UPDATE food_additives SET health_concerns_he = 'מונח כללי לפלפלים חריפים. מכיל קפסאיצין.' WHERE health_concerns = 'General term for hot peppers. Contains capsaicin.';
UPDATE food_additives SET health_concerns_he = 'קטגוריית מעבה כללית; הבטיחות תלויה בתרכובת הספציפית' WHERE health_concerns = 'General thickener category; safety depends on specific compound';
UPDATE food_additives SET health_concerns_he = 'נחשב בטוח בדרך כלל; הערכה מחדש של EFSA 2025 העלתה ADI ל-15 מ"ג/ק"ג' WHERE health_concerns = 'Generally considered safe; EFSA 2025 re-evaluation raised ADI to 15 mg/kg';
UPDATE food_additives SET health_concerns_he = 'בטיחות גליצרול מבוססת היטב במזון' WHERE health_concerns = 'Glycerol safety well-established in food';
UPDATE food_additives SET health_concerns_he = 'פלפלים מיובשים טחונים. צבע וטעם עדין. מקור לקפסנטין.' WHERE health_concerns = 'Ground dried peppers. Color and mild flavor. Source of capsanthin.';
UPDATE food_additives SET health_concerns_he = 'דווח על שיבוש מיקרוביום המעי' WHERE health_concerns = 'Gut microbiome disruption reported';
UPDATE food_additives SET health_concerns_he = 'כאבי ראש, עצבנות במינונים גבוהים' WHERE health_concerns = 'Headache, irritability at higher doses';
UPDATE food_additives SET health_concerns_he = 'ירק בריא; עשיר בבטא-קרוטן' WHERE health_concerns = 'Healthy vegetable; rich in beta-carotene';
UPDATE food_additives SET health_concerns_he = 'יציב בחום; ייצור מסחרי מוגבל; שימוש מסורתי במחוז יונאן' WHERE health_concerns = 'Heat stable; limited commercial production; traditional use in Yunnan Province';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי גבוה; משמש כחלופת ''תווית נקייה'' לסירופ תירס' WHERE health_concerns = 'High GI; used as ''clean label'' alternative to corn syrup';
UPDATE food_additives SET health_concerns_he = 'יציבות גבוהה בחום; משלשל מעל 20-30 גרם/יום; השפעה גליקמית נמוכה יותר ממלטיטול' WHERE health_concerns = 'High heat stability; laxative at >20-30g/day; lower GI impact than maltitol';
UPDATE food_additives SET health_concerns_he = 'שמן זית מהדרגה הגבוהה ביותר. עשיר בחומצה אולאית ופוליפנולים.' WHERE health_concerns = 'Highest grade olive oil. Rich in oleic acid, polyphenols.';
UPDATE food_additives SET health_concerns_he = 'שיבוש הורמונלי; משבש אנדוקריני; אסור במזון באיחוד האירופי מ-2006' WHERE health_concerns = 'Hormone disruption; endocrine disruptor; banned in EU food since 2006';
UPDATE food_additives SET health_concerns_he = 'אוליגוסכריד מחלב אם; יתרונות חיסוניים; מתוק במעט' WHERE health_concerns = 'Human milk oligosaccharide; immune benefits; mildly sweet';
UPDATE food_additives SET health_concerns_he = 'IARC 2B יולי 2023; מכון ויצמן: שינוי מיקרוביוטת המעי; אוניברסיטת בן גוריון: רעיל לחיידקי מעי; ישראל ללא אזהרה' WHERE health_concerns = 'IARC 2B July 2023; Weizmann: altered gut microbiota; BGU: toxic to gut bacteria; Israel no warning';
UPDATE food_additives SET health_concerns_he = 'פרופיל טעם משופר לעומת גליקוזידי סטביול סטנדרטיים' WHERE health_concerns = 'Improved taste profile vs standard steviol glycosides';
UPDATE food_additives SET health_concerns_he = 'פרופיל טעם משופר; פחות מר מ-Reb A' WHERE health_concerns = 'Improved taste profile; less bitter than Reb A';
UPDATE food_additives SET health_concerns_he = 'אינרטי; בטוח בכמויות קטנות' WHERE health_concerns = 'Inert; safe in small quantities';
UPDATE food_additives SET health_concerns_he = 'אין מספיק נתונים לשימוש במזון' WHERE health_concerns = 'Insufficient data for food use';
UPDATE food_additives SET health_concerns_he = 'אין מספיק נתוני בטיחות למזון' WHERE health_concerns = 'Insufficient safety data for food';
UPDATE food_additives SET health_concerns_he = 'העשרת ברזל בקמח/דגנים. נפוץ במוצרי חיטה מועשרים.' WHERE health_concerns = 'Iron fortification in flour/cereals. Common in enriched wheat products.';
UPDATE food_additives SET health_concerns_he = 'עומס ברזל בעודף' WHERE health_concerns = 'Iron overload at excess';
UPDATE food_additives SET health_concerns_he = 'סיכון לעומס ברזל' WHERE health_concerns = 'Iron overload risk';
UPDATE food_additives SET health_concerns_he = 'מגרה בריכוזים גבוהים' WHERE health_concerns = 'Irritant at high concentrations';
UPDATE food_additives SET health_concerns_he = 'יפן מסווגת כ-0 קלוריות/גרם; מאושר ביפן מאז 2010; אישור קוריאני 2012' WHERE health_concerns = 'Japan classifies at 0 kcal/g; approved since 2010 in Japan; Korean approval 2012';
UPDATE food_additives SET health_concerns_he = 'רעילות כליות/כבד, אסור לשימוש' WHERE health_concerns = 'Kidney/liver toxicity, banned';
UPDATE food_additives SET health_concerns_he = 'L-ארבינוז עשוי לעכב אנזים סוכראז; ריבוז משמש לאנרגיה/ביצועי ספורט' WHERE health_concerns = 'L-Arabinose may inhibit sucrase enzyme; ribose used for energy/sports performance';
UPDATE food_additives SET health_concerns_he = 'תרכובת מעבדה; החומר המתוק ביותר הידוע בעולם' WHERE health_concerns = 'Laboratory compound; world''s sweetest known substance';
UPDATE food_additives SET health_concerns_he = 'משלשל בסף נמוך יותר מסורביטול (~10-20 גרם); השפעות אוסמוטיות; תחושת קרירות' WHERE health_concerns = 'Laxative at lower threshold than sorbitol (~10-20g); osmotic effects; cooling sensation';
UPDATE food_additives SET health_concerns_he = 'משלשל; נתוני בטיחות מזון מוגבלים' WHERE health_concerns = 'Laxative; limited food safety data';
UPDATE food_additives SET health_concerns_he = 'חומצת תפיחה. משמשת עם סודה לשתייה. גם מונעת השחמת תפוחי אדמה.' WHERE health_concerns = 'Leavening acid. Used with baking soda. Also prevents darkening in potatoes.';
UPDATE food_additives SET health_concerns_he = 'פחות מתוק; יותר מר מ-Reb A; בדרך כלל רכיב משני' WHERE health_concerns = 'Less sweet; more bitter than Reb A; usually minor component';
UPDATE food_additives SET health_concerns_he = 'אישורים מוגבלים בעולם; יציב בחום' WHERE health_concerns = 'Limited approvals globally; heat stable';
UPDATE food_additives SET health_concerns_he = 'נתונים מוגבלים; נראה נסבל היטב במינונים שנחקרו' WHERE health_concerns = 'Limited data; appears well-tolerated at studied doses';
UPDATE food_additives SET health_concerns_he = 'נתונים מוגבלים; נראה נסבל היטב בטווח הקצר' WHERE health_concerns = 'Limited data; appears well-tolerated short-term';
UPDATE food_additives SET health_concerns_he = 'אישור מזון מוגבל' WHERE health_concerns = 'Limited food approval';
UPDATE food_additives SET health_concerns_he = 'נתוני בטיחות מזון מוגבלים' WHERE health_concerns = 'Limited food safety data';
UPDATE food_additives SET health_concerns_he = 'נתוני בטיחות מוגבלים; שימוש מוגבל' WHERE health_concerns = 'Limited safety data; restricted use';
UPDATE food_additives SET health_concerns_he = 'נתונים טוקסיקולוגיים מוגבלים' WHERE health_concerns = 'Limited toxicological data';
UPDATE food_additives SET health_concerns_he = 'מתיקות מתמשכת; משמש להסוואת מרירות' WHERE health_concerns = 'Lingering sweetness; used to mask bitterness';
UPDATE food_additives SET health_concerns_he = 'מלטודקסטרין כמילוי מוסיף קלוריות ומעלה אינדקס גליקמי לעומת סוכרלוז טהור' WHERE health_concerns = 'Maltodextrin filler adds calories and raises GI vs pure sucralose';
UPDATE food_additives SET health_concerns_he = 'מסווה חוסר B12; עלול לקדם גידולים קולורקטליים; פרכוסים במשתמשי תרופות נוגדות פרכוסים' WHERE health_concerns = 'Masks B12 deficiency; May promote colorectal neoplasms; Seizures in anticonvulsant users';
UPDATE food_additives SET health_concerns_he = 'עלול להחמיר מצבים דלקתיים' WHERE health_concerns = 'May exacerbate inflammatory conditions';
UPDATE food_additives SET health_concerns_he = 'עלול להפחית ספיגת תרופות' WHERE health_concerns = 'May reduce drug absorption';
UPDATE food_additives SET health_concerns_he = 'עלול להפחית ספיגת תרופות/תזונה' WHERE health_concerns = 'May reduce drug/nutrient absorption';
UPDATE food_additives SET health_concerns_he = 'עלול להפחית יעילות תרופות; אזהרת אינטראקציה עם תרופות' WHERE health_concerns = 'May reduce medication efficacy; drug interaction warning';
UPDATE food_additives SET health_concerns_he = 'עשב ים תיכוני. מכיל קרבקרול (אנטי-מיקרוביאלי).' WHERE health_concerns = 'Mediterranean herb. Contains carvacrol (antimicrobial).';
UPDATE food_additives SET health_concerns_he = 'פלפל חריף בינוני. מכיל קפסאיצין.' WHERE health_concerns = 'Medium-hot chili pepper. Contains capsaicin.';
UPDATE food_additives SET health_concerns_he = 'רכיב משני בתמצית פרי הנזיר' WHERE health_concerns = 'Minor component of monk fruit extract';
UPDATE food_additives SET health_concerns_he = 'גליקוזיד סטביול משני; פחות מתוק מסטביוזיד' WHERE health_concerns = 'Minor steviol glycoside; less sweet than stevioside';
UPDATE food_additives SET health_concerns_he = 'טעם מר יותר מ-Reb A; שימוש מסורתי בדרום אמריקה' WHERE health_concerns = 'More bitter aftertaste than Reb A; traditional use in South America';
UPDATE food_additives SET health_concerns_he = 'הצורה הנפוצה ביותר של סכרין בשימוש מסחרי' WHERE health_concerns = 'Most common form of saccharin used commercially';
UPDATE food_additives SET health_concerns_he = 'גליקוזיד הסטביול הנפוץ ביותר; טעם מתוק נקי' WHERE health_concerns = 'Most commonly used steviol glycoside; clean sweet taste';
UPDATE food_additives SET health_concerns_he = 'לא רלוונטי' WHERE health_concerns = 'N/A';
UPDATE food_additives SET health_concerns_he = 'אישור חדש; נחשב בטוח' WHERE health_concerns = 'New approval; considered safe';
UPDATE food_additives SET health_concerns_he = 'חדש; בטיחות הוערכה על ידי FDA' WHERE health_concerns = 'New; safety evaluated by FDA';
UPDATE food_additives SET health_concerns_he = 'מסלול ניטרוזאמין; עצומה של 500K+ באיחוד האירופי לאיסור' WHERE health_concerns = 'Nitrosamine pathway; EU 500K+ petition for ban';
UPDATE food_additives SET health_concerns_he = 'אין רעילות ידועה (עודף מופרש בשתן; צביעה צהובה)' WHERE health_concerns = 'No known toxicity (excess excreted in urine; yellow discoloration)';
UPDATE food_additives SET health_concerns_he = 'אין רעילות ידועה ממזון או תוספים; עלול לפגוע בטיפול נוגד קרישה' WHERE health_concerns = 'No known toxicity from food or supplements; May impair anticoagulant therapy';
UPDATE food_additives SET health_concerns_he = 'אין רעילות ידועה מצריכה דרך הפה' WHERE health_concerns = 'No known toxicity from oral intake';
UPDATE food_additives SET health_concerns_he = 'לא גורם עששת; משלשל במינונים גבוהים' WHERE health_concerns = 'Non-cariogenic; laxative at high oral doses';
UPDATE food_additives SET health_concerns_he = 'לא גורם עששת; מתעכל באיטיות' WHERE health_concerns = 'Non-cariogenic; slowly digested';
UPDATE food_additives SET health_concerns_he = 'לא גורם עששת; מתעכל באיטיות; בשימוש ביפן מאז שנות ה-70' WHERE health_concerns = 'Non-cariogenic; slowly digested; used in Japan since 1970s';
UPDATE food_additives SET health_concerns_he = 'אין בחשיפה למינונים מומלצים' WHERE health_concerns = 'None at recommended doses';
UPDATE food_additives SET health_concerns_he = 'לא הוערך לבטיחות מזון' WHERE health_concerns = 'Not evaluated for food safety';
UPDATE food_additives SET health_concerns_he = 'לא לשימוש במזון' WHERE health_concerns = 'Not for food use';
UPDATE food_additives SET health_concerns_he = 'לא למזון; לשימוש בתרופות/קוסמטיקה בלבד' WHERE health_concerns = 'Not for food; drug/cosmetic use only';
UPDATE food_additives SET health_concerns_he = 'לא למזון; שימוש תרופתי מוגבל' WHERE health_concerns = 'Not for food; restricted drug use';
UPDATE food_additives SET health_concerns_he = 'לא לצריכת אדם בדרגה זו' WHERE health_concerns = 'Not for human consumption at this grade';
UPDATE food_additives SET health_concerns_he = 'לא לצריכת מזון אנושית' WHERE health_concerns = 'Not for human food consumption';
UPDATE food_additives SET health_concerns_he = 'רק גליקוזידי סטביול מזוקקים (≥95%) מאושרים; עלה שלם אסור בארה"ב/אירופה' WHERE health_concerns = 'Only purified steviol glycosides (ג‰¥95%) are approved; whole leaf not permitted in US/EU';
UPDATE food_additives SET health_concerns_he = 'תמצית טעם ממשפחת הסחלב. מכיל וניליין. התבלין היקר ביותר לפי משקל.' WHERE health_concerns = 'Orchid-derived flavoring. Contains vanillin. Most expensive spice by weight.';
UPDATE food_additives SET health_concerns_he = 'חלק מ-E471. מתחלב מגליצרול + חומצת שומן.' WHERE health_concerns = 'Part of E471. Emulsifier from glycerol + fatty acid.';
UPDATE food_additives SET health_concerns_he = 'נוירופתיה היקפית; אטקסיה חושית; אובדן תחושה' WHERE health_concerns = 'Peripheral neuropathy; Sensory ataxia; Loss of sensation';
UPDATE food_additives SET health_concerns_he = 'שומן מהצומח; עשוי להכיל שמן דקל או שומנים מוקשים' WHERE health_concerns = 'Plant-derived fat; may contain palm oil or hydrogenated fats';
UPDATE food_additives SET health_concerns_he = 'צורת רבים של טעם מלאכותי.' WHERE health_concerns = 'Plural of Artificial Flavor.';
UPDATE food_additives SET health_concerns_he = 'צורת רבים של חומר טעם. מונח כללי.' WHERE health_concerns = 'Plural of Flavoring. Generic term.';
UPDATE food_additives SET health_concerns_he = 'צורת רבים של בצל. ירק שורש.' WHERE health_concerns = 'Plural of Onion. Root vegetable.';
UPDATE food_additives SET health_concerns_he = 'שמן צמחי רב בלתי רווי. עשיר באומגה-6.' WHERE health_concerns = 'Polyunsaturated vegetable oil. High omega-6.';
UPDATE food_additives SET health_concerns_he = 'נספג בצורה גרועה; משמש בבדיקת ספיגת קסילוז; חומר מוצא לקסיליטול' WHERE health_concerns = 'Poorly absorbed; used in xylose absorption test; precursor to xylitol';
UPDATE food_additives SET health_concerns_he = 'נספג בצורה גרועה; משמש יותר לבריאות דרכי השתן מאשר כממתיק' WHERE health_concerns = 'Poorly absorbed; used more for urinary health than sweetness';
UPDATE food_additives SET health_concerns_he = 'פופולרי בדיאטות קטו/דלות פחמימות; אזהרת ADI של אריתריטול חלה' WHERE health_concerns = 'Popular in keto/low-carb diets; erythritol ADI caution applies';
UPDATE food_additives SET health_concerns_he = 'תערובת אפס קלוריות פופולרית; אזהרת ADI של EFSA לאריתריטול חלה' WHERE health_concerns = 'Popular zero-calorie blend; EFSA erythritol ADI caution applies';
UPDATE food_additives SET health_concerns_he = 'חומר מוצא ללוגדונאם; מחקר בלבד' WHERE health_concerns = 'Precursor to lugduname; research only';
UPDATE food_additives SET health_concerns_he = 'בעיקר חומר מרקם; תרומת מתיקות מינימלית' WHERE health_concerns = 'Primarily a texturizer; minimal sweetness contribution';
UPDATE food_additives SET health_concerns_he = 'מטבוליט פורין; עליית חומצת שתן באנשים רגישים' WHERE health_concerns = 'Purine metabolite; uric acid elevation in susceptible individuals';
UPDATE food_additives SET health_concerns_he = 'תגובות אלרגיות/אנפילקטיות נדירות' WHERE health_concerns = 'Rare allergic/anaphylactic reactions';
UPDATE food_additives SET health_concerns_he = 'מרירות מופחתת לעומת גליקוזידי סטביול סטנדרטיים' WHERE health_concerns = 'Reduced bitterness vs standard steviol glycosides';
UPDATE food_additives SET health_concerns_he = 'פרסתזיה מופחתת לעומת שחרור מיידי' WHERE health_concerns = 'Reduced paresthesia vs. instant release';
UPDATE food_additives SET health_concerns_he = 'קשור לפרי הנזיר אך מין שונה; הערכה רגולטורית מוגבלת' WHERE health_concerns = 'Related to monk fruit but different species; limited regulatory evaluation';
UPDATE food_additives SET health_concerns_he = 'סוג מחקרי; לחלק מהחברים שימוש מסורתי' WHERE health_concerns = 'Research class; some members have traditional use';
UPDATE food_additives SET health_concerns_he = 'מוגבל לשימוש שאינו מזון; שימוש תרופתי מוגבל' WHERE health_concerns = 'Restricted to non-food; limited drug use';
UPDATE food_additives SET health_concerns_he = 'משקעים גבישיים ברשתית במינונים גבוהים; מגבלות מזון מחמירות' WHERE health_concerns = 'Retinal crystal deposits at high human doses; strict feed limits';
UPDATE food_additives SET health_concerns_he = 'ירק שורש. גידול מרכזי. ממשפחת הסולניים.' WHERE health_concerns = 'Root vegetable. Major crop. Nightshade family.';
UPDATE food_additives SET health_concerns_he = 'בטיחות סכרין אושרה מחדש על ידי EFSA 2024; חומרי מילוי מוסיפים קלוריות' WHERE health_concerns = 'Saccharin safety reaffirmed by EFSA 2024; fillers add calories';
UPDATE food_additives SET health_concerns_he = 'בטוח כתוסף תזונה; לא כתוסף צבע' WHERE health_concerns = 'Safe as supplement; not as color additive';
UPDATE food_additives SET health_concerns_he = 'בטוח ב-ADI; תכולת נחושת מנוטרת' WHERE health_concerns = 'Safe at ADI; copper content monitored';
UPDATE food_additives SET health_concerns_he = 'בטוח ברמות מאושרות' WHERE health_concerns = 'Safe at approved levels';
UPDATE food_additives SET health_concerns_he = 'בטוח ברמות מזון רגילות' WHERE health_concerns = 'Safe at normal food levels';
UPDATE food_additives SET health_concerns_he = 'בטוח ברמות מוגבלות' WHERE health_concerns = 'Safe at restricted levels';
UPDATE food_additives SET health_concerns_he = 'בטוח ל-DHA; לא צבע ראשי' WHERE health_concerns = 'Safe for DHA; not a primary colorant';
UPDATE food_additives SET health_concerns_he = 'בטוח בקוסמטיקה; לא לצביעת מזון' WHERE health_concerns = 'Safe in cosmetics; not for food coloring';
UPDATE food_additives SET health_concerns_he = 'בטוח לשימוש בהזנת בעלי חיים' WHERE health_concerns = 'Safe in feed use';
UPDATE food_additives SET health_concerns_he = 'בטוח במזון; מרכיב מסורתי' WHERE health_concerns = 'Safe in food; traditional ingredient';
UPDATE food_additives SET health_concerns_he = 'בטוח בכמויות מתונות. הגבלה לילדים ונשים בהריון.' WHERE health_concerns = 'Safe in moderate amounts. Limit for children and pregnant women.';
UPDATE food_additives SET health_concerns_he = 'בטוח בכמויות קטנות' WHERE health_concerns = 'Safe in small amounts';
UPDATE food_additives SET health_concerns_he = 'בטוח בשימוש מסורתי אסיאתי' WHERE health_concerns = 'Safe in traditional Asian use';
UPDATE food_additives SET health_concerns_he = 'בטוח בשימוש מסורתי; נפוץ ביפן' WHERE health_concerns = 'Safe in traditional use; widely used in Japan';
UPDATE food_additives SET health_concerns_he = 'בטוח; יציב בחומצה' WHERE health_concerns = 'Safe; acid-stable';
UPDATE food_additives SET health_concerns_he = 'בטוח; יקר' WHERE health_concerns = 'Safe; expensive';
UPDATE food_additives SET health_concerns_he = 'בטוח; תבלין יקר' WHERE health_concerns = 'Safe; expensive spice';
UPDATE food_additives SET health_concerns_he = 'בטוח; יתרונות לבריאות העיניים' WHERE health_concerns = 'Safe; eye health benefits';
UPDATE food_additives SET health_concerns_he = 'בטוח; גוסיפול הוסר' WHERE health_concerns = 'Safe; gossypol removed';
UPDATE food_additives SET health_concerns_he = 'בטוח; רגיש לחום ול-pH' WHERE health_concerns = 'Safe; heat and pH sensitive';
UPDATE food_additives SET health_concerns_he = 'בטוח; אנתוציאנינים יציבים בחום' WHERE health_concerns = 'Safe; heat stable anthocyanins';
UPDATE food_additives SET health_concerns_he = 'בטוח; רגיש לחום' WHERE health_concerns = 'Safe; heat-sensitive';
UPDATE food_additives SET health_concerns_he = 'בטוח; רגיש לחום ול-pH' WHERE health_concerns = 'Safe; heat-sensitive; pH-sensitive';
UPDATE food_additives SET health_concerns_he = 'בטוח; בריאות המקולה' WHERE health_concerns = 'Safe; macular health';
UPDATE food_additives SET health_concerns_he = 'בטוח; תכונות מרגיעות קלות' WHERE health_concerns = 'Safe; mild sedative properties';
UPDATE food_additives SET health_concerns_he = 'בטוח; עיבוד מינימלי' WHERE health_concerns = 'Safe; minimal processing';
UPDATE food_additives SET health_concerns_he = 'בטוח; חייב להיות מבושל (גולמי מכיל אוקסלטים)' WHERE health_concerns = 'Safe; must be cooked (raw contains oxalates)';
UPDATE food_additives SET health_concerns_he = 'בטוח; ייצור זהה לטבע' WHERE health_concerns = 'Safe; nature-identical production';
UPDATE food_additives SET health_concerns_he = 'בטוח; לא זהה ל-E123' WHERE health_concerns = 'Safe; not the same as E123';
UPDATE food_additives SET health_concerns_he = 'בטוח; מרכיב מזון חדשני' WHERE health_concerns = 'Safe; novel food ingredient';
UPDATE food_additives SET health_concerns_he = 'בטוח; עשיר בערכים תזונתיים' WHERE health_concerns = 'Safe; nutrient-dense';
UPDATE food_additives SET health_concerns_he = 'בטוח; תוסף תזונה' WHERE health_concerns = 'Safe; nutritional supplement';
UPDATE food_additives SET health_concerns_he = 'בטוח; ירק עלים מזין' WHERE health_concerns = 'Safe; nutritious leafy green';
UPDATE food_additives SET health_concerns_he = 'בטוח; תכונות מחוון pH' WHERE health_concerns = 'Safe; pH indicator properties';
UPDATE food_additives SET health_concerns_he = 'בטוח; צבע כחול תלוי pH' WHERE health_concerns = 'Safe; pH-dependent blue color';
UPDATE food_additives SET health_concerns_he = 'בטוח; רגיש ל-pH' WHERE health_concerns = 'Safe; pH-sensitive';
UPDATE food_additives SET health_concerns_he = 'בטוח; צבע רגיש ל-pH' WHERE health_concerns = 'Safe; pH-sensitive color';
UPDATE food_additives SET health_concerns_he = 'בטוח; עשיר באנתוציאנינים' WHERE health_concerns = 'Safe; rich in anthocyanins';
UPDATE food_additives SET health_concerns_he = 'בטוח; מתוקנן לצבע אחיד' WHERE health_concerns = 'Safe; standardized for consistent color';
UPDATE food_additives SET health_concerns_he = 'בטוח; סופרפוד' WHERE health_concerns = 'Safe; superfood';
UPDATE food_additives SET health_concerns_he = 'בטוח; מרכיב יפני מסורתי' WHERE health_concerns = 'Safe; traditional Japanese ingredient';
UPDATE food_additives SET health_concerns_he = 'בטוח; תכולת קרוטנואידים גבוהה מאוד' WHERE health_concerns = 'Safe; very high carotenoid content';
UPDATE food_additives SET health_concerns_he = 'צורת מלח של סכרין' WHERE health_concerns = 'Salt form of saccharin';
UPDATE food_additives SET health_concerns_he = 'זהה לעמילן תירס. איות חלופי.' WHERE health_concerns = 'Same as Corn Starch. Alternate spelling.';
UPDATE food_additives SET health_concerns_he = 'זהה לאבקת שום אך גס יותר.' WHERE health_concerns = 'Same as Garlic Powder but coarser.';
UPDATE food_additives SET health_concerns_he = 'זהה לעמילן מזון מותאם. וריאנט תיוג אמריקאי.' WHERE health_concerns = 'Same as Modified Food Starch. US labeling variant.';
UPDATE food_additives SET health_concerns_he = 'זהה לאלולוז נוזלי; צורה גבישית להחלפה ישירה; יכולת השחמת מאייר' WHERE health_concerns = 'Same as liquid allulose; crystalline form for direct substitution; Maillard browning capacity';
UPDATE food_additives SET health_concerns_he = 'זהה לאספרטיים רגיל; ציפוי משפר יציבות תרמית' WHERE health_concerns = 'Same as standard aspartame; coating improves thermal stability';
UPDATE food_additives SET health_concerns_he = 'הרעלת עופרת חמורה; סקרנות היסטורית בלבד; רעיל ביותר' WHERE health_concerns = 'Severe lead poisoning; historical curiosity only; extremely toxic';
UPDATE food_additives SET health_concerns_he = 'דומה ל-E473' WHERE health_concerns = 'Similar to E473';
UPDATE food_additives SET health_concerns_he = 'צורת יחיד. תרבית חיידקים לייצור גבינה.' WHERE health_concerns = 'Single form. Bacterial starter culture for cheese production.';
UPDATE food_additives SET health_concerns_he = 'צורת יחיד של תבלינים.' WHERE health_concerns = 'Singular form of Spices.';
UPDATE food_additives SET health_concerns_he = 'צורת יחיד.' WHERE health_concerns = 'Singular form.';
UPDATE food_additives SET health_concerns_he = 'צורת יחיד של חלמונים.' WHERE health_concerns = 'Singular of Egg Yolks.';
UPDATE food_additives SET health_concerns_he = 'צורת יחיד של ביצים.' WHERE health_concerns = 'Singular of Eggs.';
UPDATE food_additives SET health_concerns_he = 'צורת מלח נתרן של ציקלמט; אסור בארה"ב מאז 1969' WHERE health_concerns = 'Sodium salt form of cyclamate; banned in US since 1969';
UPDATE food_additives SET health_concerns_he = 'עמילן מותאם לשימושי מזון. המקור משתנה (תירס, תפוח אדמה, טפיוקה).' WHERE health_concerns = 'Starch modified for food applications. Source varies (corn, potato, tapioca).';
UPDATE food_additives SET health_concerns_he = 'דומה מבנית לסטביוזיד; שימוש מסורתי בסין' WHERE health_concerns = 'Structurally similar to stevioside; traditional use in China';
UPDATE food_additives SET health_concerns_he = 'מינונים תת-ממתיקים משפרים ומעגלים טעמים' WHERE health_concerns = 'Sub-sweetening doses enhance and round out flavors';
UPDATE food_additives SET health_concerns_he = 'סוכרלוז מסווה את מרירות הסטיביה; גישת ניסוח פופולרית' WHERE health_concerns = 'Sucralose masks stevia bitterness; popular formulation approach';
UPDATE food_additives SET health_concerns_he = 'רגישות לסולפיטים' WHERE health_concerns = 'Sulfite sensitivity';
UPDATE food_additives SET health_concerns_he = 'תערובת סינרגיסטית המשמשת ברוב מותגי משקאות הדיאט; מסווה טעמי לוואי' WHERE health_concerns = 'Synergistic blend used in most major diet beverage brands; masks off-flavors';
UPDATE food_additives SET health_concerns_he = 'מתיקות סינרגיסטית; בטיחות כל רכיב בנפרד' WHERE health_concerns = 'Synergistic sweetness; individual component safety applies';
UPDATE food_additives SET health_concerns_he = 'צורת סירופ ליישומים נוזליים; אותה בטיחות כמו גבישי' WHERE health_concerns = 'Syrup form for liquid applications; same safety as crystalline';
UPDATE food_additives SET health_concerns_he = 'שיבוש בלוטת התריס; אנמיה המוליטית - תינוקות הכי פגיעים' WHERE health_concerns = 'Thyroid disruption; hemolytic anemia – infants most vulnerable';
UPDATE food_additives SET health_concerns_he = 'הפרעת בלוטת תריס בעודף' WHERE health_concerns = 'Thyroid dysfunction at excess';
UPDATE food_additives SET health_concerns_he = 'שיבוש תפקוד בלוטת התריס (מעכב קליטת יוד); השפעות התפתחותיות בעוברים/תינוקות' WHERE health_concerns = 'Thyroid function disruption (inhibits iodine uptake); developmental effects in fetuses/infants';
UPDATE food_additives SET health_concerns_he = 'עיכוב קליטת יוד בתריס - קריטי להתפתחות עצבית בתינוקות' WHERE health_concerns = 'Thyroid iodine uptake inhibition – critical for neurodevelopment in infants';
UPDATE food_additives SET health_concerns_he = 'גידולי תריס בחולדות; FDA אסר לפי סעיף דילייני' WHERE health_concerns = 'Thyroid tumors in rats; FDA banned under Delaney Clause';
UPDATE food_additives SET health_concerns_he = 'תבלין מסורתי עם גוונים מתוקים; אפיון מוגבל' WHERE health_concerns = 'Traditional spice with sweet notes; limited characterization';
UPDATE food_additives SET health_concerns_he = 'שימוש מסורתי במשך מאות שנים; צורת פרי שלם (לא תמצית)' WHERE health_concerns = 'Traditional use for centuries; whole fruit form (not extract)';
UPDATE food_additives SET health_concerns_he = 'תכונות שינוי טעם ייחודיות; הופך חמוץ למתוק' WHERE health_concerns = 'Unique taste-modifying properties; makes sour taste sweet';
UPDATE food_additives SET health_concerns_he = 'ממס אוניברסלי, מרכיב בסיס ברוב המזונות המעובדים.' WHERE health_concerns = 'Universal solvent, base ingredient in most processed foods.';
UPDATE food_additives SET health_concerns_he = 'לא יציב; קשה לייצור מסחרי' WHERE health_concerns = 'Unstable; difficult to produce commercially';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי משתנה בהתאם לתכולת מלטיטול; השפעות משלשלות' WHERE health_concerns = 'Variable GI depending on maltitol content; laxative effects';
UPDATE food_additives SET health_concerns_he = 'הרכב משתנה; השפעות משלשלות דומות לפוליאולים אחרים' WHERE health_concerns = 'Variable composition; laxative effects similar to other polyols';
UPDATE food_additives SET health_concerns_he = 'עוצמת מתיקות נמוכה מאוד; רכיב משני' WHERE health_concerns = 'Very low sweetness intensity; minor component';
UPDATE food_additives SET health_concerns_he = 'מים מסוננים לטוהר. מרכיב בסיס נפוץ.' WHERE health_concerns = 'Water filtered for purity. Common base ingredient.';
UPDATE food_additives SET health_concerns_he = 'מים עם CO2 מומס. בסיס למשקאות קלים.' WHERE health_concerns = 'Water with dissolved CO2. Base for soft drinks.';
UPDATE food_additives SET health_concerns_he = 'בשר לבן. לא חלאל/כשר ללא הסמכה.' WHERE health_concerns = 'White meat. Not halal/kosher without certification.';
UPDATE food_additives SET health_concerns_he = 'ירק מזון שלם. נפוץ ברוב המטבחים.' WHERE health_concerns = 'Whole food vegetable. Common in most cuisines.';
UPDATE food_additives SET health_concerns_he = 'שיבוש בלוטת התריס; אנמיה המוליטית - תינוקות הכי פגיעים' WHERE health_concerns = 'Thyroid disruption; hemolytic anemia ג€" infants most vulnerable';
UPDATE food_additives SET health_concerns_he = 'עיכוב קליטת יוד בתריס - קריטי להתפתחות עצבית בתינוקות' WHERE health_concerns = 'Thyroid iodine uptake inhibition ג€" critical for neurodevelopment in infants';