UPDATE food_additives SET health_concerns_he = 'חשש מ-4-MEI ו-THI; רשימת Prop 65 קליפורניה' WHERE health_concerns = '4-MEI and THI concerns; California Prop 65';
UPDATE food_additives SET health_concerns_he = 'חשש מ-4-MEI בסוג III/IV' WHERE health_concerns = '4-MEI concerns for Class III/IV';
UPDATE food_additives SET health_concerns_he = 'ניטור 4-MEI; בטוח ברמות בירה רגילות' WHERE health_concerns = '4-MEI monitoring; safe at typical beer levels';
UPDATE food_additives SET health_concerns_he = 'חשש מ-4-מתילאימידזול (4-MEI); רשום ב-Prop 65 קליפורניה' WHERE health_concerns = '4-methylimidazole (4-MEI) concerns; California Prop 65 listed';
UPDATE food_additives SET health_concerns_he = 'חשש ממזהם 4-מתילאימידזול (4-MEI); חשד לחומר מסרטן' WHERE health_concerns = '4-methylimidazole (4-MEI) contaminant concerns; potential carcinogen';
UPDATE food_additives SET health_concerns_he = 'סיכון אלרגני אם מופק מסויה/ביצים' WHERE health_concerns = 'Allergen risk if soy/egg-derived';
UPDATE food_additives SET health_concerns_he = 'תגובות אלרגיות' WHERE health_concerns = 'Allergic reactions';
UPDATE food_additives SET health_concerns_he = 'תגובות אלרגיות באנשים רגישים' WHERE health_concerns = 'Allergic reactions in sensitive individuals';
UPDATE food_additives SET health_concerns_he = 'תגובות אלרגיות כולל אנפילקסיס' WHERE health_concerns = 'Allergic reactions including anaphylaxis';
UPDATE food_additives SET health_concerns_he = 'תגובות אלרגיות אפשריות' WHERE health_concerns = 'Allergic reactions possible';
UPDATE food_additives SET health_concerns_he = 'תגובות אלרגיות, חשש לשיבוש הורמונלי' WHERE health_concerns = 'Allergic reactions, hormone disruption concerns';
UPDATE food_additives SET health_concerns_he = 'תגובות אלרגיות, פחות בשימוש' WHERE health_concerns = 'Allergic reactions, less used';
UPDATE food_additives SET health_concerns_he = 'תגובות אלרגיות, מידע מוגבל' WHERE health_concerns = 'Allergic reactions, limited data';
UPDATE food_additives SET health_concerns_he = 'חשש מהצטברות אלומיניום' WHERE health_concerns = 'Aluminium accumulation concerns';
UPDATE food_additives SET health_concerns_he = 'הצטברות אלומיניום; רעילות עצבית שנויה במחלוקת' WHERE health_concerns = 'Aluminium accumulation; neurotoxicity debated';
UPDATE food_additives SET health_concerns_he = 'חששות אלומיניום' WHERE health_concerns = 'Aluminium concerns';
UPDATE food_additives SET health_concerns_he = 'חשש מחשיפה לאלומיניום' WHERE health_concerns = 'Aluminium exposure concern';
UPDATE food_additives SET health_concerns_he = 'שיקולי חשיפה לאלומיניום' WHERE health_concerns = 'Aluminium exposure consideration';
UPDATE food_additives SET health_concerns_he = 'חשש מחשיפה לאלומיניום' WHERE health_concerns = 'Aluminum exposure concerns';
UPDATE food_additives SET health_concerns_he = 'תכונות נוגדות חמצון; נסבל היטב בדרך כלל' WHERE health_concerns = 'Antioxidant properties; generally well tolerated';
UPDATE food_additives SET health_concerns_he = 'עלול לעורר אסטמה' WHERE health_concerns = 'Asthma triggers';
UPDATE food_additives SET health_concerns_he = 'עלול לעורר אסטמה באנשים רגישים' WHERE health_concerns = 'Asthma triggers in sensitive individuals';
UPDATE food_additives SET health_concerns_he = 'עלול לעורר אסטמה, תגובות אלרגיות' WHERE health_concerns = 'Asthma triggers, allergic reactions';
UPDATE food_additives SET health_concerns_he = 'עלול לעורר אסטמה, אורטיקריה באנשים רגישים' WHERE health_concerns = 'Asthma triggers, urticaria in sensitive individuals';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות; רעילות גנטית' WHERE health_concerns = 'Carcinogenicity; genotoxicity';
UPDATE food_additives SET health_concerns_he = 'חשש לשיבוש הורמונלי' WHERE health_concerns = 'Endocrine disruption concerns';
UPDATE food_additives SET health_concerns_he = 'חשש לשיבוש הורמונלי, תגובות אלרגיות' WHERE health_concerns = 'Endocrine disruption concerns, allergic reactions';
UPDATE food_additives SET health_concerns_he = 'שיבוש הורמונלי, חששות לפוריות' WHERE health_concerns = 'Endocrine disruption, reproductive concerns';
UPDATE food_additives SET health_concerns_he = 'מינרל חיוני, בטוח בדרך כלל' WHERE health_concerns = 'Essential mineral, generally safe';
UPDATE food_additives SET health_concerns_he = 'Fat-soluble vitamin C derivative, בטוח בדרך כלל' WHERE health_concerns = 'Fat-soluble vitamin C derivative, generally safe';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול' WHERE health_concerns = 'GI discomfort';
UPDATE food_additives SET health_concerns_he = 'מוכר כבטוח בדרך כלל (GRAS)' WHERE health_concerns = 'Generally recognized as safe';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל' WHERE health_concerns = 'Generally safe';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל (vitamin C derivative); benzene risk with sodium benzoate' WHERE health_concerns = 'Generally safe (vitamin C derivative); benzene risk with sodium benzoate';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל at approved levels' WHERE health_concerns = 'Generally safe at approved levels';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל ברמות נמוכות' WHERE health_concerns = 'Generally safe at low levels';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל at permitted levels' WHERE health_concerns = 'Generally safe at permitted levels';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל in normal amounts' WHERE health_concerns = 'Generally safe in normal amounts';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל בעיבוד' WHERE health_concerns = 'Generally safe in processing';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל topically, limited food use' WHERE health_concerns = 'Generally safe topically, limited food use';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, 4-MEI concerns debated' WHERE health_concerns = 'Generally safe, 4-MEI concerns debated';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ויטמין B' WHERE health_concerns = 'Generally safe, B vitamin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, B vitamin form' WHERE health_concerns = 'Generally safe, B vitamin form';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, EGCG' WHERE health_concerns = 'Generally safe, EGCG';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, GRAS, natural vinegar component' WHERE health_concerns = 'Generally safe, GRAS, natural vinegar component';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, L-DOPA' WHERE health_concerns = 'Generally safe, L-DOPA';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, PAH concerns if excessive' WHERE health_concerns = 'Generally safe, PAH concerns if excessive';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, PEITC' WHERE health_concerns = 'Generally safe, PEITC';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, S-allyl cysteine' WHERE health_concerns = 'Generally safe, S-allyl cysteine';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, acetic acid salt' WHERE health_concerns = 'Generally safe, acetic acid salt';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, allicin' WHERE health_concerns = 'Generally safe, allicin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצת אמינו' WHERE health_concerns = 'Generally safe, amino acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, נגזרת חומצת אמינו' WHERE health_concerns = 'Generally safe, amino acid derivative';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, amino sulfonic acid' WHERE health_concerns = 'Generally safe, amino sulfonic acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, anethole' WHERE health_concerns = 'Generally safe, anethole';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, annatto' WHERE health_concerns = 'Generally safe, annatto';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אנתוציאנידין' WHERE health_concerns = 'Generally safe, anthocyanidin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אנתוציאנינים' WHERE health_concerns = 'Generally safe, anthocyanins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, anthocyanosides' WHERE health_concerns = 'Generally safe, anthocyanosides';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, antimicrobial' WHERE health_concerns = 'Generally safe, antimicrobial';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, antimicrobial fatty acid' WHERE health_concerns = 'Generally safe, antimicrobial fatty acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, apigenin' WHERE health_concerns = 'Generally safe, apigenin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ascaridole' WHERE health_concerns = 'Generally safe, ascaridole';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, aspalathin' WHERE health_concerns = 'Generally safe, aspalathin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, avenanthramides' WHERE health_concerns = 'Generally safe, avenanthramides';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, bacteriocin' WHERE health_concerns = 'Generally safe, bacteriocin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, bacteriocin peptide' WHERE health_concerns = 'Generally safe, bacteriocin peptide';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, bee resin' WHERE health_concerns = 'Generally safe, bee resin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, bee secretion' WHERE health_concerns = 'Generally safe, bee secretion';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, behavioral effects reported (debated)' WHERE health_concerns = 'Generally safe, behavioral effects reported (debated)';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, בטא-קרוטן' WHERE health_concerns = 'Generally safe, beta-carotene';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, בטלאינים' WHERE health_concerns = 'Generally safe, betalains';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, betulin' WHERE health_concerns = 'Generally safe, betulin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, bromelain' WHERE health_concerns = 'Generally safe, bromelain';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, brown algae' WHERE health_concerns = 'Generally safe, brown algae';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, browning products' WHERE health_concerns = 'Generally safe, browning products';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, calcium source' WHERE health_concerns = 'Generally safe, calcium source';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קפסאיצין' WHERE health_concerns = 'Generally safe, capsaicin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קרוטנואיד' WHERE health_concerns = 'Generally safe, carotenoid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, carotenoids' WHERE health_concerns = 'Generally safe, carotenoids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, carvacrol' WHERE health_concerns = 'Generally safe, carvacrol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, carvone' WHERE health_concerns = 'Generally safe, carvone';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קטכין' WHERE health_concerns = 'Generally safe, catechin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, catechins' WHERE health_concerns = 'Generally safe, catechins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, cationic polypeptide' WHERE health_concerns = 'Generally safe, cationic polypeptide';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, cationic surfactant' WHERE health_concerns = 'Generally safe, cationic surfactant';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, caution with kidney disease' WHERE health_concerns = 'Generally safe, caution with kidney disease';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, chlorogenic acids' WHERE health_concerns = 'Generally safe, chlorogenic acids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, chlorophyll' WHERE health_concerns = 'Generally safe, chlorophyll';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, cinnamaldehyde' WHERE health_concerns = 'Generally safe, cinnamaldehyde';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, cinnamon component' WHERE health_concerns = 'Generally safe, cinnamon component';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, citrus flavonoid' WHERE health_concerns = 'Generally safe, citrus flavonoid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, citrus flavonoids' WHERE health_concerns = 'Generally safe, citrus flavonoids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, citrus oil component' WHERE health_concerns = 'Generally safe, citrus oil component';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, clove oil component' WHERE health_concerns = 'Generally safe, clove oil component';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, contains acetic acid' WHERE health_concerns = 'Generally safe, contains acetic acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מכיל אלכוהול' WHERE health_concerns = 'Generally safe, contains alcohol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, contains minerals' WHERE health_concerns = 'Generally safe, contains minerals';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, contains monacolins' WHERE health_concerns = 'Generally safe, contains monacolins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, contains trace minerals' WHERE health_concerns = 'Generally safe, contains trace minerals';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, cuminaldehyde' WHERE health_concerns = 'Generally safe, cuminaldehyde';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, curcuminoids' WHERE health_concerns = 'Generally safe, curcuminoids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, delphinidins' WHERE health_concerns = 'Generally safe, delphinidins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, dipeptide' WHERE health_concerns = 'Generally safe, dipeptide';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, diterpene' WHERE health_concerns = 'Generally safe, diterpene';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, dithiol compound' WHERE health_concerns = 'Generally safe, dithiol compound';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ellagic acid' WHERE health_concerns = 'Generally safe, ellagic acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ellagitannins' WHERE health_concerns = 'Generally safe, ellagitannins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אנזים' WHERE health_concerns = 'Generally safe, enzyme';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, enzyme from egg white' WHERE health_concerns = 'Generally safe, enzyme from egg white';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, estragole' WHERE health_concerns = 'Generally safe, estragole';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, eucalyptol' WHERE health_concerns = 'Generally safe, eucalyptol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אאוגנול' WHERE health_concerns = 'Generally safe, eugenol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, flavan-3-ol' WHERE health_concerns = 'Generally safe, flavan-3-ol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, flavanols' WHERE health_concerns = 'Generally safe, flavanols';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, flavanone glycoside' WHERE health_concerns = 'Generally safe, flavanone glycoside';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פלבונואיד' WHERE health_concerns = 'Generally safe, flavonoid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, flavonoid glycoside' WHERE health_concerns = 'Generally safe, flavonoid glycoside';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, flavonoid pigments' WHERE health_concerns = 'Generally safe, flavonoid pigments';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, flavonoids' WHERE health_concerns = 'Generally safe, flavonoids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, fruit fiber' WHERE health_concerns = 'Generally safe, fruit fiber';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, fungicide' WHERE health_concerns = 'Generally safe, fungicide';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, gingerols' WHERE health_concerns = 'Generally safe, gingerols';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ginsenosides' WHERE health_concerns = 'Generally safe, ginsenosides';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, גלוקוזינולטים' WHERE health_concerns = 'Generally safe, glucosinolates';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, glutamate source' WHERE health_concerns = 'Generally safe, glutamate source';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, glycyrrhizin' WHERE health_concerns = 'Generally safe, glycyrrhizin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, hesperidin' WHERE health_concerns = 'Generally safe, hesperidin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, high intake affects calcium' WHERE health_concerns = 'Generally safe, high intake affects calcium';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, high intake causes dental/metabolic issues' WHERE health_concerns = 'Generally safe, high intake causes dental/metabolic issues';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, high intake causes metabolic issues' WHERE health_concerns = 'Generally safe, high intake causes metabolic issues';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, high intake increases blood pressure' WHERE health_concerns = 'Generally safe, high intake increases blood pressure';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, נתרן גבוה' WHERE health_concerns = 'Generally safe, high sodium';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, high vitamin C' WHERE health_concerns = 'Generally safe, high vitamin C';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, highly refined' WHERE health_concerns = 'Generally safe, highly refined';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, hormone' WHERE health_concerns = 'Generally safe, hormone';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, hydrolyzable tannin' WHERE health_concerns = 'Generally safe, hydrolyzable tannin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, hydrolyzes to CO2 and methanol' WHERE health_concerns = 'Generally safe, hydrolyzes to CO2 and methanol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, hydroxytyrosol' WHERE health_concerns = 'Generally safe, hydroxytyrosol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, inert mineral' WHERE health_concerns = 'Generally safe, inert mineral';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, insect secretion' WHERE health_concerns = 'Generally safe, insect secretion';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, intoxicating' WHERE health_concerns = 'Generally safe, intoxicating';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, inulin' WHERE health_concerns = 'Generally safe, inulin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, isoflavones' WHERE health_concerns = 'Generally safe, isoflavones';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, איזותיוציאנטים' WHERE health_concerns = 'Generally safe, isothiocyanates';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, lactic acid bacteria' WHERE health_concerns = 'Generally safe, lactic acid bacteria';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, lactose content' WHERE health_concerns = 'Generally safe, lactose content';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, legume seed' WHERE health_concerns = 'Generally safe, legume seed';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, lignans' WHERE health_concerns = 'Generally safe, lignans';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, linalool' WHERE health_concerns = 'Generally safe, linalool';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, lipid antioxidant' WHERE health_concerns = 'Generally safe, lipid antioxidant';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, lutein' WHERE health_concerns = 'Generally safe, lutein';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, lycopene' WHERE health_concerns = 'Generally safe, lycopene';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, lysine' WHERE health_concerns = 'Generally safe, lysine';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, macamides' WHERE health_concerns = 'Generally safe, macamides';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, mangiferin' WHERE health_concerns = 'Generally safe, mangiferin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, marine carotenoid' WHERE health_concerns = 'Generally safe, marine carotenoid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, may bind minerals' WHERE health_concerns = 'Generally safe, may bind minerals';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, medium-chain fatty acid' WHERE health_concerns = 'Generally safe, medium-chain fatty acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, menthol' WHERE health_concerns = 'Generally safe, menthol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, methyl salicylate' WHERE health_concerns = 'Generally safe, methyl salicylate';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, methylglyoxal' WHERE health_concerns = 'Generally safe, methylglyoxal';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, migraine trigger in sensitive individuals' WHERE health_concerns = 'Generally safe, migraine trigger in sensitive individuals';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, milk protein' WHERE health_concerns = 'Generally safe, milk protein';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, mineral chelator (high doses deplete minerals)' WHERE health_concerns = 'Generally safe, mineral chelator (high doses deplete minerals)';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, mineral source' WHERE health_concerns = 'Generally safe, mineral source';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, mushroom sugar' WHERE health_concerns = 'Generally safe, mushroom sugar';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, myristicin' WHERE health_concerns = 'Generally safe, myristicin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, naringin' WHERE health_concerns = 'Generally safe, naringin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, nasunin' WHERE health_concerns = 'Generally safe, nasunin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, nattokinase' WHERE health_concerns = 'Generally safe, nattokinase';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, natural fermentation product' WHERE health_concerns = 'Generally safe, natural fermentation product';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, natural fruit acid' WHERE health_concerns = 'Generally safe, natural fruit acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, natural grape acid' WHERE health_concerns = 'Generally safe, natural grape acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, natural milk enzyme system' WHERE health_concerns = 'Generally safe, natural milk enzyme system';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, natural plant extract' WHERE health_concerns = 'Generally safe, natural plant extract';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, natural sweetener' WHERE health_concerns = 'Generally safe, natural sweetener';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, natural wood smoke' WHERE health_concerns = 'Generally safe, natural wood smoke';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, no THC' WHERE health_concerns = 'Generally safe, no THC';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, nucleoside' WHERE health_concerns = 'Generally safe, nucleoside';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, oligomeric flavonoids' WHERE health_concerns = 'Generally safe, oligomeric flavonoids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, omega-3' WHERE health_concerns = 'Generally safe, omega-3';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, omega-7' WHERE health_concerns = 'Generally safe, omega-7';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, oregano/thyme' WHERE health_concerns = 'Generally safe, oregano/thyme';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, organic acids' WHERE health_concerns = 'Generally safe, organic acids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, oryzanol' WHERE health_concerns = 'Generally safe, oryzanol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, palm wax' WHERE health_concerns = 'Generally safe, palm wax';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, papain' WHERE health_concerns = 'Generally safe, papain';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, peptide bacteriocin' WHERE health_concerns = 'Generally safe, peptide bacteriocin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, peptide fragment' WHERE health_concerns = 'Generally safe, peptide fragment';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצה פנולית' WHERE health_concerns = 'Generally safe, phenolic acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, phenolic compound' WHERE health_concerns = 'Generally safe, phenolic compound';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, phenolics' WHERE health_concerns = 'Generally safe, phenolics';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, phycocyanin' WHERE health_concerns = 'Generally safe, phycocyanin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, phytoestrogen' WHERE health_concerns = 'Generally safe, phytoestrogen';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, piperine' WHERE health_concerns = 'Generally safe, piperine';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, סטרול צמחי' WHERE health_concerns = 'Generally safe, plant sterol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, plant wax' WHERE health_concerns = 'Generally safe, plant wax';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, polymethoxyflavone' WHERE health_concerns = 'Generally safe, polymethoxyflavone';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פוליפנול' WHERE health_concerns = 'Generally safe, polyphenol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פוליפנולים' WHERE health_concerns = 'Generally safe, polyphenols';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, polysaccharide' WHERE health_concerns = 'Generally safe, polysaccharide';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פוליסכרידים' WHERE health_concerns = 'Generally safe, polysaccharides';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, prevents discoloration' WHERE health_concerns = 'Generally safe, prevents discoloration';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, proanthocyanidins' WHERE health_concerns = 'Generally safe, proanthocyanidins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, probiotic' WHERE health_concerns = 'Generally safe, probiotic';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, probiotic metabolites' WHERE health_concerns = 'Generally safe, probiotic metabolites';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, protein pigment' WHERE health_concerns = 'Generally safe, protein pigment';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, quercetin' WHERE health_concerns = 'Generally safe, quercetin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, resveratrol' WHERE health_concerns = 'Generally safe, resveratrol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, rosavins' WHERE health_concerns = 'Generally safe, rosavins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, rutin' WHERE health_concerns = 'Generally safe, rutin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, salicin' WHERE health_concerns = 'Generally safe, salicin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, saponins' WHERE health_concerns = 'Generally safe, saponins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, seaweed extract' WHERE health_concerns = 'Generally safe, seaweed extract';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, sesamol/sesamolin' WHERE health_concerns = 'Generally safe, sesamol/sesamolin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, shellfish derivative' WHERE health_concerns = 'Generally safe, shellfish derivative';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, silymarin' WHERE health_concerns = 'Generally safe, silymarin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, soy/egg source (allergen if sensitive)' WHERE health_concerns = 'Generally safe, soy/egg source (allergen if sensitive)';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, squalene' WHERE health_concerns = 'Generally safe, squalene';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, sulforaphane' WHERE health_concerns = 'Generally safe, sulforaphane';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, טאנינים' WHERE health_concerns = 'Generally safe, tannins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, terpenes' WHERE health_concerns = 'Generally safe, terpenes';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, theaflavins' WHERE health_concerns = 'Generally safe, theaflavins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, thymol' WHERE health_concerns = 'Generally safe, thymol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, tree exudate' WHERE health_concerns = 'Generally safe, tree exudate';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, trihydroxybenzoic acid' WHERE health_concerns = 'Generally safe, trihydroxybenzoic acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, tripeptide' WHERE health_concerns = 'Generally safe, tripeptide';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, triterpene' WHERE health_concerns = 'Generally safe, triterpene';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, valerenic acid' WHERE health_concerns = 'Generally safe, valerenic acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, vitamin A form' WHERE health_concerns = 'Generally safe, vitamin A form';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, vitamin C' WHERE health_concerns = 'Generally safe, vitamin C';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, vitamin C derivative' WHERE health_concerns = 'Generally safe, vitamin C derivative';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, vitamin E' WHERE health_concerns = 'Generally safe, vitamin E';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, withanolides' WHERE health_concerns = 'Generally safe, withanolides';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, zeaxanthin' WHERE health_concerns = 'Generally safe, zeaxanthin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; Mild nausea at high doses; Flushing is rare' WHERE health_concerns = 'Generally safe; Mild nausea at high doses; Flushing is rare';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; Possible increased prostate cancer risk debated (high-dose studies); GI distress' WHERE health_concerns = 'Generally safe; Possible increased prostate cancer risk debated (high-dose studies); GI distress';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; amino acid' WHERE health_concerns = 'Generally safe; amino acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; antacid use' WHERE health_concerns = 'Generally safe; antacid use';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; calcium source' WHERE health_concerns = 'Generally safe; calcium source';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; common buffering agent' WHERE health_concerns = 'Generally safe; common buffering agent';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; delisted for technical reasons' WHERE health_concerns = 'Generally safe; delisted for technical reasons';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; essential amino acid' WHERE health_concerns = 'Generally safe; essential amino acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; high doses may be nephrotoxic' WHERE health_concerns = 'Generally safe; high doses may be nephrotoxic';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; laxative at high doses' WHERE health_concerns = 'Generally safe; laxative at high doses';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; may cause skin allergies' WHERE health_concerns = 'Generally safe; may cause skin allergies';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; may reduce drug absorption' WHERE health_concerns = 'Generally safe; may reduce drug absorption';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; natural fruit acid' WHERE health_concerns = 'Generally safe; natural fruit acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; potassium source' WHERE health_concerns = 'Generally safe; potassium source';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; rare allergic reactions' WHERE health_concerns = 'Generally safe; rare allergic reactions';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; rare allergies; ethylene oxide contamination concern' WHERE health_concerns = 'Generally safe; rare allergies; ethylene oxide contamination concern';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; rare bloating; NEC concern in premature infants' WHERE health_concerns = 'Generally safe; rare bloating; NEC concern in premature infants';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; slow acidifier' WHERE health_concerns = 'Generally safe; slow acidifier';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; sulfite-sensitive individuals should be cautious' WHERE health_concerns = 'Generally safe; sulfite-sensitive individuals should be cautious';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; toxicity at very high doses' WHERE health_concerns = 'Generally safe; toxicity at very high doses';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; used to treat kidney stones' WHERE health_concerns = 'Generally safe; used to treat kidney stones';
UPDATE food_additives SET health_concerns_he = 'נסבל היטב בדרך כלל' WHERE health_concerns = 'Generally well-tolerated';
UPDATE food_additives SET health_concerns_he = 'חששות לגבי מיקרוביום המעי' WHERE health_concerns = 'Gut microbiome concerns';
UPDATE food_additives SET health_concerns_he = 'חששות לגבי מיקרוביום המעי במחקרי בעלי חיים' WHERE health_concerns = 'Gut microbiome concerns in animal studies';
UPDATE food_additives SET health_concerns_he = 'חששות לגבי מיקרוביום המעי במחקרים' WHERE health_concerns = 'Gut microbiome concerns in studies';
UPDATE food_additives SET health_concerns_he = 'שיבוש מיקרוביום המעי במחקרי בעלי חיים' WHERE health_concerns = 'Gut microbiome disruption in animal studies';
UPDATE food_additives SET health_concerns_he = 'חשש מצריכת פוספט גבוהה' WHERE health_concerns = 'High phosphate intake concern';
UPDATE food_additives SET health_concerns_he = 'נתונים לא מספיקים' WHERE health_concerns = 'Insufficient data';
UPDATE food_additives SET health_concerns_he = 'נתוני בטיחות לא מספיקים' WHERE health_concerns = 'Insufficient safety data';
UPDATE food_additives SET health_concerns_he = 'השפעה משלשלת במינונים גבוהים' WHERE health_concerns = 'Laxative effect at high doses';
UPDATE food_additives SET health_concerns_he = 'מקור חלבון דל שומן' WHERE health_concerns = 'Lean protein source';
UPDATE food_additives SET health_concerns_he = 'מידע מוגבל' WHERE health_concerns = 'Limited data';
UPDATE food_additives SET health_concerns_he = 'נתוני בטיחות מוגבלים' WHERE health_concerns = 'Limited safety data';
UPDATE food_additives SET health_concerns_he = 'חדש; נחשב בטוח' WHERE health_concerns = 'New; considered safe';
UPDATE food_additives SET health_concerns_he = 'ללא חששות' WHERE health_concerns = 'No concerns';
UPDATE food_additives SET health_concerns_he = 'ללא חשש בטיחותי' WHERE health_concerns = 'No safety concern';
UPDATE food_additives SET health_concerns_he = 'ללא חשש בטיחותי (EFSA 2017)' WHERE health_concerns = 'No safety concern (EFSA 2017)';
UPDATE food_additives SET health_concerns_he = 'ללא חשש בטיחותי (EFSA 2017); aluminium exposure consideration' WHERE health_concerns = 'No safety concern (EFSA 2017); aluminium exposure consideration';
UPDATE food_additives SET health_concerns_he = 'ללא חשש בטיחותי (EFSA 2017); אפשרות ל-GMO' WHERE health_concerns = 'No safety concern (EFSA 2017); potential GMO';
UPDATE food_additives SET health_concerns_he = 'ללא חשש בטיחותי (EFSA 2017); potential GMO source' WHERE health_concerns = 'No safety concern (EFSA 2017); potential GMO source';
UPDATE food_additives SET health_concerns_he = 'ללא חשש בטיחותי; אפשרות ל-GMO' WHERE health_concerns = 'No safety concern; potential GMO';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים' WHERE health_concerns = 'No significant concerns';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים בצריכה יומית מותרת' WHERE health_concerns = 'No significant concerns at ADI';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים at approved levels' WHERE health_concerns = 'No significant concerns at approved levels';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים at current use levels' WHERE health_concerns = 'No significant concerns at current use levels';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים at food-grade levels' WHERE health_concerns = 'No significant concerns at food-grade levels';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים; BSE risk mitigated' WHERE health_concerns = 'No significant concerns; BSE risk mitigated';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים; allergen potential' WHERE health_concerns = 'No significant concerns; allergen potential';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים; alternative to lecithin' WHERE health_concerns = 'No significant concerns; alternative to lecithin';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים; bloating at excess' WHERE health_concerns = 'No significant concerns; bloating at excess';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים; indigestible fiber' WHERE health_concerns = 'No significant concerns; indigestible fiber';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים; key ingredient in plant meats' WHERE health_concerns = 'No significant concerns; key ingredient in plant meats';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים; פרה-ביוטי' WHERE health_concerns = 'No significant concerns; prebiotic';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים; prebiotic effects' WHERE health_concerns = 'No significant concerns; prebiotic effects';
UPDATE food_additives SET health_concerns_he = 'ללא חששות משמעותיים; prebiotic properties reported' WHERE health_concerns = 'No significant concerns; prebiotic properties reported';
UPDATE food_additives SET health_concerns_he = 'לא מאושר למזון' WHERE health_concerns = 'Not approved for food';
UPDATE food_additives SET health_concerns_he = 'לא למזון' WHERE health_concerns = 'Not for food';
UPDATE food_additives SET health_concerns_he = 'תכולת פורין; סיכון לגאוט' WHERE health_concerns = 'Purine content; gout risk';
UPDATE food_additives SET health_concerns_he = 'תגובות אלרגיות נדירות' WHERE health_concerns = 'Rare allergic reactions';
UPDATE food_additives SET health_concerns_he = 'בטוח' WHERE health_concerns = 'Safe';
UPDATE food_additives SET health_concerns_he = 'בטוח כתוסף מזון לבעלי חיים' WHERE health_concerns = 'Safe as feed additive';
UPDATE food_additives SET health_concerns_he = 'בטוח בצריכה יומית מותרת' WHERE health_concerns = 'Safe at ADI';
UPDATE food_additives SET health_concerns_he = 'בטוח ברמות מזון רגילות' WHERE health_concerns = 'Safe at food levels';
UPDATE food_additives SET health_concerns_he = 'בטוח בשימוש מסורתי' WHERE health_concerns = 'Safe in traditional use';
UPDATE food_additives SET health_concerns_he = 'בטוח. אלרגן: חלב.' WHERE health_concerns = 'Safe. Allergen: milk.';
UPDATE food_additives SET health_concerns_he = 'בטוח; נוגד חמצון' WHERE health_concerns = 'Safe; antioxidant';
UPDATE food_additives SET health_concerns_he = 'בטוח; שימוש מסורתי' WHERE health_concerns = 'Safe; traditional use';
UPDATE food_additives SET health_concerns_he = 'חששות פוספט מאותה קבוצה' WHERE health_concerns = 'Same group phosphate concerns';
UPDATE food_additives SET health_concerns_he = 'ראה סידן' WHERE health_concerns = 'See Calcium';
UPDATE food_additives SET health_concerns_he = 'ראה נחושת' WHERE health_concerns = 'See Copper';
UPDATE food_additives SET health_concerns_he = 'ראה Copper; GI irritation at high doses' WHERE health_concerns = 'See Copper; GI irritation at high doses';
UPDATE food_additives SET health_concerns_he = 'ראה E100' WHERE health_concerns = 'See E100';
UPDATE food_additives SET health_concerns_he = 'ראה E101' WHERE health_concerns = 'See E101';
UPDATE food_additives SET health_concerns_he = 'ראה E102' WHERE health_concerns = 'See E102';
UPDATE food_additives SET health_concerns_he = 'ראה E104' WHERE health_concerns = 'See E104';
UPDATE food_additives SET health_concerns_he = 'ראה E110' WHERE health_concerns = 'See E110';
UPDATE food_additives SET health_concerns_he = 'ראה E120' WHERE health_concerns = 'See E120';
UPDATE food_additives SET health_concerns_he = 'ראה E120; allergen concern' WHERE health_concerns = 'See E120; allergen concern';
UPDATE food_additives SET health_concerns_he = 'ראה E122' WHERE health_concerns = 'See E122';
UPDATE food_additives SET health_concerns_he = 'ראה E123' WHERE health_concerns = 'See E123';
UPDATE food_additives SET health_concerns_he = 'ראה E124' WHERE health_concerns = 'See E124';
UPDATE food_additives SET health_concerns_he = 'ראה E127' WHERE health_concerns = 'See E127';
UPDATE food_additives SET health_concerns_he = 'ראה E129' WHERE health_concerns = 'See E129';
UPDATE food_additives SET health_concerns_he = 'ראה E131' WHERE health_concerns = 'See E131';
UPDATE food_additives SET health_concerns_he = 'ראה E132' WHERE health_concerns = 'See E132';
UPDATE food_additives SET health_concerns_he = 'ראה E133' WHERE health_concerns = 'See E133';
UPDATE food_additives SET health_concerns_he = 'ראה E142' WHERE health_concerns = 'See E142';
UPDATE food_additives SET health_concerns_he = 'ראה E143' WHERE health_concerns = 'See E143';
UPDATE food_additives SET health_concerns_he = 'ראה E151' WHERE health_concerns = 'See E151';
UPDATE food_additives SET health_concerns_he = 'ראה E155' WHERE health_concerns = 'See E155';
UPDATE food_additives SET health_concerns_he = 'ראה E160c' WHERE health_concerns = 'See E160c';
UPDATE food_additives SET health_concerns_he = 'ראה E160d' WHERE health_concerns = 'See E160d';
UPDATE food_additives SET health_concerns_he = 'ראה E161g' WHERE health_concerns = 'See E161g';
UPDATE food_additives SET health_concerns_he = 'ראה E164' WHERE health_concerns = 'See E164';
UPDATE food_additives SET health_concerns_he = 'ראה E171; genotoxicity concerns' WHERE health_concerns = 'See E171; genotoxicity concerns';
UPDATE food_additives SET health_concerns_he = 'ראה יוד' WHERE health_concerns = 'See Iodine';
UPDATE food_additives SET health_concerns_he = 'ראה Iron; GI distress common (constipation, nausea, black stools)' WHERE health_concerns = 'See Iron; GI distress common (constipation, nausea, black stools)';
UPDATE food_additives SET health_concerns_he = 'ראה Iron; GI side effects less than ferrous sulfate' WHERE health_concerns = 'See Iron; GI side effects less than ferrous sulfate';
UPDATE food_additives SET health_concerns_he = 'ראה Iron; Generally better tolerated' WHERE health_concerns = 'See Iron; Generally better tolerated';
UPDATE food_additives SET health_concerns_he = 'ראה Iron; Minimal GI effects' WHERE health_concerns = 'See Iron; Minimal GI effects';
UPDATE food_additives SET health_concerns_he = 'ראה Iron; Similar GI effects to ferrous sulfate' WHERE health_concerns = 'See Iron; Similar GI effects to ferrous sulfate';
UPDATE food_additives SET health_concerns_he = 'ראה מגנזיום' WHERE health_concerns = 'See Magnesium';
UPDATE food_additives SET health_concerns_he = 'ראה Magnesium; Common laxative effect' WHERE health_concerns = 'See Magnesium; Common laxative effect';
UPDATE food_additives SET health_concerns_he = 'ראה Magnesium; Laxative effect at higher doses' WHERE health_concerns = 'See Magnesium; Laxative effect at higher doses';
UPDATE food_additives SET health_concerns_he = 'ראה Magnesium; Less likely to cause diarrhea' WHERE health_concerns = 'See Magnesium; Less likely to cause diarrhea';
UPDATE food_additives SET health_concerns_he = 'ראה Omega-3 EPA; Fishy odor; GI upset; Prolonged bleeding' WHERE health_concerns = 'See Omega-3 EPA; Fishy odor; GI upset; Prolonged bleeding';
UPDATE food_additives SET health_concerns_he = 'ראה סלניום' WHERE health_concerns = 'See Selenium';
UPDATE food_additives SET health_concerns_he = 'ראה Selenium; Longer tissue retention than inorganic forms' WHERE health_concerns = 'See Selenium; Longer tissue retention than inorganic forms';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין A' WHERE health_concerns = 'See Vitamin A';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין B1' WHERE health_concerns = 'See Vitamin B1';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין B12' WHERE health_concerns = 'See Vitamin B12';
UPDATE food_additives SET health_concerns_he = 'ראה Vitamin B2' WHERE health_concerns = 'See Vitamin B2';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין B5' WHERE health_concerns = 'See Vitamin B5';
UPDATE food_additives SET health_concerns_he = 'ראה Vitamin B5; Occasional GI effects' WHERE health_concerns = 'See Vitamin B5; Occasional GI effects';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין B6' WHERE health_concerns = 'See Vitamin B6';
UPDATE food_additives SET health_concerns_he = 'ראה Vitamin B6; Neuropathy at chronic high doses' WHERE health_concerns = 'See Vitamin B6; Neuropathy at chronic high doses';
UPDATE food_additives SET health_concerns_he = 'ראה Vitamin C' WHERE health_concerns = 'See Vitamin C';
UPDATE food_additives SET health_concerns_he = 'ראה Vitamin C and Zinc' WHERE health_concerns = 'See Vitamin C and Zinc';
UPDATE food_additives SET health_concerns_he = 'ראה Vitamin C; Account for magnesium content' WHERE health_concerns = 'See Vitamin C; Account for magnesium content';
UPDATE food_additives SET health_concerns_he = 'ראה Vitamin C; Also provides calcium (~10% by weight)' WHERE health_concerns = 'See Vitamin C; Also provides calcium (~10% by weight)';
UPDATE food_additives SET health_concerns_he = 'ראה Vitamin C; Also provides potassium' WHERE health_concerns = 'See Vitamin C; Also provides potassium';
UPDATE food_additives SET health_concerns_he = 'ראה Vitamin C; Sodium contribution at high doses' WHERE health_concerns = 'See Vitamin C; Sodium contribution at high doses';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין D' WHERE health_concerns = 'See Vitamin D';
UPDATE food_additives SET health_concerns_he = 'ראה Vitamin D (higher potency means narrower safety margin)' WHERE health_concerns = 'See Vitamin D (higher potency means narrower safety margin)';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין E' WHERE health_concerns = 'See Vitamin E';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין K' WHERE health_concerns = 'See Vitamin K';
UPDATE food_additives SET health_concerns_he = 'ראה אבץ' WHERE health_concerns = 'See Zinc';
UPDATE food_additives SET health_concerns_he = 'ראה Zinc; GI upset at higher doses' WHERE health_concerns = 'See Zinc; GI upset at higher doses';
UPDATE food_additives SET health_concerns_he = 'ראה individual components' WHERE health_concerns = 'See individual components';
UPDATE food_additives SET health_concerns_he = 'חששות דומים לפוליסורבטים אחרים' WHERE health_concerns = 'Similar concerns as other polysorbates';
UPDATE food_additives SET health_concerns_he = 'מגרה עור, חשד לחומר מסרטן' WHERE health_concerns = 'Skin irritant, potential carcinogen';
UPDATE food_additives SET health_concerns_he = 'Vitamin A precursor, בטוח בדרך כלל' WHERE health_concerns = 'Vitamin A precursor, generally safe';
UPDATE food_additives SET health_concerns_he = 'מלח ויטמין C, בטוח בדרך כלל' WHERE health_concerns = 'Vitamin C salt, generally safe';
UPDATE food_additives SET health_concerns_he = 'Vitamin C stereoisomer, בטוח בדרך כלל' WHERE health_concerns = 'Vitamin C stereoisomer, generally safe';
UPDATE food_additives SET health_concerns_he = 'צורת ויטמין E, בטוח בדרך כלל' WHERE health_concerns = 'Vitamin E form, generally safe';
UPDATE food_additives SET health_concerns_he = 'ויטמין E, בטוח בדרך כלל' WHERE health_concerns = 'Vitamin E, generally safe';