UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, בקטריוצין פפטידי' WHERE health_concerns = 'Generally safe, peptide bacteriocin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קוטל פטריות' WHERE health_concerns = 'Generally safe, fungicide';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, GRAS, מרכיב טבעי של חומץ' WHERE health_concerns = 'Generally safe, GRAS, natural vinegar component';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, תוצר תסיסה טבעי' WHERE health_concerns = 'Generally safe, natural fermentation product';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, עלול לעורר מיגרנה באנשים רגישים' WHERE health_concerns = 'Generally safe, migraine trigger in sensitive individuals';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, דווח על השפעות התנהגותיות (שנוי במחלוקת)' WHERE health_concerns = 'Generally safe, behavioral effects reported (debated)';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מתפרק ל-CO2 ומתנול' WHERE health_concerns = 'Generally safe, hydrolyzes to CO2 and methanol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פעיל שטח קטיוני' WHERE health_concerns = 'Generally safe, cationic surfactant';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מקור סויה/ביצה (אלרגן אם רגיש)' WHERE health_concerns = 'Generally safe, soy/egg source (allergen if sensitive)';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצת פרי טבעית' WHERE health_concerns = 'Generally safe, natural fruit acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצת ענבים טבעית' WHERE health_concerns = 'Generally safe, natural grape acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, צריכה גבוהה משפיעה על סידן' WHERE health_concerns = 'Generally safe, high intake affects calcium';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מקור סידן' WHERE health_concerns = 'Generally safe, calcium source';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קלטור מינרלים (מינונים גבוהים מדלדלים מינרלים)' WHERE health_concerns = 'Generally safe, mineral chelator (high doses deplete minerals)';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, תמצית צמחית טבעית' WHERE health_concerns = 'Generally safe, natural plant extract';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מונע שינוי צבע' WHERE health_concerns = 'Generally safe, prevents discoloration';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל בכמויות רגילות' WHERE health_concerns = 'Generally safe in normal amounts';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חששות 4-MEI שנויים במחלוקת' WHERE health_concerns = 'Generally safe, 4-MEI concerns debated';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, עלול לקשור מינרלים' WHERE health_concerns = 'Generally safe, may bind minerals';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, צריכה גבוהה מעלה לחץ דם' WHERE health_concerns = 'Generally safe, high intake increases blood pressure';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, זהירות עם מחלת כליות' WHERE health_concerns = 'Generally safe, caution with kidney disease';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, צריכה גבוהה גורמת לבעיות שיניים/מטבוליות' WHERE health_concerns = 'Generally safe, high intake causes dental/metabolic issues';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, צריכה גבוהה גורמת לבעיות מטבוליות' WHERE health_concerns = 'Generally safe, high intake causes metabolic issues';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חששות PAH אם מופרז' WHERE health_concerns = 'Generally safe, PAH concerns if excessive';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ויתנוליידים' WHERE health_concerns = 'Generally safe, withanolides';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, עשיר בוויטמין C' WHERE health_concerns = 'Generally safe, high vitamin C';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ויטמין C' WHERE health_concerns = 'Generally safe, vitamin C';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, צורת ויטמין A' WHERE health_concerns = 'Generally safe, vitamin A form';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, רסברטרול' WHERE health_concerns = 'Generally safe, resveratrol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קוורצטין' WHERE health_concerns = 'Generally safe, quercetin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מטבוליטים פרוביוטיים' WHERE health_concerns = 'Generally safe, probiotic metabolites';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פרואנתוציאנידינים' WHERE health_concerns = 'Generally safe, proanthocyanidins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פולימתוקסיפלבון' WHERE health_concerns = 'Generally safe, polymethoxyflavone';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פיטואסטרוגן' WHERE health_concerns = 'Generally safe, phytoestrogen';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, תרכובת פנולית' WHERE health_concerns = 'Generally safe, phenolic compound';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצת שומן בינונית שרשרת' WHERE health_concerns = 'Generally safe, medium-chain fatty acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, לינלול' WHERE health_concerns = 'Generally safe, linalool';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ליגנאנים' WHERE health_concerns = 'Generally safe, lignans';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, איזופלבונים' WHERE health_concerns = 'Generally safe, isoflavones';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פלבנואידים' WHERE health_concerns = 'Generally safe, flavonoids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, גליקוזיד פלבנון' WHERE health_concerns = 'Generally safe, flavanone glycoside';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, דיטרפן' WHERE health_concerns = 'Generally safe, diterpene';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, דיפפטיד' WHERE health_concerns = 'Generally safe, dipeptide';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, בקטריוצין' WHERE health_concerns = 'Generally safe, bacteriocin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אפיגנין' WHERE health_concerns = 'Generally safe, apigenin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אנתול' WHERE health_concerns = 'Generally safe, anethole';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל ברמות מותרות' WHERE health_concerns = 'Generally safe at permitted levels';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; תגובות אלרגיות נדירות' WHERE health_concerns = 'Generally safe; rare allergic reactions';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; משלשל במינונים גבוהים' WHERE health_concerns = 'Generally safe; laxative at high doses';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; מקור סידן' WHERE health_concerns = 'Generally safe; calcium source';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, תרכובת טרפן' WHERE health_concerns = 'Generally safe, terpene compound';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, סינפרין' WHERE health_concerns = 'Generally safe, synephrine';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, סקוויטרפן' WHERE health_concerns = 'Generally safe, sesquiterpene';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ספונינים' WHERE health_concerns = 'Generally safe, saponins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, זהירות מפירוליזידין' WHERE health_concerns = 'Generally safe, pyrrolizidine caution';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פוליפנול' WHERE health_concerns = 'Generally safe, polyphenol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, נרינגנין' WHERE health_concerns = 'Generally safe, naringenin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, עלול לפעול עם תרופות' WHERE health_concerns = 'Generally safe, may interact with medications';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, לוטאולין' WHERE health_concerns = 'Generally safe, luteolin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קמפפרול' WHERE health_concerns = 'Generally safe, kaempferol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצה הידרוקסיקינמית' WHERE health_concerns = 'Generally safe, hydroxycinnamic acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, הידרוקסיבנזאלדהיד' WHERE health_concerns = 'Generally safe, hydroxybenzaldehyde';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ג''ינגרולים' WHERE health_concerns = 'Generally safe, gingerols';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אוגנול' WHERE health_concerns = 'Generally safe, eugenol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצה אלגית' WHERE health_concerns = 'Generally safe, ellagic acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, כורכומינואיד' WHERE health_concerns = 'Generally safe, curcuminoid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חלים מגבלות קומרין' WHERE health_concerns = 'Generally safe, coumarin limits apply';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קטכינים' WHERE health_concerns = 'Generally safe, catechins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצה קפאוילקינית' WHERE health_concerns = 'Generally safe, caffeoylquinic acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, בטא-גלוקן' WHERE health_concerns = 'Generally safe, beta-glucan';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אנתוציאנין' WHERE health_concerns = 'Generally safe, anthocyanin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אלדהיד' WHERE health_concerns = 'Generally safe, aldehyde';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אלקלואיד' WHERE health_concerns = 'Generally safe, alkaloid';
UPDATE food_additives SET health_concerns_he = 'ויטמין C, בטוח, מינונים גבוהים מאוד עלולים לגרום להפרעה במערכת העיכול' WHERE health_concerns = 'Vitamin C, safe, very high doses may cause GI upset';
UPDATE food_additives SET health_concerns_he = 'ויטמין E, בטוח, מינונים גבוהים עלולים להשפיע על קרישת הדם' WHERE health_concerns = 'Vitamin E, safe, high doses may affect blood clotting';
UPDATE food_additives SET health_concerns_he = 'סטריאואיזומר של ויטמין C, בטוח בדרך כלל' WHERE health_concerns = 'Vitamin C stereoisomer, generally safe';
UPDATE food_additives SET health_concerns_he = 'מבשר של ויטמין A, בטוח בדרך כלל' WHERE health_concerns = 'Vitamin A precursor, generally safe';
UPDATE food_additives SET health_concerns_he = 'נגזרת מסיסת שומן של ויטמין C, בטוח בדרך כלל' WHERE health_concerns = 'Fat-soluble vitamin C derivative, generally safe';
UPDATE food_additives SET health_concerns_he = 'הפרעות ראייה במינונים גבוהים, חששות לנזק ל-DNA (שנוי במחלוקת)' WHERE health_concerns = 'Vision disturbances high doses, DNA damage concerns (debated)';
UPDATE food_additives SET health_concerns_he = 'אפשרי מסרטן (מחקרים סותרים), שיבוש אנדוקריני' WHERE health_concerns = 'Possible carcinogen (conflicting studies), endocrine disruption';
UPDATE food_additives SET health_concerns_he = 'חשוד כמסרטן' WHERE health_concerns = 'Suspected carcinogen';
UPDATE food_additives SET health_concerns_he = 'רעילות אפשרית' WHERE health_concerns = 'Potential toxicity';
UPDATE food_additives SET health_concerns_he = 'רעילות רבייה, אסור במדינות רבות' WHERE health_concerns = 'Reproductive toxicity, banned many countries';
UPDATE food_additives SET health_concerns_he = 'חששות לשיבוש הורמונלי, חששות להיפראקטיביות' WHERE health_concerns = 'Hormone disruption concerns, hyperactivity concerns';
UPDATE food_additives SET health_concerns_he = 'בטוח; מכיל קפאין' WHERE health_concerns = 'Safe; contains caffeine';
UPDATE food_additives SET health_concerns_he = 'בטוח. צבע מזון טבעי.' WHERE health_concerns = 'Safe. Natural food coloring.';
UPDATE food_additives SET health_concerns_he = 'בטוח. אלרגן: חרדל.' WHERE health_concerns = 'Safe. Allergen: mustard.';
UPDATE food_additives SET health_concerns_he = 'בטוח. אלרגן: אגוזי עץ.' WHERE health_concerns = 'Safe. Allergen: tree nuts.';
UPDATE food_additives SET health_concerns_he = 'בטוח. אלרגן: סויה.' WHERE health_concerns = 'Safe. Allergen: soy.';
UPDATE food_additives SET health_concerns_he = 'בטוח. אלרגן: שומשום.' WHERE health_concerns = 'Safe. Allergen: sesame.';
UPDATE food_additives SET health_concerns_he = 'בטוח. אלרגן: עלול להכיל גלוטן.' WHERE health_concerns = 'Safe. Allergen: may contain gluten.';
UPDATE food_additives SET health_concerns_he = 'בטוח. אלרגן: גלוטן.' WHERE health_concerns = 'Safe. Allergen: gluten.';
UPDATE food_additives SET health_concerns_he = 'בטוח. אלרגן: ביצים.' WHERE health_concerns = 'Safe. Allergen: eggs.';
UPDATE food_additives SET health_concerns_he = 'בטוח. עלול להכיל אלרגן: גלוטן.' WHERE health_concerns = 'Safe. May contain allergen: gluten.';
UPDATE food_additives SET health_concerns_he = 'בטוח לרוב האנשים. אלרגן: גלוטן.' WHERE health_concerns = 'Safe for most people. Allergen: gluten.';
UPDATE food_additives SET health_concerns_he = 'בטוח במזון; תוספים מדאיגים למעשנים' WHERE health_concerns = 'Safe in food; supplements concerning for smokers';
UPDATE food_additives SET health_concerns_he = 'בטוח בכמויות מזון; מכיל שאריות אלכוהול' WHERE health_concerns = 'Safe in food amounts; contains alcohol residue';
UPDATE food_additives SET health_concerns_he = 'בטוח; נגזרת ויטמין' WHERE health_concerns = 'Safe; vitamin derivative';
UPDATE food_additives SET health_concerns_he = 'בטוח; צבע טבעי טרנדי' WHERE health_concerns = 'Safe; trendy natural color';
UPDATE food_additives SET health_concerns_he = 'בטוח; צבע סגול טבעי טרנדי' WHERE health_concerns = 'Safe; trending natural purple color';
UPDATE food_additives SET health_concerns_he = 'בטוח; חששות קיימות (סביבתיים)' WHERE health_concerns = 'Safe; sustainability concerns (environmental)';
UPDATE food_additives SET health_concerns_he = 'בטוח; עשיר בוויטמין C' WHERE health_concerns = 'Safe; rich in vitamin C';
UPDATE food_additives SET health_concerns_he = 'בטוח; תגובות אלרגיות נדירות' WHERE health_concerns = 'Safe; rare allergic reactions';
UPDATE food_additives SET health_concerns_he = 'בטוח; זנים חריפים עלולים לגרות את מערכת העיכול' WHERE health_concerns = 'Safe; pungent varieties may cause GI irritation';
UPDATE food_additives SET health_concerns_he = 'בטוח; נוגד חמצון עוצמתי' WHERE health_concerns = 'Safe; powerful antioxidant';
UPDATE food_additives SET health_concerns_he = 'בטוח; פיגמנט טבעי' WHERE health_concerns = 'Safe; natural pigment';
UPDATE food_additives SET health_concerns_he = 'בטוח; מחוון pH טבעי' WHERE health_concerns = 'Safe; natural pH indicator';
UPDATE food_additives SET health_concerns_he = 'בטוח; מקור קרוטן טבעי' WHERE health_concerns = 'Safe; natural carotene source';
UPDATE food_additives SET health_concerns_he = 'בטוח; תוצר מאייר טבעי' WHERE health_concerns = 'Safe; natural Maillard product';
UPDATE food_additives SET health_concerns_he = 'בטוח; תוסף מינרלי' WHERE health_concerns = 'Safe; mineral supplement';
UPDATE food_additives SET health_concerns_he = 'בטוח; נוגד חמצון גבוה' WHERE health_concerns = 'Safe; high antioxidant';
UPDATE food_additives SET health_concerns_he = 'בטוח; ויטמין חיוני' WHERE health_concerns = 'Safe; essential vitamin';
UPDATE food_additives SET health_concerns_he = 'בטוח; מכיל תיאוברומין/קפאין' WHERE health_concerns = 'Safe; contains theobromine/caffeine';
UPDATE food_additives SET health_concerns_he = 'בטוח; נוגד חמצון; יתרונות לדרכי השתן' WHERE health_concerns = 'Safe; antioxidant; urinary benefits';
UPDATE food_additives SET health_concerns_he = 'בטוח; פלבנואיד נוגד חמצון' WHERE health_concerns = 'Safe; antioxidant flavonoid';
UPDATE food_additives SET health_concerns_he = 'בטוח; יתרונות נוגד חמצון' WHERE health_concerns = 'Safe; antioxidant benefits';
UPDATE food_additives SET health_concerns_he = 'בטוח; תכונות אנטי-דלקתיות' WHERE health_concerns = 'Safe; anti-inflammatory properties';
UPDATE food_additives SET health_concerns_he = 'אין חששות משמעותיים ברמות מאושרות' WHERE health_concerns = 'No significant concerns at approved levels';
UPDATE food_additives SET health_concerns_he = 'נתונים מוגבלים; לא דווח על חששות משמעותיים' WHERE health_concerns = 'Limited data; no significant concerns reported';
UPDATE food_additives SET health_concerns_he = 'רעילות כלייתית; השפעות על עצמות' WHERE health_concerns = 'Nephrotoxicity; bone effects';
UPDATE food_additives SET health_concerns_he = 'תמצית טעם טבעית; בטוח בדרך כלל' WHERE health_concerns = 'Natural flavoring; generally safe';
UPDATE food_additives SET health_concerns_he = 'משלשל במינונים גבוהים' WHERE health_concerns = 'Laxative at high doses';
UPDATE food_additives SET health_concerns_he = 'רעילות חיסונית; רעילות כבדית; השפעות התפתחותיות' WHERE health_concerns = 'Immunotoxicity; hepatotoxicity; developmental effects';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית (תוספת לרעילות פוראן)' WHERE health_concerns = 'Hepatotoxicity (additive to furan toxicity)';
UPDATE food_additives SET health_concerns_he = 'ויכוח על דלקת במערכת העיכול' WHERE health_concerns = 'GI inflammation debate';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול אם היפרטוני' WHERE health_concerns = 'GI discomfort if hypertonic';
UPDATE food_additives SET health_concerns_he = 'חדש; בטיחות בהערכה' WHERE health_concerns = 'Emerging; safety under evaluation';
UPDATE food_additives SET health_concerns_he = 'מחקר סאות''המפטון היפראקטיביות; יוצר בנזן עם ויטמין C' WHERE health_concerns = 'Southampton study hyperactivity; forms benzene with vitamin C';
UPDATE food_additives SET health_concerns_he = 'שישיית סאות''המפטון היפראקטיביות; דלקת ריאות בתיווך חיסוני' WHERE health_concerns = 'Southampton Six hyperactivity; immune-mediated lung inflammation';
UPDATE food_additives SET health_concerns_he = 'שישיית סאות''המפטון היפראקטיביות; אסור בארה"ב, יפן, שוודיה, נורבגיה' WHERE health_concerns = 'Southampton Six hyperactivity; banned in US, Japan, Sweden, Norway';
UPDATE food_additives SET health_concerns_he = 'שישיית סאות''המפטון קשר להיפראקטיביות; אסור בארה"ב, יפן, אוסטרליה, נורבגיה' WHERE health_concerns = 'Southampton Six hyperactivity link; banned in US, Japan, Australia, Norway';
UPDATE food_additives SET health_concerns_he = 'הממתיק המאושר החזק ביותר; יציב בחום; נדרשות כמויות נמוכות מאוד' WHERE health_concerns = 'Most potent approved sweetener; heat stable; very low amounts needed';
UPDATE food_additives SET health_concerns_he = 'עלה שלם/תמצית גולמית לא מאושרים בארה"ב; עלול להיות טעם מר/ליקריץ' WHERE health_concerns = 'Whole leaf/crude extract not approved in US; may have bitter/licorice aftertaste';
UPDATE food_additives SET health_concerns_he = 'חלבון צמחי טבעי; רעילות נמוכה מאוד; EFSA 2021 אישר בטיחות' WHERE health_concerns = 'Natural plant protein; very low toxicity; EFSA 2021 confirmed safety';
UPDATE food_additives SET health_concerns_he = 'שימוש מסורתי בסין במשך מאות שנים; לא זוהו חששות בטיחות על ידי FDA' WHERE health_concerns = 'Traditional use in China for centuries; no safety concerns identified by FDA';
UPDATE food_additives SET health_concerns_he = 'חלבון משנה טעם; לא ממתיק כשלעצמו' WHERE health_concerns = 'Taste-modifying protein; not a sweetener per se';
UPDATE food_additives SET health_concerns_he = 'חלבון פרי סרנדיפיטי; רגיש לחום; ייצור קשה' WHERE health_concerns = 'Serendipity berry protein; heat-labile; difficult production';
UPDATE food_additives SET health_concerns_he = 'גישה טכנולוגית ולא מרכיב בודד; מפחית צורך בסוכר בניסוחים' WHERE health_concerns = 'Technology approach rather than single ingredient; reduces sugar needed in formulations';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי גבוה מאוד; מומר במהירות לגלוקוז' WHERE health_concerns = 'Very high GI; rapidly converted to glucose';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי גבוה מאוד; מתעכל במהירות; מילוי נפוץ באריזות ממתיק' WHERE health_concerns = 'Very high GI; rapidly digested; common filler in sweetener packets';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי גבוה מאוד; סירופ יפני מסורתי; פחות מתוק מסוכר' WHERE health_concerns = 'Very high GI; traditional Japanese syrup; less sweet than sugar';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי גבוה מאוד; פחות מתוק מסוכרוז; משמש למרקם' WHERE health_concerns = 'Very high GI; less sweet than sucrose; used for texture';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי גבוה מאוד; יחידת גלוקוז כפולה; נספג במהירות' WHERE health_concerns = 'Very high GI; double glucose unit; rapidly absorbed';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי גבוה מאוד; חששות לתכולת ארסן מאורז; ללא פרוקטוז' WHERE health_concerns = 'Very high GI; concerns about arsenic content from rice; fructose-free';
UPDATE food_additives SET health_concerns_he = 'תכולת פרוקטוז גבוהה מאוד; אינדקס גליקמי נמוך אך אותם חששות מטבוליזם כבדי כמו פרוקטוז; משווק כחלופה ''טבעית''' WHERE health_concerns = 'Very high fructose content; low GI but same liver metabolism concerns as fructose; marketed as ''natural'' alternative';
UPDATE food_additives SET health_concerns_he = 'אנרגיה בשחרור איטי; אינדקס גליקמי נמוך מסוכרוז' WHERE health_concerns = 'Slow-release energy; lower GI than sucrose';
UPDATE food_additives SET health_concerns_he = 'סוכר פשוט (גלוקוז). מתיקות נמוכה מסוכרוז. משמש באפייה ובעירוי.' WHERE health_concerns = 'Simple sugar (glucose). Lower sweetness than sucrose. Used in baking, IVs.';
UPDATE food_additives SET health_concerns_he = 'מינונים גבוהים עלולים לגרום ליתר לחץ דם, היפוקלמיה; לא מומלץ לצריכה גבוהה ממושכת' WHERE health_concerns = 'High doses may cause hypertension, hypokalemia; not recommended for prolonged high intake';
UPDATE food_additives SET health_concerns_he = 'אפקט משלשל במינונים גבוהים (>20 גרם/יום); שלשול אוסמוטי; נדרשת אזהרת EU למשלשל >10% פוליאול' WHERE health_concerns = 'Laxative effect at high doses (>20g/day); osmotic diarrhea; EU laxative warning required >10% polyol';
UPDATE food_additives SET health_concerns_he = 'השפעה פרה-ביוטית/משלשלת חזקה; מאושר FDA כמשלשל במרשם; מופק מלקטוז' WHERE health_concerns = 'Strong prebiotic/laxative effect; FDA-approved as prescription laxative; derived from lactose';
UPDATE food_additives SET health_concerns_he = 'פרה-ביוטי חזק; גזים/נפיחות במינונים גבוהים; ערך קלורי נמוך' WHERE health_concerns = 'Strong prebiotic; gas/bloating at high doses; low caloric value';
UPDATE food_additives SET health_concerns_he = 'פרה-ביוטי חזק; גזים/נפיחות במינונים גבוהים (>20 גרם/יום); יתרונות ספיגת סידן' WHERE health_concerns = 'Strong prebiotic; gas/bloating at high doses (>20g/day); calcium absorption benefits';
UPDATE food_additives SET health_concerns_he = 'פרה-ביוטי חזק במינונים נמוכים; נסבל היטב' WHERE health_concerns = 'Strong prebiotic at low doses; well tolerated';
UPDATE food_additives SET health_concerns_he = 'משלשל אוסמוטי חזק; פרה-ביוטי; משמש לטיפול באנצפלופתיה כבדית' WHERE health_concerns = 'Strong osmotic laxative; prebiotic; used for hepatic encephalopathy treatment';
UPDATE food_additives SET health_concerns_he = 'השפעות פרה-ביוטיות; אי נוחות במערכת העיכול במינונים גבוהים (>30 גרם); טעם פירותי/קרמל קל' WHERE health_concerns = 'Prebiotic effects; GI discomfort at high doses (>30g); slightly fruity/caramel taste';
UPDATE food_additives SET health_concerns_he = 'דיסכריד ניתן לעיכול מלא; שחרור איטי של גלוקוז ופרוקטוז; לא גורם עששת' WHERE health_concerns = 'Fully digestible disaccharide; slow release of glucose and fructose; non-cariogenic';
UPDATE food_additives SET health_concerns_he = 'חלק מ-IMO ניתנים לעיכול חלקי (יותר קלוריות מהנטען); פרה-ביוטי' WHERE health_concerns = 'Some IMO partially digestible (higher calorie than claimed); prebiotic';
UPDATE food_additives SET health_concerns_he = 'תערובת סורביטול, מלטיטול ואוליגוסכרידים מוקשים; השפעות משלשלות במינונים גבוהים' WHERE health_concerns = 'Mixture of sorbitol, maltitol, and hydrogenated oligosaccharides; laxative effects at high doses';
UPDATE food_additives SET health_concerns_he = 'זהה לסורביטול; משלשל במינונים גבוהים' WHERE health_concerns = 'Same as sorbitol; laxative at high doses';
UPDATE food_additives SET health_concerns_he = 'EFSA הוריד ADI ל-0.5 גרם/ק"ג ב-2023 בשל השפעות משלשלות; מחקרי קליבלנד קליניק קשרו לאירועים קרדיווסקולריים' WHERE health_concerns = 'EFSA lowered ADI to 0.5g/kg in 2023 due to laxative effects; Cleveland Clinic studies linked to cardiovascular events';
UPDATE food_additives SET health_concerns_he = 'הרכיב המתוק העיקרי בפרי הנזיר; דווח על תכונות נוגדות חמצון' WHERE health_concerns = 'Primary sweet component of monk fruit; antioxidant properties reported';
UPDATE food_additives SET health_concerns_he = 'ממתיק מסורתי; קלורי אך מכיל ברזל ונוגדי חמצון' WHERE health_concerns = 'Traditional sweetener; caloric but contains iron and antioxidants';
UPDATE food_additives SET health_concerns_he = 'ממתיק מקסיקני מסורתי; גושים בצורת חרוט; זהה לפנלה' WHERE health_concerns = 'Traditional Mexican sweetener; cone-shaped blocks; same as panela';
UPDATE food_additives SET health_concerns_he = 'ממתיק אסיאתי מסורתי; אינדקס גליקמי בינוני; קלורי' WHERE health_concerns = 'Traditional Asian sweetener; moderate GI; caloric';
UPDATE food_additives SET health_concerns_he = 'לא מזוקק; שומר על מינרלים אך עדיין קלורי; משווק כסוכר בריא יותר' WHERE health_concerns = 'Unrefined; retains minerals but still caloric; marketed as healthier sugar';
UPDATE food_additives SET health_concerns_he = 'סוכר לא מזוקק; מכיל מינרלים אך עדיין קלורי וגורם עששת' WHERE health_concerns = 'Unrefined sugar; contains minerals but still caloric and cariogenic';
UPDATE food_additives SET health_concerns_he = 'מקור המינרלים העשיר ביותר בין הסוכרים (ברזל, סידן, מגנזיום, אשלגן)' WHERE health_concerns = 'Richest mineral source among sugars (iron, calcium, magnesium, potassium)';
UPDATE food_additives SET health_concerns_he = 'עשיר בפוליפנולים ונוגדי חמצון; פרופיל מתוק-חמוץ; אינדקס גליקמי נמוך מסוכר' WHERE health_concerns = 'Rich in polyphenols and antioxidants; sweet-sour profile; lower GI than sugar';
UPDATE food_additives SET health_concerns_he = 'עשיר בברזל; שימוש איורוודי מסורתי; עדיין סוכר קלורי' WHERE health_concerns = 'Rich in iron; traditional Ayurvedic use; still caloric sugar';
UPDATE food_additives SET health_concerns_he = 'זהה לפנלה; סוכר קנה שלם לא מזוקק; שומר על מינרלים' WHERE health_concerns = 'Same as panela; unrefined whole cane sugar; retains minerals';
UPDATE food_additives SET health_concerns_he = 'אותו פרופיל קלורי/מטבולי כמו סוכרוז; תכונות נגד גיבוש' WHERE health_concerns = 'Same caloric/metabolic profile as sucrose; anti-crystallization properties';
UPDATE food_additives SET health_concerns_he = 'זהה לסוכרוז; ~20% מאספקת הסוכר העולמית מסלק סוכר' WHERE health_concerns = 'Same as sucrose; ~20% of global sugar supply from sugar beets';
UPDATE food_additives SET health_concerns_he = 'זהה לסוכרוז; מכיל עמילן תירס נגד גיבוש; נמס במהירות' WHERE health_concerns = 'Same as sucrose; contains anticaking cornstarch; rapidly dissolves';
UPDATE food_additives SET health_concerns_he = 'זהה לסוכר רגיל, מאושר אורגני.' WHERE health_concerns = 'Same as regular sugar, organic certified.';
UPDATE food_additives SET health_concerns_he = 'ממתיק מזון שלם; אינדקס גליקמי נמוך; עשיר בבטא-קרוטן' WHERE health_concerns = 'Whole food sweetener; low GI; rich in beta-carotene';
UPDATE food_additives SET health_concerns_he = 'ממתיק מזון שלם עם סיבים; עדיין קלורי' WHERE health_concerns = 'Whole food sweetener with fiber; still caloric';
UPDATE food_additives SET health_concerns_he = 'סוכר לבן עם מולסה שהוחזרה. מעט יותר מינרלים מלבן.' WHERE health_concerns = 'White sugar with molasses added back. Slightly more minerals than white.';
UPDATE food_additives SET health_concerns_he = 'סוכר מקני סוכר. פחות מעובד מסוכר לבן אם גולמי/טורבינדו.' WHERE health_concerns = 'Sugar from sugarcane. Less processed than white sugar if raw/turbinado.';
UPDATE food_additives SET health_concerns_he = 'עיכוב תפקוד בלוטת התריס; אנמיה המוליטית; מתמוגלובינמיה במינונים גבוהים' WHERE health_concerns = 'Thyroid function inhibition; hemolytic anemia; methemoglobinemia at high doses';
UPDATE food_additives SET health_concerns_he = 'שיבוש תפקוד בלוטת התריס; חשש לסרטנות (גידולי תריס בחולדות); רעילות גנטית (במבחנה); רעילות עצבית' WHERE health_concerns = 'Thyroid function disruption; potential carcinogenicity (thyroid tumors in rats); genotoxicity (in vitro); neurotoxicity';
UPDATE food_additives SET health_concerns_he = 'הפרעת בלוטת תריס (יתר/תת פעילות); דלקת בלוטת התריס; זפק; יתר פעילות תריס מושרית יוד (Jod-Basedow)' WHERE health_concerns = 'Thyroid dysfunction (hyper/hypothyroidism); Thyroiditis; Goiter; Iodine-induced hyperthyroidism (Jod-Basedow)';
UPDATE food_additives SET health_concerns_he = 'שיבוש בלוטת התריס; רעילות נוירו-התפתחותית; שיבוש אנדוקריני; רעילות כבדית' WHERE health_concerns = 'Thyroid disruption; neurodevelopmental toxicity; endocrine disruption; hepatotoxicity';
UPDATE food_additives SET health_concerns_he = 'רעיל; ממתיק היסטורי שנאסר בשל חששות בטיחות' WHERE health_concerns = 'Toxic; historical sweetener banned due to safety concerns';
UPDATE food_additives SET health_concerns_he = 'רעיל; מסרטן; שימש היסטורית ברפואה; כעת אסור' WHERE health_concerns = 'Toxic; carcinogenic; historically used in medicines; now banned';
UPDATE food_additives SET health_concerns_he = 'רעיל במינונים גבוהים; בטוח ברמות מזון' WHERE health_concerns = 'Toxic at high doses; safe at food levels';
UPDATE food_additives SET health_concerns_he = 'רעיל במינונים גבוהים; נזק לכבד' WHERE health_concerns = 'Toxic at high doses; liver damage';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית (נזק לכבד); מסרטן; אסור מאז 1950 בארה"ב' WHERE health_concerns = 'Hepatotoxicity (liver damage); carcinogenic; banned since 1950 in US';
UPDATE food_additives SET health_concerns_he = 'חששות הצטברות בדיל במינונים גבוהים' WHERE health_concerns = 'Tin accumulation concerns at high doses';
UPDATE food_additives SET health_concerns_he = 'משקעים ברשתית במינונים גבוהים' WHERE health_concerns = 'Retinal deposits at high doses';
UPDATE food_additives SET health_concerns_he = 'גירוי נשימתי; רעילות תאית; חשש לרעילות גנטית' WHERE health_concerns = 'Respiratory irritation; cytotoxicity; potential genotoxicity';
UPDATE food_additives SET health_concerns_he = 'חשד לטרטוגניות; חדירה לאיברים; ADI נמוך' WHERE health_concerns = 'Suspected teratogenicity; organ penetration; low ADI';
UPDATE food_additives SET health_concerns_he = 'רעילות עצבית סינרגיסטית עם כחול מבריק (46% הפחתת תאים לעומת 16% צפוי); קשרים לשמנות/מטבוליזם' WHERE health_concerns = 'Synergistic neurotoxicity with Brilliant Blue (46% cell reduction vs expected 16%); obesity/metabolic links';
UPDATE food_additives SET health_concerns_he = 'רגישות לסולפיטים; החמרת אסתמה' WHERE health_concerns = 'Sulfite sensitivity; asthma exacerbation';
UPDATE food_additives SET health_concerns_he = 'אותה רגישות לסולפיטים; חייב להצהיר כאלרגן מעל 10ppm' WHERE health_concerns = 'Same sulfite sensitivity; must declare as allergen above 10ppm';
UPDATE food_additives SET health_concerns_he = 'אותם חששות ניטרוזאמין; סרטן מעי גס/קיבה' WHERE health_concerns = 'Same nitrosamine concerns; colorectal/stomach cancer';
UPDATE food_additives SET health_concerns_he = 'אותם חששות כקבוצת הגלוטמטים' WHERE health_concerns = 'Same concerns as glutamates group';
UPDATE food_additives SET health_concerns_he = 'אותם חששות כקבוצת הגלוטמטים; צריכת מגנזיום' WHERE health_concerns = 'Same concerns as glutamates group; magnesium intake';
UPDATE food_additives SET health_concerns_he = 'אותם חששות כמו MSG; שיקול צריכת אשלגן' WHERE health_concerns = 'Same concerns as MSG; potassium intake consideration';
UPDATE food_additives SET health_concerns_he = 'משמש עם MSG; חששות לשיגדון/חומצת שתן; אסור במזון תינוקות' WHERE health_concerns = 'Used with MSG; concerns for gout/uric acid; banned in infant foods';
UPDATE food_additives SET health_concerns_he = 'זהה ל-E627; מעורר שיגדון; לא מותר במזון תינוקות' WHERE health_concerns = 'Same as E627; gout trigger; not permitted in infant foods';
UPDATE food_additives SET health_concerns_he = 'משמש עם ניטריט לעיכוב ניטרוזאמינים; כאבי ראש ברגישים' WHERE health_concerns = 'Used with nitrite to inhibit nitrosamines; headaches in sensitive';
UPDATE food_additives SET health_concerns_he = 'זהה לקפאין בתוספת השפעות טאנין על מערכת העיכול' WHERE health_concerns = 'Same as caffeine plus tannin-related GI effects';
UPDATE food_additives SET health_concerns_he = 'זהה לקפאין אך עם תחילת פעולה איטית יותר' WHERE health_concerns = 'Same as caffeine but potentially slower onset';
UPDATE food_additives SET health_concerns_he = 'זהה לקפאין אנהידרוס' WHERE health_concerns = 'Same as caffeine anhydrous';
UPDATE food_additives SET health_concerns_he = 'נסבל היטב; לא נראה משפיע על דופק/לחץ דם כמו קפאין' WHERE health_concerns = 'Well-tolerated; does not appear to affect heart rate/BP as much as caffeine';
UPDATE food_additives SET health_concerns_he = 'טכיקרדיה, הפרעות קצב לב' WHERE health_concerns = 'Tachycardia, cardiac arrhythmia';
UPDATE food_additives SET health_concerns_he = 'ראה רכיבים בודדים' WHERE health_concerns = 'See individual components';
UPDATE food_additives SET health_concerns_he = 'ראה אבץ; הפרעה במערכת העיכול במינונים גבוהים' WHERE health_concerns = 'See Zinc; GI upset at higher doses';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין D (עוצמה גבוהה יותר = מרווח בטיחות צר יותר)' WHERE health_concerns = 'See Vitamin D (higher potency means narrower safety margin)';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין C; תרומת נתרן במינונים גבוהים' WHERE health_concerns = 'See Vitamin C; Sodium contribution at high doses';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין C; מספק גם אשלגן' WHERE health_concerns = 'See Vitamin C; Also provides potassium';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין C; מספק גם סידן (~10% ממשקל)' WHERE health_concerns = 'See Vitamin C; Also provides calcium (~10% by weight)';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין C; יש לקחת בחשבון תכולת מגנזיום' WHERE health_concerns = 'See Vitamin C; Account for magnesium content';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין C ואבץ' WHERE health_concerns = 'See Vitamin C and Zinc';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין C' WHERE health_concerns = 'See Vitamin C';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין B6; נוירופתיה במינונים גבוהים כרוניים' WHERE health_concerns = 'See Vitamin B6; Neuropathy at chronic high doses';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין B5; השפעות מערכת העיכול מדי פעם' WHERE health_concerns = 'See Vitamin B5; Occasional GI effects';
UPDATE food_additives SET health_concerns_he = 'ראה ויטמין B2' WHERE health_concerns = 'See Vitamin B2';
UPDATE food_additives SET health_concerns_he = 'ראה סלניום; שמירה ארוכה יותר ברקמות מצורות אי-אורגניות' WHERE health_concerns = 'See Selenium; Longer tissue retention than inorganic forms';
UPDATE food_additives SET health_concerns_he = 'ראה אומגה-3 EPA; ריח דגים; הפרעה במערכת העיכול; דימום ממושך' WHERE health_concerns = 'See Omega-3 EPA; Fishy odor; GI upset; Prolonged bleeding';
UPDATE food_additives SET health_concerns_he = 'ראה מגנזיום; פחות סיכוי לגרום שלשול' WHERE health_concerns = 'See Magnesium; Less likely to cause diarrhea';
UPDATE food_additives SET health_concerns_he = 'ראה מגנזיום; אפקט משלשל במינונים גבוהים' WHERE health_concerns = 'See Magnesium; Laxative effect at higher doses';
UPDATE food_additives SET health_concerns_he = 'ראה מגנזיום; אפקט משלשל נפוץ' WHERE health_concerns = 'See Magnesium; Common laxative effect';
UPDATE food_additives SET health_concerns_he = 'ראה ברזל; השפעות מערכת עיכול דומות לסולפט ברזלי' WHERE health_concerns = 'See Iron; Similar GI effects to ferrous sulfate';
UPDATE food_additives SET health_concerns_he = 'ראה ברזל; השפעות מינימליות על מערכת העיכול' WHERE health_concerns = 'See Iron; Minimal GI effects';
UPDATE food_additives SET health_concerns_he = 'ראה ברזל; נסבל טוב יותר בדרך כלל' WHERE health_concerns = 'See Iron; Generally better tolerated';
UPDATE food_additives SET health_concerns_he = 'ראה ברזל; תופעות לוואי במערכת העיכול פחות מסולפט ברזלי' WHERE health_concerns = 'See Iron; GI side effects less than ferrous sulfate';
UPDATE food_additives SET health_concerns_he = 'ראה ברזל; מצוקת מערכת עיכול נפוצה (עצירות, בחילה, צואה שחורה)' WHERE health_concerns = 'See Iron; GI distress common (constipation, nausea, black stools)';
UPDATE food_additives SET health_concerns_he = 'ראה E171; חששות לרעילות גנטית' WHERE health_concerns = 'See E171; genotoxicity concerns';
UPDATE food_additives SET health_concerns_he = 'ראה E120; חשש אלרגן' WHERE health_concerns = 'See E120; allergen concern';
UPDATE food_additives SET health_concerns_he = 'ראה נחושת; גירוי מערכת העיכול במינונים גבוהים' WHERE health_concerns = 'See Copper; GI irritation at high doses';
UPDATE food_additives SET health_concerns_he = 'חששות דומים לקרגינן' WHERE health_concerns = 'Similar concerns as carrageenan';
UPDATE food_additives SET health_concerns_he = 'מזון שלם. אלרגן מרכזי (קזאין, מי גבינה). מקור לסידן, חלבון.' WHERE health_concerns = 'Whole food. Major allergen (casein, whey). Source of calcium, protein.';
UPDATE food_additives SET health_concerns_he = 'תיבול מזון שלם. מכיל אליצין. תכונות אנטי-מיקרוביאליות פוטנציאליות.' WHERE health_concerns = 'Whole food seasoning. Contains allicin. Potential antimicrobial properties.';
UPDATE food_additives SET health_concerns_he = 'חומץ מאלכוהול מזוקק. 5% חומצה אצטית. טהור מאוד.' WHERE health_concerns = 'Vinegar made from distilled alcohol. 5% acetic acid. Very pure.';
UPDATE food_additives SET health_concerns_he = 'שמן טרופי עשיר בשומן רווי. חששות קיימות (כריתת יערות).' WHERE health_concerns = 'Tropical oil high in saturated fat. Sustainability concerns (deforestation).';
UPDATE food_additives SET health_concerns_he = 'אגוז עץ. אלרגן מרכזי. גם מגרה עור (אורושיול בקליפה).' WHERE health_concerns = 'Tree nut. Major allergen. Also a skin irritant (urushiol in shell).';
UPDATE food_additives SET health_concerns_he = 'אלרגן אגוז עץ. עשיר בשומן חד בלתי רווי.' WHERE health_concerns = 'Tree nut allergen. High in monounsaturated fat.';
UPDATE food_additives SET health_concerns_he = 'אלרגן אגוז עץ. מקור טוב לוויטמין E, שומנים בריאים.' WHERE health_concerns = 'Tree nut allergen. Good source of vitamin E, healthy fats.';
UPDATE food_additives SET health_concerns_he = 'ירק שורש. עשיר בבטא-קרוטן. אלרגן נפוץ באזורים מסוימים.' WHERE health_concerns = 'Root vegetable. High in beta-carotene. Common allergen in some regions.';
UPDATE food_additives SET health_concerns_he = 'תבלין שורשי. תכונות נגד בחילה. נפוץ במטבח האסיאתי.' WHERE health_concerns = 'Rhizome spice. Anti-nausea properties. Common in Asian cuisine.';
UPDATE food_additives SET health_concerns_he = 'עמילן מחיטה. עלול להכיל עקבות גלוטן. משמש באטריות אסיאתיות.' WHERE health_concerns = 'Starch from wheat. May contain trace gluten. Used in Asian noodles.';
UPDATE food_additives SET health_concerns_he = 'עמילן מתירס. מעבה נפוץ. ללא גלוטן.' WHERE health_concerns = 'Starch from corn. Common thickener. Gluten-free.';
UPDATE food_additives SET health_concerns_he = 'דגן עיקרי. ללא גלוטן. חששות ארסן בחלק מהזנים.' WHERE health_concerns = 'Staple grain. Gluten-free. Arsenic concerns in some varieties.';
UPDATE food_additives SET health_concerns_he = 'חלב מעובד רגיל; אלרגן לסובלים מאי סבילות ללקטוז' WHERE health_concerns = 'Standard processed milk; allergen for lactose intolerant';
UPDATE food_additives SET health_concerns_he = 'זהה לחלב דל שומן. אלרגן חלבי.' WHERE health_concerns = 'Same as nonfat milk. Dairy allergen.';
UPDATE food_additives SET health_concerns_he = 'זהה לשום מיובש.' WHERE health_concerns = 'Same as Dehydrated Garlic.';
UPDATE food_additives SET health_concerns_he = 'זהה לטעם טבעי. צורת יחיד.' WHERE health_concerns = 'Same as Natural Flavor. Singular form.';
UPDATE food_additives SET health_concerns_he = 'עלייה במשקל (אגירת מים), אי נוחות במערכת העיכול במינונים גבוהים, התכווצויות שרירים אנקדוטליות' WHERE health_concerns = 'Weight gain (water retention), GI discomfort at high doses, anecdotal muscle cramps';
UPDATE food_additives SET health_concerns_he = 'חששות אלרגיה לסויה; בטוח בדרך כלל' WHERE health_concerns = 'Soy allergy concerns; generally safe';
UPDATE food_additives SET health_concerns_he = 'הרעלת דגים סקומברואידית (סמקה, כאב ראש, מצוקת מערכת עיכול); תגובות דמויות אלרגיה; לחץ דם נמוך' WHERE health_concerns = 'Scombroid fish poisoning (flushing, headache, GI distress); allergic-like reactions; hypotension';
UPDATE food_additives SET health_concerns_he = 'נדיר מאוד: אקנה במינונים גבוהים' WHERE health_concerns = 'Very rare: acne at high doses';
UPDATE food_additives SET health_concerns_he = 'נתוני בטיחות מוגבלים מאוד; חששות כבדיים פוטנציאליים' WHERE health_concerns = 'Very limited safety data; potential hepatic concerns';
UPDATE food_additives SET health_concerns_he = 'נתונים מוגבלים מאוד; לא פותח מסחרית' WHERE health_concerns = 'Very limited data; not commercially developed';
UPDATE food_additives SET health_concerns_he = 'פערי נתונים מסוימים; בטוח בדרך כלל ב-ADI; פוטנציאל אנטי-ויראלי צוין' WHERE health_concerns = 'Some data gaps; generally safe at ADI; antiviral potential noted';
UPDATE food_additives SET health_concerns_he = 'שימוש רפואי מסורתי; נוגד חמצון; דווח על תכונות אנטי-דלקתיות' WHERE health_concerns = 'Traditional medicinal use; antioxidant; anti-inflammatory properties reported';
UPDATE food_additives SET health_concerns_he = 'דומה ל-T-2: רעילות המטולוגית; רעילות חיסונית' WHERE health_concerns = 'Similar to T-2: hematotoxicity; immunotoxicity';
UPDATE food_additives SET health_concerns_he = 'דומה ל-Fumonisin B1; רעילות כבדית; רעילות כלייתית' WHERE health_concerns = 'Similar to Fumonisin B1; hepatotoxicity; nephrotoxicity';
UPDATE food_additives SET health_concerns_he = 'דומה ל-DMAA: סיכונים קרדיווסקולריים' WHERE health_concerns = 'Similar to DMAA: cardiovascular risks';
UPDATE food_additives SET health_concerns_he = 'זהה ל-DON: רעילות מערכת עיכול; רעילות חיסונית' WHERE health_concerns = 'Same as DON: GI toxicity; immunotoxicity';
UPDATE food_additives SET health_concerns_he = 'זהה למי גבינה; פחות לקטוז מ-WPC' WHERE health_concerns = 'Same as whey; less lactose than WPC';
UPDATE food_additives SET health_concerns_he = 'היפראקטיביות בילדים; תגובות אלרגיות; נזק כרומוזומלי במחקרי בעלי חיים' WHERE health_concerns = 'Hyperactivity in children; allergic reactions; chromosomal damage in animal studies';
UPDATE food_additives SET health_concerns_he = 'אין בחשיפה למינונים מומלצים' WHERE health_concerns = 'None at recommended doses';