UPDATE food_additives SET health_concerns_he = '100% קקאו. ללא סוכר. מכיל תאוברומין.' WHERE health_concerns = '100% cacao. No sugar added. Contains theobromine.';
UPDATE food_additives SET health_concerns_he = 'חלב 3.25% שומן. אלרגן חלב.' WHERE health_concerns = '3.25% fat milk. Dairy allergen.';
UPDATE food_additives SET health_concerns_he = '5% חומצה אצטית. משמר וממטעם טבעי.' WHERE health_concerns = '5% acetic acid. Natural preservative and flavoring.';
UPDATE food_additives SET health_concerns_he = '80%+ חלבון מחלב. אלרגן חלב. בשימוש בחטיפי חלבון.' WHERE health_concerns = '80%+ protein from milk. Dairy allergen. Used in protein bars.';
UPDATE food_additives SET health_concerns_he = 'תמיכה בסינתזת ATP; בשימוש בעייפות כרונית; סוכר פנטוז מתוק קלות' WHERE health_concerns = 'ATP synthesis support; used for chronic fatigue; mildly sweet pentose sugar';
UPDATE food_additives SET health_concerns_he = 'הצטברות קשורה לגלקטוסמיה; שימוש מסחרי מוגבל' WHERE health_concerns = 'Accumulation linked to galactosemia; limited commercial use';
UPDATE food_additives SET health_concerns_he = 'אקנה, נשירת שיער, שינויי מצב רוח, שיבוש הורמונלי; מעלה טסטוסטרון בנשים' WHERE health_concerns = 'Acne, hair loss, mood changes, hormone disruption; raises T in women';
UPDATE food_additives SET health_concerns_he = 'הרעלת ציאניד חריפה; כשל נשימתי; נזק עצבי; כרוני: השפעה על בלוטת התריס' WHERE health_concerns = 'Acute cyanide poisoning; respiratory failure; neurological damage; chronic: thyroid effects';
UPDATE food_additives SET health_concerns_he = 'עשב אדפטוגני; ספונינים מתוקים; נתוני בטיחות מוגבלים כתוסף מזון' WHERE health_concerns = 'Adaptogenic herb; sweet saponins; limited safety data as food additive';
UPDATE food_additives SET health_concerns_he = 'אבקת קקאו מושהת. טעם עדין יותר, צבע כהה יותר. פלבנולים מופחתים.' WHERE health_concerns = 'Alkalized cocoa powder. Milder flavor, darker color. Reduced flavanols.';
UPDATE food_additives SET health_concerns_he = 'חלופה ללא אלרגנים למלטודקסטרין תירס; מדד גליקמי גבוה מאוד; בשימוש כחומר מילוי' WHERE health_concerns = 'Allergen-free alternative to corn maltodextrin; very high GI; used as bulking agent';
UPDATE food_additives SET health_concerns_he = 'תגובות אלרגיות; החמרת אסטמה; אורטיקריה; אי-סבילות ברגישים לאספירין' WHERE health_concerns = 'Allergic reactions; asthma exacerbation; urticaria; intolerance in aspirin-sensitive individuals';
UPDATE food_additives SET health_concerns_he = 'תגובות אלרגיות; שחרור היסטמין; מעורר אסטמה; טרטוגניות (בעלי חיים); רעילות כבדית (מינון גבוה)' WHERE health_concerns = 'Allergic reactions; histamine release; asthma trigger; teratogenicity (animal); hepatotoxicity (high dose)';
UPDATE food_additives SET health_concerns_he = 'תגובות אלרגיות/רגישות יתר; פרו-דלקתי; השפעות על פוריות (מינון גבוה); רעילות גנטית (מודלים צמחיים)' WHERE health_concerns = 'Allergic/hypersensitivity reactions; pro-inflammatory; fertility effects (high dose); genotoxicity (plant models)';
UPDATE food_additives SET health_concerns_he = 'איות חלופי של עמילן תירס משופר.' WHERE health_concerns = 'Alternate spelling of Modified Corn Starch.';
UPDATE food_additives SET health_concerns_he = 'איות חלופי של תיאמין מונוניטראט. אותה תרכובת.' WHERE health_concerns = 'Alternate spelling of Thiamine Mononitrate. Same compound.';
UPDATE food_additives SET health_concerns_he = 'בין הממתיקים החזקים ביותר; מחקר אקדמי בלבד' WHERE health_concerns = 'Among most potent sweeteners; academic research only';
UPDATE food_additives SET health_concerns_he = 'שומן מן החי בבישול ומזון מעובד. לא חלאל/כשר ללא תעודה.' WHERE health_concerns = 'Animal fat used in cooking and processed foods. Not halal/kosher without cert.';
UPDATE food_additives SET health_concerns_he = 'שומן מן החי; מכיל שומן רווי' WHERE health_concerns = 'Animal fat; contains saturated fat';
UPDATE food_additives SET health_concerns_he = 'תכונות נגד סרטן נחקרו; לא מאושר למזון' WHERE health_concerns = 'Anticancer properties studied; not food-approved';
UPDATE food_additives SET health_concerns_he = 'השפעות אנטיכולינרגיות דומות לאטרופין; נמנום; בלבול' WHERE health_concerns = 'Anticholinergic effects similar to atropine; drowsiness; confusion';
UPDATE food_additives SET health_concerns_he = 'השפעות אנטיכולינרגיות: טכיקרדיה; אישונים מורחבים; יובש בפה; הזיות; פרכוסים (חריף)' WHERE health_concerns = 'Anticholinergic effects: tachycardia; dilated pupils; dry mouth; hallucinations; seizures (acute)';
UPDATE food_additives SET health_concerns_he = 'אנטי-תזונתי; נזק לכבד במינונים גבוהים' WHERE health_concerns = 'Antinutritional; liver damage at high doses';
UPDATE food_additives SET health_concerns_he = 'נוגד חמצון; טענות נגד השמנה נחקרו' WHERE health_concerns = 'Antioxidant; anti-obesity claims studied';
UPDATE food_additives SET health_concerns_he = 'חרדה, טכיקרדיה, יתר לחץ דם, התקפי פאניקה, בחילה, נדודי שינה' WHERE health_concerns = 'Anxiety, tachycardia, hypertension, panic attacks, nausea, insomnia';
UPDATE food_additives SET health_concerns_he = 'ארגיריה (שינוי צבע עור מכסף) בצריכה מופרזת; בטוח בכמויות זעירות' WHERE health_concerns = 'Argyria (silver skin discoloration) at excessive intake; safe in trace amounts';
UPDATE food_additives SET health_concerns_he = 'עשב תיבול ארומטי. נפוץ במטבח האיטלקי והתאילנדי.' WHERE health_concerns = 'Aromatic herb. Common in Italian and Thai cuisine.';
UPDATE food_additives SET health_concerns_he = 'ייצור אומנותי; לישה ידנית; מרקם עדין במיוחד; קלורי' WHERE health_concerns = 'Artisanal production; hand-kneaded; extremely fine texture; caloric';
UPDATE food_additives SET health_concerns_he = 'אסטמה ב-3-10% מהאסתמטיים; פריחה; צפצופים; אנפילקסיס; צריכה חורגת לעתים מה-ADI' WHERE health_concerns = 'Asthma in 3-10% of asthmatics; hives; wheezing; anaphylaxis; intakes often exceed ADI';
UPDATE food_additives SET health_concerns_he = 'עלול לעורר אסטמה, תגובות אלרגיות חמורות' WHERE health_concerns = 'Asthma triggers, severe allergic reactions';
UPDATE food_additives SET health_concerns_he = 'תרביות חיידקים לייצור גבינה. זנים שונים.' WHERE health_concerns = 'Bacterial cultures for cheese production. Various strains.';
UPDATE food_additives SET health_concerns_he = 'אסור באיחוד האירופי/אוסטרליה; בשימוש בגומי/פלסטיק; כימיקל מזרני יוגה' WHERE health_concerns = 'Banned EU/Australia; used in rubber/plastics; yoga mat chemical';
UPDATE food_additives SET health_concerns_he = 'אסור באיחוד האירופי/יפן; FDA ביטל GRAS 2024; כאבי ראש, אובדן זיכרון; ברום מצטבר' WHERE health_concerns = 'Banned EU/Japan; FDA revoked GRAS 2024; headaches, memory loss; bromine accumulates';
UPDATE food_additives SET health_concerns_he = 'אסור באיחוד האירופי/בריטניה/קנדה; מעכב ספיגת ויטמינים; מצוקה במערכת העיכול' WHERE health_concerns = 'Banned EU/UK/Canada; inhibits vitamin absorption; GI distress';
UPDATE food_additives SET health_concerns_he = 'אסור לשימוש ישיר במזון, חששות כבדיים' WHERE health_concerns = 'Banned for direct food use, liver concerns';
UPDATE food_additives SET health_concerns_he = 'אסור בארה"ב בשל חשש היסטורי לסרטן בחולדות; מאושר באיחוד האירופי/קנדה/מדינות רבות' WHERE health_concerns = 'Banned in US due to historical cancer concerns in rats; approved in EU/Canada/many countries';
UPDATE food_additives SET health_concerns_he = 'תיבול בסיסי, מינרל חיוני. WHO ממליץ <5 גרם/יום. צריכה מופרזת קשורה ליתר לחץ דם.' WHERE health_concerns = 'Basic seasoning, essential mineral. WHO recommends <5g/day. Excessive intake linked to hypertension.';
UPDATE food_additives SET health_concerns_he = 'מיטיב לעיכול ולבריאות הלב' WHERE health_concerns = 'Beneficial for digestion and heart health';
UPDATE food_additives SET health_concerns_he = 'פרי יער. אלרגן נפוץ בילדים.' WHERE health_concerns = 'Berry fruit. Common allergen in children.';
UPDATE food_additives SET health_concerns_he = 'הצטברות ביולוגית ברקמות (כבד, טחול, בלוטות לימפה); היווצרות גרנולומה בבעלי חיים' WHERE health_concerns = 'Bioaccumulation in tissues (liver, spleen, lymph nodes); granuloma formation in animals';
UPDATE food_additives SET health_concerns_he = 'זהה ביולוגית לגליקוזידי סטביול ממקור צמחי' WHERE health_concerns = 'Bioidentical to plant-derived steviol glycosides';
UPDATE food_additives SET health_concerns_he = 'חומר תפיחה ביולוגי. בשימוש בלחם, בירה, יין.' WHERE health_concerns = 'Biological leavening agent. Used in bread, beer, wine.';
UPDATE food_additives SET health_concerns_he = 'סמן ביולוגי לזיהומים פטרייתיים; לא בשימוש מסחרי כממתיק' WHERE health_concerns = 'Biomarker for certain fungal infections; not used commercially as sweetener';
UPDATE food_additives SET health_concerns_he = 'טעם מר; נסבל היטב בדרך כלל' WHERE health_concerns = 'Bitter taste; generally well-tolerated';
UPDATE food_additives SET health_concerns_he = 'חוסם קולטני טעם מתוק; בשימוש בניהול סוכרת; עשוי להוריד סוכר בדם' WHERE health_concerns = 'Blocks sweet taste receptors; used in diabetes management; may lower blood sugar';
UPDATE food_additives SET health_concerns_he = 'גידולי מוח בחולדות זכרים; בחילה; תגובות אלרגיות' WHERE health_concerns = 'Brain tumors in male rats; nausea; allergic reactions';
UPDATE food_additives SET health_concerns_he = 'חומר מילוי; משלשל קל במינונים גבוהים מאוד; סיב מסיס' WHERE health_concerns = 'Bulking agent; mild laxative at very high doses; soluble fiber';
UPDATE food_additives SET health_concerns_he = 'תוצר לוואי של ייצור גבינה. אלרגן חלב. עשיר בחלבון.' WHERE health_concerns = 'Byproduct of cheese making. Dairy allergen. High in protein.';
UPDATE food_additives SET health_concerns_he = 'סוכר C4; מתווך מטבולי; לא בשימוש מסחרי כממתיק' WHERE health_concerns = 'C4 sugar; metabolic intermediate; not used as sweetener commercially';
UPDATE food_additives SET health_concerns_he = 'דיכוי מערכת העצבים המרכזית; דיכוי נשימתי; התמכרות (במינונים חריפים גבוהים)' WHERE health_concerns = 'CNS depression; respiratory depression; dependence (at high acute doses)';
UPDATE food_additives SET health_concerns_he = 'ללא קפאין; עשיר בסידן; מדד גליקמי נמוך מסוכר; תכולת טאנין' WHERE health_concerns = 'Caffeine-free; high in calcium; lower GI than sugar; tannin content';
UPDATE food_additives SET health_concerns_he = 'השפעות הקשורות לקפאין; צריכה גבוהה ארוכת טווח קשורה לחששות בוושט' WHERE health_concerns = 'Caffeine-related effects; long-term high consumption linked to esophageal concerns';
UPDATE food_additives SET health_concerns_he = 'צורת מלח סידן של ציקלמט' WHERE health_concerns = 'Calcium salt form of cyclamate';
UPDATE food_additives SET health_concerns_he = 'קלורי (4.32 קק"ל/גרם); משלשל אוסמוטי במינונים גבוהים מאוד; בשימוש נרחב כלחלחן' WHERE health_concerns = 'Caloric (4.32 kcal/g); osmotic laxative at very high doses; widely used as humectant';
UPDATE food_additives SET health_concerns_he = 'סירופ סוכר קלורי; חששות זהים לסוכרוז' WHERE health_concerns = 'Caloric sugar syrup; same concerns as sucrose';
UPDATE food_additives SET health_concerns_he = 'לא ניתן לפירוק מטבולי בבני אדם; אפס קלוריות אך יקר במיוחד' WHERE health_concerns = 'Cannot be metabolized by humans; zero calories but extremely expensive';
UPDATE food_additives SET health_concerns_he = 'חששות סרטוגניים' WHERE health_concerns = 'Carcinogenic concerns';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות (מעי גס, שד, ערמונית בבעלי חיים); מוטגניות' WHERE health_concerns = 'Carcinogenicity (colon, breast, prostate in animals); mutagenicity';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות (כבד בבעלי חיים)' WHERE health_concerns = 'Carcinogenicity (liver in animals)';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות (כבד, וושט בבעלי חיים)' WHERE health_concerns = 'Carcinogenicity (liver, esophagus in animals)';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות (כבד, וושט); רעילות גנטית' WHERE health_concerns = 'Carcinogenicity (liver, esophagus); genotoxicity';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות (כבד, כליות בבעלי חיים); רעילות גנטית' WHERE health_concerns = 'Carcinogenicity (liver, kidney in animals); genotoxicity';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות (ריאות, מערכת עיכול); רעילות גנטית; רעילות כלייתית; רגישות עורית' WHERE health_concerns = 'Carcinogenicity (lung, GI tract); genotoxicity; nephrotoxicity; dermal sensitization';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות (ריאות, שלפוחית, עור); מחלות לב וכלי דם; סוכרת; נגעי עור; רעילות עצבית' WHERE health_concerns = 'Carcinogenicity (lung, bladder, skin); cardiovascular disease; diabetes; dermal lesions; neurotoxicity';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות (ריאות, כבד, לימפומה בבעלי חיים); רעילות גנטית' WHERE health_concerns = 'Carcinogenicity (lung, liver, lymphoma in animals); genotoxicity';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות (מערכת עיכול ונשימה עליונה כמטבוליט אלכוהול); מוטגניות; גירוי' WHERE health_concerns = 'Carcinogenicity (upper aerodigestive tract as alcohol metabolite); mutagenicity; irritation';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות; מחלות לב וכלי דם; נגעי עור' WHERE health_concerns = 'Carcinogenicity; cardiovascular disease; skin lesions';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות; לב וכלי דם; נגעי עור' WHERE health_concerns = 'Carcinogenicity; cardiovascular; skin lesions';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות; כלורקנה; רעילות חיסונית; רעילות לפוריות; שיבוש הורמונלי' WHERE health_concerns = 'Carcinogenicity; chloracne; immunotoxicity; reproductive toxicity; endocrine disruption';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות; רעילות גנטית (בין ה-PAH החזקים ביותר)' WHERE health_concerns = 'Carcinogenicity; genotoxicity (among the most potent PAHs)';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות; רעילות גנטית; דיכוי חיסוני' WHERE health_concerns = 'Carcinogenicity; genotoxicity; immunosuppression';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות; רעילות גנטית; מוטגניות; רעילות חיסונית' WHERE health_concerns = 'Carcinogenicity; genotoxicity; mutagenicity; immunotoxicity';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות; רעילות כבדית' WHERE health_concerns = 'Carcinogenicity; hepatotoxicity';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות; רעילות כבדית (החלש מבין ארבעת האפלטוקסינים העיקריים)' WHERE health_concerns = 'Carcinogenicity; hepatotoxicity (least potent of the four major aflatoxins)';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות; רעילות כבדית (פחות חזק מ-AFB1)' WHERE health_concerns = 'Carcinogenicity; hepatotoxicity (less potent than AFB1)';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות; רעילות כבדית; עובר לחלב מאפלטוקסין B1 במזון לבעלי חיים' WHERE health_concerns = 'Carcinogenicity; hepatotoxicity; carried into milk from aflatoxin B1 in animal feed';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות; רעילות כבדית; רעילות גנטית' WHERE health_concerns = 'Carcinogenicity; hepatotoxicity; genotoxicity';
UPDATE food_additives SET health_concerns_he = 'סרטוגניות; רעילות חיסונית; השפעות נוירו-התפתחותיות; שיבוש הורמונלי' WHERE health_concerns = 'Carcinogenicity; immunotoxicity; neurodevelopmental effects; endocrine disruption';