UPDATE food_additives SET health_concerns_he = 'חששות 4-MEI ו-THI; California Prop 65' WHERE health_concerns = '4-MEI and THI concerns; California Prop 65';
UPDATE food_additives SET health_concerns_he = 'חששות 4-מתילאימידזול (4-MEI); רשום ב-California Prop 65' WHERE health_concerns = '4-methylimidazole (4-MEI) concerns; California Prop 65 listed';
UPDATE food_additives SET health_concerns_he = 'נגזרת הדרים; מתיקות מתמשכת; תכונות נוגדות חמצון' WHERE health_concerns = 'Citrus derivative; lingering sweetness; antioxidant properties';
UPDATE food_additives SET health_concerns_he = 'קבוצת תרכובות הנגזרות מפלבנואידים; מתיקות מתמשכת' WHERE health_concerns = 'Class of compounds derived from flavonoids; lingering sweetness';
UPDATE food_additives SET health_concerns_he = 'הקרוב ביותר לטעם סוכר בין גליקוזידי הסטביול; מיוצר בתסיסה או המרה אנזימטית' WHERE health_concerns = 'Closest to sugar taste among steviol glycosides; produced via fermentation or enzymatic conversion';
UPDATE food_additives SET health_concerns_he = 'עצירות, אי נוחות במערכת העיכול; היפרקלצמיה; סיכון לאבני כליות' WHERE health_concerns = 'Constipation, GI discomfort; hypercalcemia; kidney stone risk';
UPDATE food_additives SET health_concerns_he = 'עצירות, בחילה, צואה שחורה, הפרעה במערכת העיכול; סיכון לעומס ברזל' WHERE health_concerns = 'Constipation, nausea, black stools, GI upset; iron overload risk';
UPDATE food_additives SET health_concerns_he = 'דרמטיטיס מגע; תסמיני אלרגיה לניקל דרך הפה באנשים רגישים' WHERE health_concerns = 'Contact dermatitis; oral nickel allergy symptoms in sensitized individuals';
UPDATE food_additives SET health_concerns_he = 'דרמטיטיס מגע; השפעות מערכתיות באנשים רגישים' WHERE health_concerns = 'Contact dermatitis; systemic effects in sensitized individuals';
UPDATE food_additives SET health_concerns_he = 'מכיל 4-MEI אפשרי מסרטן; אזהרת California Prop 65' WHERE health_concerns = 'Contains 4-MEI possibly carcinogenic; California Prop 65 warning';
UPDATE food_additives SET health_concerns_he = 'מכיל בטא-גלוקן; אינדקס גליקמי בינוני; לא ללא גלוטן' WHERE health_concerns = 'Contains beta-glucan; moderate GI; not gluten-free';
UPDATE food_additives SET health_concerns_he = 'מכיל סובין, נבט, אנדוספרם. יותר סיבים מקמח לבן. אלרגן גלוטן.' WHERE health_concerns = 'Contains bran, germ, endosperm. More fiber than white flour. Gluten allergen.';
UPDATE food_additives SET health_concerns_he = 'מכיל מוצקי קקאו, חמאת קקאו, סוכר. חשש אלרגן נפוץ (חלב).' WHERE health_concerns = 'Contains cocoa solids, cocoa butter, sugar. Common allergen concern (milk).';
UPDATE food_additives SET health_concerns_he = 'מכיל כורכומין (E100). טענות אנטי-דלקתיות. צבע צהוב.' WHERE health_concerns = 'Contains curcumin (E100). Anti-inflammatory claims. Yellow color.';
UPDATE food_additives SET health_concerns_he = 'מכיל אנזימים לאפיית לחם. מקור לעמילאז. מכיל גלוטן.' WHERE health_concerns = 'Contains enzymes for bread making. Source of amylase. Contains gluten.';
UPDATE food_additives SET health_concerns_he = 'מכיל פרוקטוז; אינדקס גליקמי נמוך מסירופ מייפל; תכולת מינרלים' WHERE health_concerns = 'Contains fructose; lower GI than maple syrup; mineral content';
UPDATE food_additives SET health_concerns_he = 'מכיל גלוטן (לא מתאים לצליאק); אינדקס גליקמי נמוך מסירופ אורז' WHERE health_concerns = 'Contains gluten (not suitable for celiac disease); lower GI than rice syrup';
UPDATE food_additives SET health_concerns_he = 'מכיל סיבי אינולין; אינדקס גליקמי נמוך מסוכרוז אך עדיין סוכר קלורי' WHERE health_concerns = 'Contains inulin fiber; lower GI than sucrose but still caloric sugar';
UPDATE food_additives SET health_concerns_he = 'מכיל לקטוז; לא מתאים לרגישי לקטוז; מתיקות עדינה; חומר מילוי חסכוני' WHERE health_concerns = 'Contains lactose; unsuitable for lactose intolerant; mild sweetness; cost-effective bulking agent';
UPDATE food_additives SET health_concerns_he = 'מכיל מינרלים (מנגן, אבץ) ונוגדי חמצון; עדיין סוכר קלורי' WHERE health_concerns = 'Contains minerals (manganese, zinc) and antioxidants; still a caloric sugar';
UPDATE food_additives SET health_concerns_he = 'מכיל מינרלים ופוליפנולים; קשור לאריכות ימים אוקינאווית (לא מוכח); קלורי' WHERE health_concerns = 'Contains minerals and polyphenols; associated with Okinawan longevity (unproven); caloric';
UPDATE food_additives SET health_concerns_he = 'מכיל פוליפנולים; אינדקס גליקמי נמוך מסוכר מזוקק; עדיין גורם עששת' WHERE health_concerns = 'Contains polyphenols; lower GI than refined sugar; still cariogenic';
UPDATE food_additives SET health_concerns_he = 'צורה גבישית; הנפח והמרקם הקרובים ביותר לסוכרוז בין הפוליאולים' WHERE health_concerns = 'Crystalline form; closest bulk and texture to sucrose among polyols';
UPDATE food_additives SET health_concerns_he = 'רעילות תאית (במבחנה); בטוח בדרך כלל ב-ADI' WHERE health_concerns = 'Cytotoxicity (in vitro); generally safe at ADI';
UPDATE food_additives SET health_concerns_he = 'רעילות תאית; רעילות חיסונית אפשרית; שיבוש תעלות יונים' WHERE health_concerns = 'Cytotoxicity; potential immunotoxicity; ion channel disruption';
UPDATE food_additives SET health_concerns_he = 'רעילות תאית; רעילות חיסונית אפשרית; פעילות יונופורית' WHERE health_concerns = 'Cytotoxicity; potential immunotoxicity; ionophoric activity';
UPDATE food_additives SET health_concerns_he = 'חומצת אמינו בצורת D; טעם מתוק; לא בשימוש מסחרי כממתיק' WHERE health_concerns = 'D-form amino acid; sweet taste; not used commercially as sweetener';
UPDATE food_additives SET health_concerns_he = 'מתפרק בקלות; עדיין לא ישים מסחרית' WHERE health_concerns = 'Denatures easily; not commercially viable yet';
UPDATE food_additives SET health_concerns_he = 'שחיקת שיניים; ירידה בצפיפות מינרלים בעצמות; בעיות כליות; אוסטאופורוזיס' WHERE health_concerns = 'Dental erosion; reduced bone mineral density; kidney problems; osteoporosis';
UPDATE food_additives SET health_concerns_he = 'פלואורוזיס שיניים (ילדים); פלואורוזיס שלדי (כרוני); בחילה; כאבי עצמות; נוקשות' WHERE health_concerns = 'Dental fluorosis (children); Skeletal fluorosis (chronic); Nausea; Bone pain; Stiffness';
UPDATE food_additives SET health_concerns_he = 'דרמטיטיס (אנשים רגישים); רעילות רבייתית/התפתחותית; חשש לסרטנות (נשימתית)' WHERE health_concerns = 'Dermatitis (sensitized individuals); reproductive/developmental toxicity; potential carcinogenicity (respiratory)';
UPDATE food_additives SET health_concerns_he = 'שלשול (הנפוץ ביותר); בחילה; התכווצויות בטן; היפרמגנזמיה (אי ספיקת כליות): לחץ דם נמוך, דיכוי נשימתי' WHERE health_concerns = 'Diarrhea (most common); Nausea; Abdominal cramping; Hypermagnesemia (renal impairment): hypotension, respiratory depression';
UPDATE food_additives SET health_concerns_he = 'שלשול במינונים גבוהים מאוד (>10 גרם); בטוח מאוד בדרך כלל' WHERE health_concerns = 'Diarrhea at very high doses (>10g); Generally very safe';
UPDATE food_additives SET health_concerns_he = 'שלשול, התכווצויות במערכת העיכול (במיוחד צורת אוקסיד)' WHERE health_concerns = 'Diarrhea, GI cramping (especially oxide form)';
UPDATE food_additives SET health_concerns_he = 'שלשול; בחילה; אבני כליות (אוקסלט); סיכון לעומס ברזל בהמוכרומטוזיס' WHERE health_concerns = 'Diarrhea; Nausea; Kidney stones (oxalate); Iron overload risk in hemochromatosis';
UPDATE food_additives SET health_concerns_he = 'רעילות דמוית דיאוקסין; רעילות כבדית; רעילות חיסונית; השפעות עור (כלוראקנה)' WHERE health_concerns = 'Dioxin-like toxicity; hepatotoxicity; immunotoxicity; skin effects (chloracne)';
UPDATE food_additives SET health_concerns_he = 'סחרחורת, יובש בפה, נדודי שינה אם נלקח מאוחר' WHERE health_concerns = 'Dizziness, dry mouth, insomnia if taken late';
UPDATE food_additives SET health_concerns_he = 'EFSA 2025 לא יכל לקבוע בטיחות (פערי נתונים); FDA מחשיב כבטוח; אי נוחות במערכת העיכול >50 גרם/מנה; מבטיח לניהול סוכר בדם' WHERE health_concerns = 'EFSA 2025 could not establish safety (data gaps); FDA considers safe; GI discomfort >50g/serving; promising for blood sugar management';
UPDATE food_additives SET health_concerns_he = 'צוינו פערי נתונים ב-EFSA; בהערכה מחדש' WHERE health_concerns = 'EFSA data gaps noted; under re-evaluation';
UPDATE food_additives SET health_concerns_he = 'EFSA הוריד ADI ל-0.5 גרם/ק"ג ב-2023 בשל השפעות משלשלות; מחקרי קליבלנד קליניק קשרו לסיכון קרדיווסקולרי (תצפיתי; EFSA לא מצא ראיות סיבתיות); כמעט אפס קלוריות' WHERE health_concerns = 'EFSA lowered ADI to 0.5g/kg in 2023 due to laxative effects; Cleveland Clinic studies linked to cardiovascular risk (observational; EFSA found no causal evidence); nearly zero calories';
UPDATE food_additives SET health_concerns_he = 'EFSA: כבר לא בטוח; חשש לרעילות גנטית; 36% בגודל ננו; ריקול Maya יוני 2025' WHERE health_concerns = 'EFSA: no longer safe; potential genotoxicity; 36% nano-sized; Maya recall June 2025';
UPDATE food_additives SET health_concerns_he = 'מונח אירופי ל-HFCS; אותם חששות מטבוליים; הגבלות מכסת ייצור הוסרו ב-2017' WHERE health_concerns = 'EU term for HFCS; same metabolic concerns; production quota restrictions removed in 2017';
UPDATE food_additives SET health_concerns_he = 'תערובת חדשה; אלולוז לא מאושר באיחוד האירופי' WHERE health_concerns = 'Emerging blend; allulose not approved in EU';
UPDATE food_additives SET health_concerns_he = 'קבוצה חדשה של תרכובות מתוקות טבעיות ממקורות צמחיים שונים' WHERE health_concerns = 'Emerging class of natural sweet compounds from various plant sources';
UPDATE food_additives SET health_concerns_he = 'פיגמנט טבעי חדש; לא מאושר למזון' WHERE health_concerns = 'Emerging natural pigment; not food-approved';
UPDATE food_additives SET health_concerns_he = 'חדש; תכונות אנטי-מיקרוביאליות; לא מאושר למזון' WHERE health_concerns = 'Emerging; antimicrobial properties; not food-approved';
UPDATE food_additives SET health_concerns_he = 'חדש; תכונות נוגדות חמצון' WHERE health_concerns = 'Emerging; antioxidant properties';
UPDATE food_additives SET health_concerns_he = 'שיבוש אנדוקריני (פעילות אסטרוגנית דומה ל-BPA); השפעות רבייתיות' WHERE health_concerns = 'Endocrine disruption (estrogenic activity similar to BPA); reproductive effects';
UPDATE food_additives SET health_concerns_he = 'שיבוש אנדוקריני; נזק לכליות/כבד בבעלי חיים; לעיתים משמש עם BHA/BHT' WHERE health_concerns = 'Endocrine disruption; kidney/liver damage in animals; often used with BHA/BHT';
UPDATE food_additives SET health_concerns_he = 'שיבוש אנדוקריני; רעילות רבייתית (אנטי-אנדרוגנית); רעילות כבדית; חשש לסרטנות' WHERE health_concerns = 'Endocrine disruption; reproductive toxicity (anti-androgenic); hepatotoxicity; potential carcinogenicity';
UPDATE food_additives SET health_concerns_he = 'זמינות ביולוגית משופרת; חששות ננו מקבילים לוויכוח TiO2' WHERE health_concerns = 'Enhanced bioavailability; nano concerns parallel to TiO2 debate';
UPDATE food_additives SET health_concerns_he = 'ממתיק דיפפטיד ניסיוני; עניין אקדמי' WHERE health_concerns = 'Experimental dipeptide sweetener; academic interest';
UPDATE food_additives SET health_concerns_he = 'ממתיק ניסיוני; לא זמין מסחרית' WHERE health_concerns = 'Experimental sweetener; not commercially available';
UPDATE food_additives SET health_concerns_he = 'ניסיוני; מבין הממתיקים החזקים הידועים' WHERE health_concerns = 'Experimental; among most potent sweeteners known';
UPDATE food_additives SET health_concerns_he = 'נתונים מוגבלים ביותר; לא זמין מסחרית' WHERE health_concerns = 'Extremely limited data; not commercially available';
UPDATE food_additives SET health_concerns_he = 'FD&C Red No. 3. E127. איסור FDA ממתין (גידולי תריס בחולדות).' WHERE health_concerns = 'FD&C Red No. 3. E127. FDA ban pending (thyroid tumors in rats).';
UPDATE food_additives SET health_concerns_he = 'מותסס; מכיל ויטמיני B; אינדקס גליקמי גבוה; נצרך חם באופן מסורתי' WHERE health_concerns = 'Fermented; contains B vitamins; high GI; traditionally consumed warm';
UPDATE food_additives SET health_concerns_he = 'ריח גוף דגי; הזעה; מצוקת מערכת עיכול; לחץ דם נמוך; רעילות כבדית' WHERE health_concerns = 'Fishy body odor; Sweating; GI distress; Hypotension; Hepatotoxicity';
UPDATE food_additives SET health_concerns_he = 'גיהוקים דגיים, אי נוחות במערכת העיכול, צואה רכה; סיכון מוגבר לדימום במינונים גבוהים' WHERE health_concerns = 'Fishy burps, GI discomfort, loose stools; increased bleeding risk at high doses';
UPDATE food_additives SET health_concerns_he = 'גיהוקים דגיים; הפרעת מערכת עיכול; זמן דימום מוגבר; עלייה אפשרית ב-LDL; דיכוי חיסוני במינונים גבוהים מאוד' WHERE health_concerns = 'Fishy burps; GI upset; Increased bleeding time; Possible LDL increase; Immunosuppression at very high doses';
UPDATE food_additives SET health_concerns_he = 'סמקה (חומצה ניקוטינית); נזק לכבד; היפרגליקמיה; מצוקת מערכת עיכול' WHERE health_concerns = 'Flushing (nicotinic acid); Liver damage; Hyperglycemia; GI distress';
UPDATE food_additives SET health_concerns_he = 'סמקה, גרד, הפרעת מערכת עיכול (צורת חומצה ניקוטינית); רעילות כבדית במינונים גבוהים מאוד' WHERE health_concerns = 'Flushing, itching, GI upset (nicotinic acid form); hepatotoxicity at very high doses';
UPDATE food_additives SET health_concerns_he = 'סמקה; רעילות כבדית; הפרעת מערכת עיכול; היפרגליקמיה' WHERE health_concerns = 'Flushing; Hepatotoxicity; GI upset; Hyperglycemia';
UPDATE food_additives SET health_concerns_he = 'חששות מערכת עיכול במינונים גבוהים; שיבוש מיקרוביום המעי במחקרי בעלי חיים' WHERE health_concerns = 'GI concerns at high doses; gut microbiome disruption in animal studies';
UPDATE food_additives SET health_concerns_he = 'חששות מערכת עיכול שנויים במחלוקת; לעיתים נמנע בתיוג נקי' WHERE health_concerns = 'GI concerns debated; often avoided in clean-label';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול (פחות תכוף לפי הטענות)' WHERE health_concerns = 'GI discomfort (less frequent per claims)';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול (פחות ממונוהידרט לפי טענות שיווקיות)' WHERE health_concerns = 'GI discomfort (less than monohydrate per marketing claims)';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול (בחילה, שלשול), טעם לא נעים' WHERE health_concerns = 'GI discomfort (nausea, diarrhea), unpleasant taste';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול במינונים גבוהים; אינטראקציות חומצות אמינו בודדות' WHERE health_concerns = 'GI discomfort at high doses; individual AA interactions';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול במינונים גבוהים; תחרות תיאורטית עם טריפטופן' WHERE health_concerns = 'GI discomfort at high doses; theoretical tryptophan competition';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, נפיחות; סיכון לאלרגיה לחלב' WHERE health_concerns = 'GI discomfort, bloating; milk allergy risk';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, שלשול; סיכון זיהום' WHERE health_concerns = 'GI discomfort, diarrhea; contamination risk';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, ישנוניות; דווח על פגיעה בכבד (נדיר); שינוי הורמוני תריס' WHERE health_concerns = 'GI discomfort, drowsiness; liver injury reported (rare); thyroid hormone alteration';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, חוסר איזון אלקטרוליטים במינונים גבוהים, טעם מלוח' WHERE health_concerns = 'GI discomfort, electrolyte imbalance at high doses, salty taste';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, ריח גוף דגי, שלשול במינונים גבוהים' WHERE health_concerns = 'GI discomfort, fishy body odor, diarrhea at high doses';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, ריח דגי (בטאין)' WHERE health_concerns = 'GI discomfort, fishy odor (betaine)';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, טעם דגי' WHERE health_concerns = 'GI discomfort, fishy taste';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, גזים' WHERE health_concerns = 'GI discomfort, gas';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, כאב ראש; אנטי-אנדרוגני' WHERE health_concerns = 'GI discomfort, headache; anti-androgenic';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, כאב ראש; עלול להכהות שתן' WHERE health_concerns = 'GI discomfort, headache; may darken urine';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, כאב ראש; אלרגיה לרכיכות (אם מופק מרכיכות)' WHERE health_concerns = 'GI discomfort, headache; shellfish allergy (if shellfish-derived)';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, צרבת, ירידה בתיאבון' WHERE health_concerns = 'GI discomfort, heartburn, decreased appetite';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, נדודי שינה, ריח דגי' WHERE health_concerns = 'GI discomfort, insomnia, fishy odor';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, ריח גוף דמוי סירופ מייפל, שלשול' WHERE health_concerns = 'GI discomfort, maple syrup-like body odor, diarrhea';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, בחילה אם נלקח ללא נוזל' WHERE health_concerns = 'GI discomfort, nausea if taken without fluid';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, בחילה, שלשול; נדיר: תגובות אנפילקטואידיות' WHERE health_concerns = 'GI discomfort, nausea, diarrhea; rare: anaphylactoid reactions';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, פריחה בעור; סיכון להיפוגליקמיה עם תרופות סוכרת' WHERE health_concerns = 'GI discomfort, skin rash; hypoglycemia risk with diabetes meds';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, הזעה; עלול להשפיע על סוכר בדם' WHERE health_concerns = 'GI discomfort, sweating; may affect blood sugar';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול, חלומות חיים (B6), ישנוניות' WHERE health_concerns = 'GI discomfort, vivid dreams (B6), drowsiness';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; חשש לתפקוד תריס (גלוקוזינולטים)' WHERE health_concerns = 'GI discomfort; concern for thyroid function (glucosinolates)';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; סיכון זיהום (מתכות כבדות, מיקרוציסטין)' WHERE health_concerns = 'GI discomfort; contamination risk (heavy metals, microcystin)';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; סיכון זיהום בגורמי גדילה' WHERE health_concerns = 'GI discomfort; contamination risk with growth factors';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; מומר לקריאטינין מהר יותר ממונוהידרט' WHERE health_concerns = 'GI discomfort; converts to creatinine faster than monohydrate';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; נתרן גבוה' WHERE health_concerns = 'GI discomfort; high sodium';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; סוכר גבוה בצורת מיץ' WHERE health_concerns = 'GI discomfort; high sugar in juice form';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; היפוקלצמיה במינונים גבוהים מאוד' WHERE health_concerns = 'GI discomfort; hypocalcemia at very high doses';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; פרופיל חומצות אמינו לא שלם' WHERE health_concerns = 'GI discomfort; incomplete amino acid profile';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; ראיות מוגבלות לעדיפות על מלטודקסטרין' WHERE health_concerns = 'GI discomfort; limited evidence of superiority over maltodextrin';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; זמינות ביולוגית דרך הפה מוגבלת' WHERE health_concerns = 'GI discomfort; limited oral bioavailability';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; זמינות ביולוגית נמוכה מ-L-טירוזין' WHERE health_concerns = 'GI discomfort; lower bioavailability than L-tyrosine';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; נתרן נמוך ממשקאות ספורט' WHERE health_concerns = 'GI discomfort; lower sodium than sports drinks';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; לא חלבון שלם (חסר טריפטופן)' WHERE health_concerns = 'GI discomfort; not a complete protein (lacks tryptophan)';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; דוח מקרה אחד של נזק ממוצר לא מאומת' WHERE health_concerns = 'GI discomfort; one case report of harm from unverified product';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; הפחתת לחץ דם אפשרית' WHERE health_concerns = 'GI discomfort; potential blood pressure reduction';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; איכות משתנה (חלק מופק מקולגן, לא מרקמת שריר)' WHERE health_concerns = 'GI discomfort; quality varies (some derived from collagen, not muscle)';
UPDATE food_additives SET health_concerns_he = 'אי נוחות במערכת העיכול; נדיר: פריחה בעור באנשים רגישים' WHERE health_concerns = 'GI discomfort; rare: skin rash in sensitive individuals';
UPDATE food_additives SET health_concerns_he = 'מצוקת מערכת עיכול, בחילה בצריכה גבוהה ללא הסתגלות' WHERE health_concerns = 'GI distress, nausea at high intake without adaptation';
UPDATE food_additives SET health_concerns_he = 'מצוקת מערכת עיכול; בחילה/הקאה; עצירות; המוכרומטוזיס; נזק לאיברים (כבד/לב); עור אפרפר' WHERE health_concerns = 'GI distress; Nausea/vomiting; Constipation; Hemochromatosis; Organ damage (liver/heart); Grey skin';
UPDATE food_additives SET health_concerns_he = 'ויכוח על דלקת במערכת העיכול; הנחקר ביותר להשפעות שליליות' WHERE health_concerns = 'GI inflammation debate; most studied for adverse effects';
UPDATE food_additives SET health_concerns_he = 'דלקת במערכת העיכול; נגעים במעי; סרטן מעי גס במעבדה; עצומת איסור FDA; הוסר מאורגני USDA 2016' WHERE health_concerns = 'GI inflammation; intestinal lesions; colon cancer in lab; FDA ban petition; removed from USDA organic 2016';
UPDATE food_additives SET health_concerns_he = 'גירוי מערכת העיכול במינונים גבוהים; משנה מטבוליזם תרופות' WHERE health_concerns = 'GI irritation at high doses; alters drug metabolism';
UPDATE food_additives SET health_concerns_he = 'גירוי מערכת העיכול, צרבת אם נלקח ללא אוכל' WHERE health_concerns = 'GI irritation, heartburn if taken without food';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי ייחוס (100); עליית סוכר מהירה בדם; מקדם עששת' WHERE health_concerns = 'GI reference (100); rapid blood sugar spike; promotes dental caries';
UPDATE food_additives SET health_concerns_he = 'הפרעת מערכת עיכול, נשירת שיער, שבריריות ציפורניים, סלנוזיס בעודף' WHERE health_concerns = 'GI upset, hair loss, nail brittleness, selenosis at excess';
UPDATE food_additives SET health_concerns_he = 'הפרעת מערכת עיכול, נזק לכבד בעודף כרוני' WHERE health_concerns = 'GI upset, liver damage at chronic excess';
UPDATE food_additives SET health_concerns_he = 'הפרעת מערכת עיכול; פוטנציאל לעודף בשילוב עם מזונות מועשרים' WHERE health_concerns = 'GI upset; potential for excess if combined with fortified foods';
UPDATE food_additives SET health_concerns_he = 'גזים, נפיחות בהתחלה; זיהומים נדירים במדוכאי חיסון' WHERE health_concerns = 'Gas, bloating initially; rare infections in immunocompromised';
UPDATE food_additives SET health_concerns_he = 'גירוי מערכת העיכול (בחילה, הקאה, שלשול) במינונים גבוהים' WHERE health_concerns = 'Gastrointestinal irritation (nausea, vomiting, diarrhea) at high doses';
UPDATE food_additives SET health_concerns_he = 'רעילות מערכת העיכול (בחילה, הקאה, שלשול); השפעות נוירולוגיות (בלבול, כאב ראש); פעילות המוליטית במינונים גבוהים' WHERE health_concerns = 'Gastrointestinal toxicity (nausea, vomiting, diarrhea); neurological effects (confusion, headache); hemolytic activity at high doses';
UPDATE food_additives SET health_concerns_he = 'רעילות מערכת העיכול; רעילות חיסונית; רעילות עצבית; רעילות גנטית' WHERE health_concerns = 'Gastrointestinal toxicity; immunotoxicity; neurotoxicity; genotoxicity';
UPDATE food_additives SET health_concerns_he = 'קטגוריית נוגדי חמצון כללית; רובם בטוחים' WHERE health_concerns = 'General antioxidant category; most are safe';
UPDATE food_additives SET health_concerns_he = 'מרכיבי חלב כלליים; מכיל אלרגנים' WHERE health_concerns = 'General dairy ingredients; contains allergens';
UPDATE food_additives SET health_concerns_he = 'קטגוריית מתחלב כללית; הבטיחות תלויה בתרכובת הספציפית' WHERE health_concerns = 'General emulsifier category; safety depends on specific compound';
UPDATE food_additives SET health_concerns_he = 'צביעת מזון כללית; חלק מהצבעים המלאכותיים קשורים להיפראקטיביות' WHERE health_concerns = 'General food coloring; some artificial colors linked to hyperactivity';
UPDATE food_additives SET health_concerns_he = 'קטגוריית משמר כללית; הבטיחות תלויה בתרכובת הספציפית' WHERE health_concerns = 'General preservative category; safety depends on specific compound';
UPDATE food_additives SET health_concerns_he = 'מונח כללי לסוכרים; צריכה מופרזת קשורה להשמנה וסוכרת' WHERE health_concerns = 'General term for sugars; excessive intake linked to obesity and diabetes';
UPDATE food_additives SET health_concerns_he = 'נחשב בטוח בדרך כלל; דרמטיטיס מגע נדירה' WHERE health_concerns = 'Generally considered safe; rare contact dermatitis';
UPDATE food_additives SET health_concerns_he = 'נחשב בטוח יותר מחומצה פולית; פחות חששות הסוואה' WHERE health_concerns = 'Generally considered safer than folic acid; Fewer masking concerns';
UPDATE food_additives SET health_concerns_he = 'סיכון נמוך בדרך כלל; חששות עיבוד-יתר' WHERE health_concerns = 'Generally low-risk; ultra-processing concerns';
UPDATE food_additives SET health_concerns_he = 'מוכר בדרך כלל כבטוח. חששות סביבתיים.' WHERE health_concerns = 'Generally recognized as safe. Environmental concerns.';
UPDATE food_additives SET health_concerns_he = 'מוכר בדרך כלל כבטוח. צריכה מופרזת קשורה ליתר לחץ דם.' WHERE health_concerns = 'Generally recognized as safe. Excessive consumption linked to hypertension.';
UPDATE food_additives SET health_concerns_he = 'מוכר בדרך כלל כבטוח. צריכה מופרזת קשורה להשמנה וסוכרת.' WHERE health_concerns = 'Generally recognized as safe. Excessive consumption linked to obesity and diabetes.';
UPDATE food_additives SET health_concerns_he = 'מוכר בדרך כלל כבטוח. צריכה מופרזת קשורה להשמנה.' WHERE health_concerns = 'Generally recognized as safe. Excessive consumption linked to obesity.';
UPDATE food_additives SET health_concerns_he = 'מוכר בדרך כלל כבטוח. צריכה מופרזת עלולה להשפיע על מטבוליזם הכבד.' WHERE health_concerns = 'Generally recognized as safe. Excessive consumption may affect liver metabolism.';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל (נגזרת ויטמין C); סיכון בנזן עם נתרן בנזואט' WHERE health_concerns = 'Generally safe (vitamin C derivative); benzene risk with sodium benzoate';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל ברמות מאושרות' WHERE health_concerns = 'Generally safe at approved levels';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל במריחה, שימוש מוגבל במזון' WHERE health_concerns = 'Generally safe topically, limited food use';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, צורת ויטמין B' WHERE health_concerns = 'Generally safe, B vitamin form';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, S-אליל ציסטאין' WHERE health_concerns = 'Generally safe, S-allyl cysteine';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מלח חומצה אצטית' WHERE health_concerns = 'Generally safe, acetic acid salt';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אליצין' WHERE health_concerns = 'Generally safe, allicin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצה אמינו סולפונית' WHERE health_concerns = 'Generally safe, amino sulfonic acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אנאטו' WHERE health_concerns = 'Generally safe, annatto';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אנתוציאנוזידים' WHERE health_concerns = 'Generally safe, anthocyanosides';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אנטי-מיקרוביאלי' WHERE health_concerns = 'Generally safe, antimicrobial';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצת שומן אנטי-מיקרוביאלית' WHERE health_concerns = 'Generally safe, antimicrobial fatty acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אסקרידול' WHERE health_concerns = 'Generally safe, ascaridole';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אספלטין' WHERE health_concerns = 'Generally safe, aspalathin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אוונאנתרמידים' WHERE health_concerns = 'Generally safe, avenanthramides';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פפטיד בקטריוצין' WHERE health_concerns = 'Generally safe, bacteriocin peptide';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, שרף דבורים' WHERE health_concerns = 'Generally safe, bee resin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, הפרשת דבורים' WHERE health_concerns = 'Generally safe, bee secretion';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, בטולין' WHERE health_concerns = 'Generally safe, betulin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ברומלאין' WHERE health_concerns = 'Generally safe, bromelain';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אצות חומות' WHERE health_concerns = 'Generally safe, brown algae';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, תוצרי השחמה' WHERE health_concerns = 'Generally safe, browning products';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קרוטנואידים' WHERE health_concerns = 'Generally safe, carotenoids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קרבקרול' WHERE health_concerns = 'Generally safe, carvacrol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קרוון' WHERE health_concerns = 'Generally safe, carvone';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פוליפפטיד קטיוני' WHERE health_concerns = 'Generally safe, cationic polypeptide';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצות כלורוגניות' WHERE health_concerns = 'Generally safe, chlorogenic acids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, כלורופיל' WHERE health_concerns = 'Generally safe, chlorophyll';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קינמאלדהיד' WHERE health_concerns = 'Generally safe, cinnamaldehyde';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מרכיב קינמון' WHERE health_concerns = 'Generally safe, cinnamon component';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פלבנואיד הדרים' WHERE health_concerns = 'Generally safe, citrus flavonoid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פלבנואידי הדרים' WHERE health_concerns = 'Generally safe, citrus flavonoids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מרכיב שמן הדרים' WHERE health_concerns = 'Generally safe, citrus oil component';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מרכיב שמן ציפורן' WHERE health_concerns = 'Generally safe, clove oil component';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מכיל חומצה אצטית' WHERE health_concerns = 'Generally safe, contains acetic acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מכיל מינרלים' WHERE health_concerns = 'Generally safe, contains minerals';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מכיל מונקולינים' WHERE health_concerns = 'Generally safe, contains monacolins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מכיל מינרלים בכמות עקבית' WHERE health_concerns = 'Generally safe, contains trace minerals';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קומינאלדהיד' WHERE health_concerns = 'Generally safe, cuminaldehyde';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, כורכומינואידים' WHERE health_concerns = 'Generally safe, curcuminoids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, דלפינידינים' WHERE health_concerns = 'Generally safe, delphinidins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, תרכובת דיתיול' WHERE health_concerns = 'Generally safe, dithiol compound';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אלגיטנינים' WHERE health_concerns = 'Generally safe, ellagitannins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אנזים מחלבון ביצה' WHERE health_concerns = 'Generally safe, enzyme from egg white';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אסטרגול' WHERE health_concerns = 'Generally safe, estragole';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אוקליפטול' WHERE health_concerns = 'Generally safe, eucalyptol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פלבן-3-אול' WHERE health_concerns = 'Generally safe, flavan-3-ol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פלבנולים' WHERE health_concerns = 'Generally safe, flavanols';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, גליקוזיד פלבנואיד' WHERE health_concerns = 'Generally safe, flavonoid glycoside';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פיגמנטי פלבנואיד' WHERE health_concerns = 'Generally safe, flavonoid pigments';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, סיבי פרי' WHERE health_concerns = 'Generally safe, fruit fiber';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ג''ינסנוזידים' WHERE health_concerns = 'Generally safe, ginsenosides';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מקור גלוטמט' WHERE health_concerns = 'Generally safe, glutamate source';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, גליצירהיזין' WHERE health_concerns = 'Generally safe, glycyrrhizin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, הספרידין' WHERE health_concerns = 'Generally safe, hesperidin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מזוקק מאוד' WHERE health_concerns = 'Generally safe, highly refined';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, הורמון' WHERE health_concerns = 'Generally safe, hormone';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, טנין הניתן להידרוליזה' WHERE health_concerns = 'Generally safe, hydrolyzable tannin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, הידרוקסיטירוזול' WHERE health_concerns = 'Generally safe, hydroxytyrosol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מינרל אינרטי' WHERE health_concerns = 'Generally safe, inert mineral';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, הפרשת חרקים' WHERE health_concerns = 'Generally safe, insect secretion';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, משכר' WHERE health_concerns = 'Generally safe, intoxicating';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אינולין' WHERE health_concerns = 'Generally safe, inulin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חיידקי חומצה לקטית' WHERE health_concerns = 'Generally safe, lactic acid bacteria';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, תכולת לקטוז' WHERE health_concerns = 'Generally safe, lactose content';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, זרע קטנית' WHERE health_concerns = 'Generally safe, legume seed';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, נוגד חמצון שומני' WHERE health_concerns = 'Generally safe, lipid antioxidant';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, לוטאין' WHERE health_concerns = 'Generally safe, lutein';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ליקופן' WHERE health_concerns = 'Generally safe, lycopene';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ליזין' WHERE health_concerns = 'Generally safe, lysine';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מקמידים' WHERE health_concerns = 'Generally safe, macamides';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מנגיפרין' WHERE health_concerns = 'Generally safe, mangiferin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, קרוטנואיד ימי' WHERE health_concerns = 'Generally safe, marine carotenoid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מנטול' WHERE health_concerns = 'Generally safe, menthol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מתיל סליצילט' WHERE health_concerns = 'Generally safe, methyl salicylate';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מתילגליאוקסל' WHERE health_concerns = 'Generally safe, methylglyoxal';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חלבון חלב' WHERE health_concerns = 'Generally safe, milk protein';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מקור מינרלי' WHERE health_concerns = 'Generally safe, mineral source';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, סוכר פטריות' WHERE health_concerns = 'Generally safe, mushroom sugar';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מיריסטיצין' WHERE health_concerns = 'Generally safe, myristicin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, נרינגין' WHERE health_concerns = 'Generally safe, naringin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, נסונין' WHERE health_concerns = 'Generally safe, nasunin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, נטוקינאז' WHERE health_concerns = 'Generally safe, nattokinase';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, מערכת אנזימי חלב טבעית' WHERE health_concerns = 'Generally safe, natural milk enzyme system';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ממתיק טבעי' WHERE health_concerns = 'Generally safe, natural sweetener';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, עשן עץ טבעי' WHERE health_concerns = 'Generally safe, natural wood smoke';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, נוקלאוזיד' WHERE health_concerns = 'Generally safe, nucleoside';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פלבנואידים אוליגומריים' WHERE health_concerns = 'Generally safe, oligomeric flavonoids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אומגה-3' WHERE health_concerns = 'Generally safe, omega-3';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אומגה-7' WHERE health_concerns = 'Generally safe, omega-7';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אורגנו/קורנית' WHERE health_concerns = 'Generally safe, oregano/thyme';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצות אורגניות' WHERE health_concerns = 'Generally safe, organic acids';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, אוריזנול' WHERE health_concerns = 'Generally safe, oryzanol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, שעוות דקל' WHERE health_concerns = 'Generally safe, palm wax';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פפאין' WHERE health_concerns = 'Generally safe, papain';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, שבר פפטידי' WHERE health_concerns = 'Generally safe, peptide fragment';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פנוליות' WHERE health_concerns = 'Generally safe, phenolics';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פיקוציאנין' WHERE health_concerns = 'Generally safe, phycocyanin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פיפרין' WHERE health_concerns = 'Generally safe, piperine';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, שעוות צמחים' WHERE health_concerns = 'Generally safe, plant wax';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פוליסכריד' WHERE health_concerns = 'Generally safe, polysaccharide';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פרוביוטי' WHERE health_concerns = 'Generally safe, probiotic';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, פיגמנט חלבוני' WHERE health_concerns = 'Generally safe, protein pigment';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, רוזווינים' WHERE health_concerns = 'Generally safe, rosavins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, רוטין' WHERE health_concerns = 'Generally safe, rutin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, סליצין' WHERE health_concerns = 'Generally safe, salicin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, תמצית אצות' WHERE health_concerns = 'Generally safe, seaweed extract';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ססמול/ססמולין' WHERE health_concerns = 'Generally safe, sesamol/sesamolin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, נגזרת רכיכות' WHERE health_concerns = 'Generally safe, shellfish derivative';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, סילימרין' WHERE health_concerns = 'Generally safe, silymarin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, סקוואלן' WHERE health_concerns = 'Generally safe, squalene';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, סולפורפן' WHERE health_concerns = 'Generally safe, sulforaphane';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, טרפנים' WHERE health_concerns = 'Generally safe, terpenes';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, תיאפלבינים' WHERE health_concerns = 'Generally safe, theaflavins';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, תימול' WHERE health_concerns = 'Generally safe, thymol';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, הפרשת עץ' WHERE health_concerns = 'Generally safe, tree exudate';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצה טריהידרוקסיבנזואית' WHERE health_concerns = 'Generally safe, trihydroxybenzoic acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, טריפפטיד' WHERE health_concerns = 'Generally safe, tripeptide';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, טריטרפן' WHERE health_concerns = 'Generally safe, triterpene';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, חומצה ולריאנית' WHERE health_concerns = 'Generally safe, valerenic acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, נגזרת ויטמין C' WHERE health_concerns = 'Generally safe, vitamin C derivative';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, ויטמין E' WHERE health_concerns = 'Generally safe, vitamin E';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל, זאקסנטין' WHERE health_concerns = 'Generally safe, zeaxanthin';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; בחילה קלה במינונים גבוהים; סמקה נדירה' WHERE health_concerns = 'Generally safe; Mild nausea at high doses; Flushing is rare';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; סיכון מוגבר לסרטן ערמונית שנוי במחלוקת (מחקרי מינון גבוה); מצוקת מערכת עיכול' WHERE health_concerns = 'Generally safe; Possible increased prostate cancer risk debated (high-dose studies); GI distress';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; חומצת אמינו' WHERE health_concerns = 'Generally safe; amino acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; שימוש כנוגד חומצה' WHERE health_concerns = 'Generally safe; antacid use';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; חומר חוצץ נפוץ' WHERE health_concerns = 'Generally safe; common buffering agent';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; הוסר מהרשימה מסיבות טכניות' WHERE health_concerns = 'Generally safe; delisted for technical reasons';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; חומצת אמינו חיונית' WHERE health_concerns = 'Generally safe; essential amino acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; מינונים גבוהים עלולים להיות רעילים לכליות' WHERE health_concerns = 'Generally safe; high doses may be nephrotoxic';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; עלול לגרום אלרגיות עור' WHERE health_concerns = 'Generally safe; may cause skin allergies';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; עלול להפחית ספיגת תרופות' WHERE health_concerns = 'Generally safe; may reduce drug absorption';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; חומצת פרי טבעית' WHERE health_concerns = 'Generally safe; natural fruit acid';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; מקור אשלגן' WHERE health_concerns = 'Generally safe; potassium source';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; אלרגיות נדירות; חשש זיהום אתילן אוקסיד' WHERE health_concerns = 'Generally safe; rare allergies; ethylene oxide contamination concern';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; נפיחות נדירה; חשש NEC בפגים' WHERE health_concerns = 'Generally safe; rare bloating; NEC concern in premature infants';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; מחמצן איטי' WHERE health_concerns = 'Generally safe; slow acidifier';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; אנשים רגישים לסולפיטים צריכים להיזהר' WHERE health_concerns = 'Generally safe; sulfite-sensitive individuals should be cautious';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; רעילות במינונים גבוהים מאוד' WHERE health_concerns = 'Generally safe; toxicity at very high doses';
UPDATE food_additives SET health_concerns_he = 'בטוח בדרך כלל; משמש לטיפול באבני כליות' WHERE health_concerns = 'Generally safe; used to treat kidney stones';
UPDATE food_additives SET health_concerns_he = 'בטוח מאוד בדרך כלל; אבני כליות במינונים גבוהים ביותר (תיאורטי)' WHERE health_concerns = 'Generally very safe; Kidney stones at extremely high doses (theoretical)';
UPDATE food_additives SET health_concerns_he = 'בטוח מאוד בדרך כלל; הפרעת מערכת עיכול קלה במינונים גבוהים; נדודי שינה אפשריים; עלול להפחית יעילות וורפרין' WHERE health_concerns = 'Generally very safe; Mild GI upset at high doses; Possible insomnia; May reduce warfarin efficacy';
UPDATE food_additives SET health_concerns_he = 'נסבל היטב בדרך כלל; ישנוניות קלה אפשרית' WHERE health_concerns = 'Generally well-tolerated; mild drowsiness possible';
UPDATE food_additives SET health_concerns_he = 'נסבל היטב בדרך כלל; לא דווח על תופעות לוואי משמעותיות' WHERE health_concerns = 'Generally well-tolerated; no significant adverse effects reported';
UPDATE food_additives SET health_concerns_he = 'נסבל היטב בדרך כלל; אי נוחות במערכת העיכול נדירה במינונים גבוהים מאוד' WHERE health_concerns = 'Generally well-tolerated; rare GI discomfort at very high doses';
UPDATE food_additives SET health_concerns_he = 'נסבל היטב בדרך כלל; חששות כליות/כבד נדירים במינונים גבוהים' WHERE health_concerns = 'Generally well-tolerated; rare kidney/liver concerns at high doses';
UPDATE food_additives SET health_concerns_he = 'נסבל היטב בדרך כלל; עקצוץ, סמקה' WHERE health_concerns = 'Generally well-tolerated; tingling, flushing';
UPDATE food_additives SET health_concerns_he = 'הצהרת תיוג כללית שמשמעותה צבעים מלאכותיים או טבעיים נוספו.' WHERE health_concerns = 'Generic label declaration meaning artificial or natural colors added.';
UPDATE food_additives SET health_concerns_he = 'מונח כללי לצבעים סינתטיים FD&C או אחרים.' WHERE health_concerns = 'Generic term for FD&C or other synthetic colors.';
UPDATE food_additives SET health_concerns_he = 'מונח כללי לטעם מוסף. יכול להיות טבעי או מלאכותי.' WHERE health_concerns = 'Generic term for added flavor. Could be natural or artificial.';
UPDATE food_additives SET health_concerns_he = 'רעילות גנטית בריכוזים גבוהים; בטוח בדרך כלל ב-ADI; פוטנציאל אנטי-דלקתי' WHERE health_concerns = 'Genotoxicity at high concentrations; generally safe at ADI; anti-inflammatory potential';
UPDATE food_additives SET health_concerns_he = 'רעילות גנטית; סרטנות (מספר איברים במכרסמים)' WHERE health_concerns = 'Genotoxicity; carcinogenicity (multiple organs in rodents)';
UPDATE food_additives SET health_concerns_he = 'רעילות גנטית; סרטנות (דרך מטבוליט גליצידול)' WHERE health_concerns = 'Genotoxicity; carcinogenicity (via glycidol metabolite)';
UPDATE food_additives SET health_concerns_he = 'רעילות גנטית; פעילות אסטרוגנית' WHERE health_concerns = 'Genotoxicity; estrogenic activity';
UPDATE food_additives SET health_concerns_he = 'רעילות גנטית; פעילות אסטרוגנית; רעילות תאית' WHERE health_concerns = 'Genotoxicity; estrogenic activity; cytotoxicity';
UPDATE food_additives SET health_concerns_he = 'רעילות גנטית; חשש לסרטנות (פרקציית MOAH בעלת 3+ טבעות)' WHERE health_concerns = 'Genotoxicity; potential carcinogenicity (3+ ring MOAH fraction)';
UPDATE food_additives SET health_concerns_he = 'סירופ גלוקוז מהידרוליזה של עמילן תירס. אינדקס גליקמי גבוה.' WHERE health_concerns = 'Glucose syrup from corn starch hydrolysis. High glycemic index.';
UPDATE food_additives SET health_concerns_he = 'קמח ללא גלוטן. נפוץ במטבח האסיאתי ובמוצרים ללא גלוטן.' WHERE health_concerns = 'Gluten-free flour. Common in Asian cuisine and GF products.';
UPDATE food_additives SET health_concerns_he = 'מעבה ללא גלוטן. נפוץ במזונות מעובדים.' WHERE health_concerns = 'Gluten-free thickener. Common in processed foods.';
UPDATE food_additives SET health_concerns_he = 'חיטה טחונה. מכיל גלוטן. אלרגן מרכזי (צליאק/אלרגיה לחיטה).' WHERE health_concerns = 'Ground wheat. Contains gluten. Major allergen (celiac/wheat allergy).';
UPDATE food_additives SET health_concerns_he = 'עשב. עשיר בוויטמין K. קישוט נפוץ.' WHERE health_concerns = 'Herb. Rich in vitamin K. Common garnish.';
UPDATE food_additives SET health_concerns_he = 'פרי בריא; עשיר בסיבים וויטמינים' WHERE health_concerns = 'Healthy fruit; rich in fiber and vitamins';
UPDATE food_additives SET health_concerns_he = 'חלבון חיטה מבודד. אלרגן מרכזי לצליאק.' WHERE health_concerns = 'Isolated wheat protein. Major allergen for celiac disease.';
UPDATE food_additives SET health_concerns_he = 'מיץ עגבניות. עשיר בליקופן.' WHERE health_concerns = 'Juice from tomatoes. Rich in lycopene.';
UPDATE food_additives SET health_concerns_he = 'ירק עלים. עשיר באוקסלטים, ברזל, ויטמין K.' WHERE health_concerns = 'Leafy green. High in oxalates, iron, vitamin K.';
UPDATE food_additives SET health_concerns_he = 'עשן נוזלי. מכיל PAHs ברמות נמוכות.' WHERE health_concerns = 'Liquid smoke. Contains PAHs at low levels.';
UPDATE food_additives SET health_concerns_he = 'אלרגן מרכזי (סיכון אנפילקסיס). טכנית קטנית. עשיר בחלבון ושומן.' WHERE health_concerns = 'Major allergen (anaphylaxis risk). Legume technically. High in protein, fat.';
UPDATE food_additives SET health_concerns_he = 'אלרגן מרכזי. מקור חלבון מלא. מכיל לציטין.' WHERE health_concerns = 'Major allergen. Complete protein source. Contains lecithin.';
UPDATE food_additives SET health_concerns_he = 'אלרגן מרכזי. מכיל איזופלבונים (פיטואסטרוגנים). חלבון מלא.' WHERE health_concerns = 'Major allergen. Contains isoflavones (phytoestrogens). Complete protein.';
UPDATE food_additives SET health_concerns_he = 'חלב ללא שומן. אותו חלבון/סידן כמו חלב מלא.' WHERE health_concerns = 'Milk with fat removed. Same protein/calcium as whole milk.';
UPDATE food_additives SET health_concerns_he = 'התבלין הנסחר ביותר. מכיל פיפרין (משפר זמינות ביולוגית).' WHERE health_concerns = 'Most traded spice. Contains piperine (bioavailability enhancer).';
UPDATE food_additives SET health_concerns_he = 'מחמצן טבעי. עשיר בוויטמין C.' WHERE health_concerns = 'Natural acidulant. Rich in vitamin C.';
UPDATE food_additives SET health_concerns_he = 'פרי הדר טבעי; עשיר בוויטמין C' WHERE health_concerns = 'Natural citrus fruit; rich in vitamin C';
UPDATE food_additives SET health_concerns_he = 'צבע מזון טבעי מפפריקה; בטוח בדרך כלל' WHERE health_concerns = 'Natural food coloring from paprika; generally safe';
UPDATE food_additives SET health_concerns_he = 'עמילן טבעי מקסווה; בטוח בדרך כלל' WHERE health_concerns = 'Natural starch from cassava; generally safe';
UPDATE food_additives SET health_concerns_he = 'ממתיק טבעי מקנה סוכר/סלק. 4 קלוריות/גרם. WHO ממליץ <25 גרם/יום סוכרים מוספים.' WHERE health_concerns = 'Natural sweetener from sugarcane/beet. 4 kcal/g. WHO recommends <25g/day added sugars.';
UPDATE food_additives SET health_concerns_he = 'מקור טבעי לוויטמין C, בטוח' WHERE health_concerns = 'Natural vitamin C source, safe';
UPDATE food_additives SET health_concerns_he = 'סוכר מאושר אורגנית. זהה תזונתית לרגיל.' WHERE health_concerns = 'Organic-certified sugar. Same nutritionally as conventional.';
UPDATE food_additives SET health_concerns_he = 'קקאו מעובד. מכיל פלבנולים, תיאוברומין. תכונות נוגדות חמצון.' WHERE health_concerns = 'Processed cacao. Contains flavanols, theobromine. Antioxidant properties.';
UPDATE food_additives SET health_concerns_he = 'מסת קקאו טהורה. לא אלכוהולי למרות השם. בסיס לשוקולד.' WHERE health_concerns = 'Pure cocoa mass. Not alcoholic despite name. Base for chocolate.';
UPDATE food_additives SET health_concerns_he = 'בשר אדום. חלבון מלא. מכיל ברזל המי.' WHERE health_concerns = 'Red meat. Complete protein. Contains heme iron.';
UPDATE food_additives SET health_concerns_he = 'שמן בוטנים מזוקק בדרך כלל בטוח לאלרגיים לבוטנים (חלבונים הוסרו). גולמי לא.' WHERE health_concerns = 'Refined peanut oil generally safe for peanut-allergic (proteins removed). Raw is not.';
UPDATE food_additives SET health_concerns_he = 'תסמינים דמויי שיגדון (חומצת שתן מוגברת); דלדול נחושת; מצוקת מערכת עיכול; שלשול' WHERE health_concerns = 'Gout-like symptoms (elevated uric acid); Copper depletion; GI distress; Diarrhea';
UPDATE food_additives SET health_concerns_he = 'תכולת פורין; להימנע עם שיגדון' WHERE health_concerns = 'Purine content; avoid with gout';
UPDATE food_additives SET health_concerns_he = 'תכולת פורין; להימנע עם שיגדון או היפראוריצמיה' WHERE health_concerns = 'Purine content; avoid with gout or hyperuricemia';
UPDATE food_additives SET health_concerns_he = 'תכולת פורין; סיכון גבוה לחומצת שתן בחולי שיגדון' WHERE health_concerns = 'Purine content; high uric acid risk for gout patients';
UPDATE food_additives SET health_concerns_he = 'שיבוש מיקרוביום המעי במחקרי בעלי חיים ובני אדם; עלול לקדם דלקת' WHERE health_concerns = 'Gut microbiome disruption in animal and human studies; may promote inflammation';
UPDATE food_additives SET health_concerns_he = 'דלקת מעי; משנה מיקרוביוטת המעי; מגביר חדירות' WHERE health_concerns = 'Intestinal inflammation; alters gut microbiota; increases permeability';
UPDATE food_additives SET health_concerns_he = 'דלקת מעי; תסמונת מטבולית בבעלי חיים; דיסביוזיס מעי' WHERE health_concerns = 'Intestinal inflammation; metabolic syndrome in animals; gut dysbiosis';
UPDATE food_additives SET health_concerns_he = 'מעכב חיידקי מעי; בעבר קשור לסרטן שלפוחית; מכון ויצמן: אי סבילות לגלוקוז' WHERE health_concerns = 'Inhibits gut bacteria; previously linked to bladder cancer; Weizmann: glucose intolerance';
UPDATE food_additives SET health_concerns_he = 'מעכב תקשורת חיידקי מעי; אוניברסיטת בן גוריון: משבש מיקרוביום; NutriNet-Sante: סיכון לסרטן' WHERE health_concerns = 'Inhibits gut bacterial communication; BGU: disrupts microbiome; NutriNet-Sante: cancer risk';
UPDATE food_additives SET health_concerns_he = 'עלול לקדם חדירת חיידקים לשכבת הריר; עליית LPS במחקרי בעלי חיים' WHERE health_concerns = 'May promote bacterial encroachment into mucus layer; increased LPS in animal studies';
UPDATE food_additives SET health_concerns_he = 'הפרעה מטבולית ודיסביוזיס מעי במחקרי בעלי חיים; הערכה מחדש של EFSA מתבצעת' WHERE health_concerns = 'Metabolic disorder and gut dysbiosis in animal studies; EFSA re-evaluation ongoing';
UPDATE food_additives SET health_concerns_he = 'גינקומסטיה, נזק לכבד, סיכונים קרדיווסקולריים, שיבוש הורמונלי' WHERE health_concerns = 'Gynecomastia, liver damage, cardiovascular risks, hormonal disruption';
UPDATE food_additives SET health_concerns_he = 'כאב ראש, סחרחורת, אי נוחות במערכת העיכול' WHERE health_concerns = 'Headache, dizziness, GI discomfort';
UPDATE food_additives SET health_concerns_he = 'כאב ראש, סחרחורת, אי נוחות במערכת העיכול; ריח גוף דגי' WHERE health_concerns = 'Headache, dizziness, GI discomfort; fishy body odor';
UPDATE food_additives SET health_concerns_he = 'כאב ראש, מתח שרירים, נדודי שינה; חששות טרטוגניים במחקרי בעלי חיים' WHERE health_concerns = 'Headache, muscle tension, insomnia; teratogenic concerns in animal studies';
UPDATE food_additives SET health_concerns_he = 'כאב ראש, הפרעות שינה, הפרעות מערכת עיכול; השפעות אסטרוגניות אפשריות' WHERE health_concerns = 'Headache, sleep disturbances, GI disorders; estrogenic effects possible';
UPDATE food_additives SET health_concerns_he = 'כאב ראש, הזעה; ממריץ מתון יותר מקפאין' WHERE health_concerns = 'Headache, sweating; milder stimulant than caffeine';
UPDATE food_additives SET health_concerns_he = 'כאב ראש; נזק לכבד; מומים מולדים; אובדן עצם; קילוף עור' WHERE health_concerns = 'Headache; Liver damage; Birth defects; Bone loss; Skin desquamation';
UPDATE food_additives SET health_concerns_he = 'ממתיק חלבוני יציב בחום; נתוני בטיחות מוגבלים' WHERE health_concerns = 'Heat stable protein sweetener; limited safety data';
UPDATE food_additives SET health_concerns_he = 'חלבון מתוק יציב בחום; ממתיק דור הבא פוטנציאלי' WHERE health_concerns = 'Heat-stable sweet protein; potential next-gen sweetener';
UPDATE food_additives SET health_concerns_he = 'רעילות המטולוגית; רעילות חיסונית; רעילות עורית (אלוקיה רעילה תזונתית); עיכוב גדילה' WHERE health_concerns = 'Hematotoxicity; immunotoxicity; dermatotoxicity (alimentary toxic aleukia); growth retardation';
UPDATE food_additives SET health_concerns_he = 'אנגיוסרקומה כבדית; רעילות כבדית; סרטנות' WHERE health_concerns = 'Hepatic angiosarcoma; hepatotoxicity; carcinogenicity';
UPDATE food_additives SET health_concerns_he = 'קרצינומה כבדית; אפלטוקסיקוזיס חריפה; דיכוי חיסוני; פגיעה בגדילה (ילדים)' WHERE health_concerns = 'Hepatocellular carcinoma; acute aflatoxicosis; immunosuppression; growth impairment (children)';
UPDATE food_additives SET health_concerns_he = 'קרצינומה כבדית; דיכוי חיסוני; מוטגניות' WHERE health_concerns = 'Hepatocellular carcinoma; immunosuppression; mutagenicity';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית (מחלה ונו-אוקלוסיבית); רעילות גנטית; סרטנות' WHERE health_concerns = 'Hepatotoxicity (veno-occlusive disease); genotoxicity; carcinogenicity';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית (מחלה ונו-אוקלוסיבית); רעילות גנטית; סרטנות (כבד)' WHERE health_concerns = 'Hepatotoxicity (veno-occlusive disease); genotoxicity; carcinogenicity (liver)';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית במינונים גבוהים מאוד (>3 גרם/יום); בחילה' WHERE health_concerns = 'Hepatotoxicity at very high doses (>3g/day); Nausea';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית, היפרויטמינוזיס A במינונים כרוניים גבוהים; טרטוגני' WHERE health_concerns = 'Hepatotoxicity, hypervitaminosis A at chronic high doses; teratogenic';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית; סרטנות (כבד, כליה, ריאה); רעילות גנטית' WHERE health_concerns = 'Hepatotoxicity; carcinogenicity (liver, kidney, lung); genotoxicity';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית; רעילות חיסונית; הצטברות ביולוגית' WHERE health_concerns = 'Hepatotoxicity; immunotoxicity; bioaccumulation';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית; רעילות חיסונית; מחלת תריס; סרטן כליה; סרטן אשכים' WHERE health_concerns = 'Hepatotoxicity; immunotoxicity; thyroid disease; kidney cancer; testicular cancer';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית; רעילות כלייתית; סרטן כבד בבעלי חיים' WHERE health_concerns = 'Hepatotoxicity; nephrotoxicity; liver cancer in animals';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית; רעילות כלייתית; סיכון למומי צינור עצבי' WHERE health_concerns = 'Hepatotoxicity; nephrotoxicity; neural tube defect risk';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית; רעילות כלייתית; שיבוש תריס; חשש לסרטנות' WHERE health_concerns = 'Hepatotoxicity; nephrotoxicity; thyroid disruption; potential carcinogenicity';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית; חשש לסרטנות (מטבוליט בתיווך סולפוטרנספראז)' WHERE health_concerns = 'Hepatotoxicity; potential carcinogenicity (sulfotransferase-mediated metabolite)';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית; חשש לסרטנות כבדית' WHERE health_concerns = 'Hepatotoxicity; potential liver carcinogenicity';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית; שיבוש תריס; חשש לסרטנות; שיבוש אנדוקריני' WHERE health_concerns = 'Hepatotoxicity; thyroid disruption; potential carcinogenicity; endocrine disruption';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי גבוה (95-136); עליות חדות בסוכר הדם; מדכא חיידקי מעי מועילים' WHERE health_concerns = 'High GI (95-136); blood sugar spikes; suppresses beneficial gut bacteria';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי גבוה; חששות ארסן מאורז; ללא פרוקטוז' WHERE health_concerns = 'High GI; arsenic concerns from rice; fructose-free';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי גבוה; תורם להשמנה; לא זהה ל-HFCS (פחות פרוקטוז)' WHERE health_concerns = 'High GI; contributes to obesity; not same as HFCS (lower fructose)';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי גבוה; משמש בעיקר כחומר מרקם ולא כממתיק' WHERE health_concerns = 'High GI; primarily used as texturizer rather than sweetener';
UPDATE food_additives SET health_concerns_he = 'סיבים גבוהים; אינדקס גליקמי נמוך; עשיר במינרלים; מזון ילידי מסורתי' WHERE health_concerns = 'High fiber; low GI; rich in minerals; traditional indigenous food';
UPDATE food_additives SET health_concerns_he = 'תכולת סוכר גבוהה; אי נוחות במערכת העיכול' WHERE health_concerns = 'High sugar content; GI discomfort';
UPDATE food_additives SET health_concerns_he = 'תוספים במינון גבוה קשורים לסרטן ריאות במעשנים; בטוח במזון' WHERE health_concerns = 'High-dose supplements linked to lung cancer in smokers; safe in food';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי גבוה ביותר בין סוכרי הכהל (35); משלשל >25-30 גרם/יום; המרקם הקרוב ביותר לסוכרוז' WHERE health_concerns = 'Highest GI among sugar alcohols (35); laxative >25-30g/day; closest texture to sucrose';
UPDATE food_additives SET health_concerns_he = 'היפראקטיביות; נזק ל-DNA; מכיל בנזידין (מסרטן) ברמות נמוכות' WHERE health_concerns = 'Hyperactivity; DNA damage; contains benzidine (carcinogen) at low levels';
UPDATE food_additives SET health_concerns_he = 'היפראקטיביות; גידולי כליות/אדרנל; תביעת M&M ישראלית 2014 (פי 5 מהמותר)' WHERE health_concerns = 'Hyperactivity; kidney/adrenal tumors; 2014 Israeli M&M lawsuit (5x permitted levels)';
UPDATE food_additives SET health_concerns_he = 'היפרקלצמיה; נזק לכליות; הסתיידות רקמות רכות; בחילה; הפרעות קצב' WHERE health_concerns = 'Hypercalcemia; Kidney damage; Soft tissue calcification; Nausea; Arrhythmias';
UPDATE food_additives SET health_concerns_he = 'היפרקלצמיה; אבני כליות; עצירות; פגיעה בספיגת ברזל/אבץ; הסתיידות כלי דם' WHERE health_concerns = 'Hypercalcemia; Kidney stones; Constipation; Impaired iron/zinc absorption; Vascular calcification';
UPDATE food_additives SET health_concerns_he = 'היפרכלורמיה; בדרך כלל קשור לצריכת נתרן מופרזת; חמצת מטבולית' WHERE health_concerns = 'Hyperchloremia; Usually tied to excess sodium intake; Metabolic acidosis';
UPDATE food_additives SET health_concerns_he = 'היפרקלמיה בעודף; אי נוחות במערכת העיכול' WHERE health_concerns = 'Hyperkalemia at excess; GI discomfort';
UPDATE food_additives SET health_concerns_he = 'היפרקלמיה; דום לב; בחילה; עקצוץ; מסוכן עם אי ספיקת כליות' WHERE health_concerns = 'Hyperkalemia; Cardiac arrest; Nausea; Tingling; Dangerous with renal impairment';
UPDATE food_additives SET health_concerns_he = 'היפרפוספטמיה; הסתיידות רקמות; פגיעה במטבוליזם סידן; היפרפאראתירואידיזם משני' WHERE health_concerns = 'Hyperphosphatemia; Calcification of tissues; Impaired calcium metabolism; Secondary hyperparathyroidism';
UPDATE food_additives SET health_concerns_he = 'סיכון ליתר לחץ דם במינונים גבוהים (>100 מ"ג חומצה גליצירהיזית/יום); היפוקלמיה' WHERE health_concerns = 'Hypertension risk at high doses (>100mg glycyrrhizic acid/day); hypokalemia';
UPDATE food_additives SET health_concerns_he = 'יתר לחץ דם עם עודף כרוני; בצקת' WHERE health_concerns = 'Hypertension with chronic excess; edema';
UPDATE food_additives SET health_concerns_he = 'יתר לחץ דם, טכיקרדיה, שבץ, דום לב, מוות' WHERE health_concerns = 'Hypertension, tachycardia, stroke, cardiac arrest, death';
UPDATE food_additives SET health_concerns_he = 'יתר לחץ דם, טכיקרדיה, שבץ, התקף לב, מוות' WHERE health_concerns = 'Hypertension, tachycardia, stroke, heart attack, death';
UPDATE food_additives SET health_concerns_he = 'יתר לחץ דם; בצקת; סיכון לשבץ; נזק לכליות; סיכון לסרטן קיבה' WHERE health_concerns = 'Hypertension; Edema; Stroke risk; Kidney damage; Stomach cancer risk';
UPDATE food_additives SET health_concerns_he = 'משבר יתר לחץ דם (במיוחד עם תרופות מעכבות MAO); כאב ראש; מיגרנה' WHERE health_concerns = 'Hypertensive crisis (especially with MAO inhibitor drugs); headache; migraine';
UPDATE food_additives SET health_concerns_he = 'יתר פעילות תריס; הגדלת כבד; עלול להתאדות מאריזה למזון' WHERE health_concerns = 'Hyperthyroidism; liver enlargement; may vaporize from packaging into food';
UPDATE food_additives SET health_concerns_he = 'היפוגליקמיה, כאב ראש, בצקת, כאבי מפרקים' WHERE health_concerns = 'Hypoglycemia, headache, edema, joint pain';
UPDATE food_additives SET health_concerns_he = 'IARC 2B מאז 1999; סרטן כליה; אסור באיחוד האירופי, בריטניה, קנדה, ברזיל' WHERE health_concerns = 'IARC 2B since 1999; kidney cancer; banned in EU, UK, Canada, Brazil';
UPDATE food_additives SET health_concerns_he = 'IARC מסרטן אפשרי; NTP מסרטן צפוי סבירה; מסרטן בקליפורניה מאז 1990' WHERE health_concerns = 'IARC possible carcinogen; NTP reasonably anticipated carcinogen; California carcinogen since 1990';
UPDATE food_additives SET health_concerns_he = 'דווח על תכונות ממריצות חיסון; נתוני בטיחות מוגבלים' WHERE health_concerns = 'Immunostimulatory properties reported; limited safety data';
UPDATE food_additives SET health_concerns_he = 'רעילות חיסונית; השפעות התפתחותיות; שיבוש תריס' WHERE health_concerns = 'Immunotoxicity; developmental effects; thyroid disruption';
UPDATE food_additives SET health_concerns_he = 'רעילות חיסונית; רעילות המטולוגית; רעילות מערכת עיכול (רעיל יותר מ-DON בחלק מהמודלים)' WHERE health_concerns = 'Immunotoxicity; hematotoxicity; GI toxicity (more toxic than DON in some models)';
UPDATE food_additives SET health_concerns_he = 'רעילות חיסונית; רעילות כבדית; כולסטרול מוגבר; שיבוש תריס; השפעות התפתחותיות; חשש לסרטנות' WHERE health_concerns = 'Immunotoxicity; hepatotoxicity; elevated cholesterol; thyroid disruption; developmental effects; potential carcinogenicity';
UPDATE food_additives SET health_concerns_he = 'רעילות חיסונית; שיבוש תריס; רעילות כבדית' WHERE health_concerns = 'Immunotoxicity; thyroid disruption; hepatotoxicity';
UPDATE food_additives SET health_concerns_he = 'סיכון מוגבר לדימום; שבץ דימומי; עלול להגביר תמותה מכל סיבה במינונים גבוהים מאוד' WHERE health_concerns = 'Increased bleeding risk; Hemorrhagic stroke; May increase all-cause mortality at very high doses';
UPDATE food_additives SET health_concerns_he = 'עלייה בדופק, לחץ דם (במיוחד עם קפאין)' WHERE health_concerns = 'Increased heart rate, blood pressure (especially with caffeine)';
UPDATE food_additives SET health_concerns_he = 'מעכב אנזים סוכראז; מפחית ספיגת סוכר בצריכה משותפת; פוטנציאל אנטי-סוכרתי' WHERE health_concerns = 'Inhibits sucrase enzyme; reduces sugar absorption when co-consumed; anti-diabetic potential';
UPDATE food_additives SET health_concerns_he = 'נדודי שינה, חרדה, טכיקרדיה, הפרעת מערכת עיכול, רעידות, תלות' WHERE health_concerns = 'Insomnia, anxiety, tachycardia, GI upset, tremors, dependence';
UPDATE food_additives SET health_concerns_he = 'נדודי שינה, אי שקט, אי נוחות במערכת העיכול; סיכון זיהום כספית במוצרים באיכות נמוכה' WHERE health_concerns = 'Insomnia, restlessness, GI discomfort; mercury contamination risk in low-quality products';
UPDATE food_additives SET health_concerns_he = 'מגרה; בטוח בדרך כלל ברמות מזון' WHERE health_concerns = 'Irritant; generally safe at food levels';
UPDATE food_additives SET health_concerns_he = 'נזק לכליות (דוחות מקרה עם פיקולינט במינונים גבוהים מאוד); Cr(III) בטוח בדרך כלל; Cr(VI) מסרטן (לא צורת תוסף)' WHERE health_concerns = 'Kidney damage (case reports with picolinate at very high doses); Cr(III) generally safe; Cr(VI) is carcinogenic (not a supplement form)';
UPDATE food_additives SET health_concerns_he = 'השפעות כליות במינונים גבוהים; ADI נמשך בשל שימוש נמוך מאוד/בודד' WHERE health_concerns = 'Kidney effects at high doses; ADI withdrawn due to very low/single use';
UPDATE food_additives SET health_concerns_he = 'אבני כליות; אי ספיקת כליות; סרטן שלפוחית (עם חומצה ציאנורית); רעילות רבייתית במינונים גבוהים' WHERE health_concerns = 'Kidney stones; renal failure; bladder cancer (with cyanuric acid); reproductive toxicity at high doses';
UPDATE food_additives SET health_concerns_he = 'אי סבילות ללקטוז נפוצה; ניתן לתסיסה; מקדם עששת פחות מסוכרוז' WHERE health_concerns = 'Lactose intolerance common; fermentable; promotes dental caries less than sucrose';
UPDATE food_additives SET health_concerns_he = 'משלשל; בטוח בדרך כלל ברמות מזון' WHERE health_concerns = 'Laxative; generally safe at food levels';
UPDATE food_additives SET health_concerns_he = 'פחות מצוקת מערכת עיכול ממלטודקסטרין; ריקון קיבה מהיר' WHERE health_concerns = 'Less GI distress than maltodextrin; fast gastric emptying';
UPDATE food_additives SET health_concerns_he = 'פחות גירוי מערכת עיכול מחומצת אסקורבית; אותו UL חל' WHERE health_concerns = 'Less GI irritation than ascorbic acid; same UL applies';
UPDATE food_additives SET health_concerns_he = 'לוקמיה (AML); רעילות מח עצם; סרטנות' WHERE health_concerns = 'Leukemia (AML); bone marrow toxicity; carcinogenicity';
UPDATE food_additives SET health_concerns_he = 'טעם לוואי דמוי ליקריץ; שימוש מסחרי מוגבל; מצמח פרילה' WHERE health_concerns = 'Licorice-like aftertaste; limited commercial use; from perilla plant';
UPDATE food_additives SET health_concerns_he = 'נתונים מוגבלים; בטוח בדרך כלל במינונים שנחקרו' WHERE health_concerns = 'Limited data; Generally safe in studied doses';
UPDATE food_additives SET health_concerns_he = 'נתונים מוגבלים; גירוי קרדיווסקולרי אפשרי' WHERE health_concerns = 'Limited data; potential cardiovascular stimulation';
UPDATE food_additives SET health_concerns_he = 'נתוני טוקסיקולוגיה עדכניים מוגבלים; צריכה גבוהה אפשרית בילדים' WHERE health_concerns = 'Limited recent toxicology data; potential high child intake';
UPDATE food_additives SET health_concerns_he = 'חששות בטיחות מוגבלים; לא הוערך על ידי EFSA (אסור באיחוד האירופי)' WHERE health_concerns = 'Limited safety concerns; not evaluated by EFSA (banned in EU)';
UPDATE food_additives SET health_concerns_he = 'שימוש מוגבל כממתיק; סיווג סוכר נדיר' WHERE health_concerns = 'Limited use as sweetener; rare sugar classification';
UPDATE food_additives SET health_concerns_he = 'קשור להשמנה ותסמונת מטבולית; השפעה מטבולית דומה לסוכרוז' WHERE health_concerns = 'Linked to obesity and metabolic syndrome; similar metabolic impact to sucrose';
UPDATE food_additives SET health_concerns_he = 'השפעות כבד וכליות במינונים גבוהים; פחות רעילות רבייתית מ-DEHP' WHERE health_concerns = 'Liver and kidney effects at high doses; less reproductive toxicity than DEHP';
UPDATE food_additives SET health_concerns_he = 'רעילות כבד וכליות; מומי צינור עצבי (בעלי חיים); קשר לסרטן הוושט; לויקואנצפלומלציה בסוסים' WHERE health_concerns = 'Liver and kidney toxicity; neural tube defects (animals); esophageal cancer association; equine leukoencephalomalacia';
UPDATE food_additives SET health_concerns_he = 'רעילות כבדית, סיכונים קרדיווסקולריים, דיכוי הורמונלי, השפעות ארוכות טווח לא ידועות' WHERE health_concerns = 'Liver toxicity, cardiovascular risks, hormonal suppression, unknown long-term effects';
UPDATE food_additives SET health_concerns_he = 'צואה רכה במינונים גבוהים' WHERE health_concerns = 'Loose stools at high doses';
UPDATE food_additives SET health_concerns_he = 'חלופה דלת נתרן לנתרן סכרין' WHERE health_concerns = 'Low-sodium alternative to sodium saccharin';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי נמוך מסוכר; עשיר באשלגן, מגנזיום; עדיין קלורי' WHERE health_concerns = 'Lower GI than sugar; rich in potassium, magnesium; still caloric';
UPDATE food_additives SET health_concerns_he = 'אינדקס גליקמי נמוך מסוכר לבן; מכיל מינרלים; עדיין קלורי' WHERE health_concerns = 'Lower GI than white sugar; contains minerals; still caloric';
UPDATE food_additives SET health_concerns_he = 'סיכון סמקה נמוך יותר; ראה ויטמין B3' WHERE health_concerns = 'Lower flushing risk; Otherwise see Vitamin B3';
UPDATE food_additives SET health_concerns_he = 'סמן לסיכון זיהום אלקלואיד ארגוט' WHERE health_concerns = 'Marker for ergot alkaloid contamination risk';
UPDATE food_additives SET health_concerns_he = 'עלול לגרום לכאב ראש וסמקה באנשים רגישים במינונים גבוהים' WHERE health_concerns = 'May cause headache and flushing in sensitive individuals at high doses';
UPDATE food_additives SET health_concerns_he = 'עלול להכיל PAHs מסרטנים; חששות EFSA; רעילות תאית במחקרי תאים' WHERE health_concerns = 'May contain carcinogenic PAHs; EFSA concerns; cytotoxicity in cell studies';
UPDATE food_additives SET health_concerns_he = 'עלול להכיל שומני טרנס; עשיר בשומן רווי' WHERE health_concerns = 'May contain trans fats; high in saturated fat';
UPDATE food_additives SET health_concerns_he = 'עלול להוריד סוכר בדם; השפעות אנטי-פוריות במחקרי בעלי חיים' WHERE health_concerns = 'May lower blood sugar; anti-fertility effects in animal studies';
UPDATE food_additives SET health_concerns_he = 'דומה מטבולית לסוכר למרות שיווק ''טבעי''; שומר על חלק מהתזונה' WHERE health_concerns = 'Metabolically similar to sugar despite ''natural'' marketing; retains some nutrients';
UPDATE food_additives SET health_concerns_he = 'אי נוחות קלה במערכת העיכול' WHERE health_concerns = 'Mild GI discomfort';
UPDATE food_additives SET health_concerns_he = 'עשיר במינרלים אך עדיין סוכר קלורי; מקדם עששת' WHERE health_concerns = 'Mineral-rich but still caloric sugar; promotes dental caries';
UPDATE food_additives SET health_concerns_he = 'מטבוליט משני של אריתריטול; נתונים מוגבלים' WHERE health_concerns = 'Minor metabolite of erythritol; limited data';
UPDATE food_additives SET health_concerns_he = 'סוכר מראה; לא עובר מטבוליזם; יקר מדי לשימוש מסחרי' WHERE health_concerns = 'Mirror sugar; not metabolized; too expensive for commercial use';
UPDATE food_additives SET health_concerns_he = 'גירוי פה/עור; אי נוחות במערכת העיכול אם נבלע בכמויות גדולות' WHERE health_concerns = 'Mouth/skin irritation; GI discomfort if ingested in large amounts';
UPDATE food_additives SET health_concerns_he = 'מוטגניות (אחד המוטגנים החזקים הידועים); חשש לסרטנות' WHERE health_concerns = 'Mutagenicity (one of the most potent mutagens known); potential carcinogenicity';
UPDATE food_additives SET health_concerns_he = 'מוטגניות; סרטנות (כבד, ריאה במכרסמים)' WHERE health_concerns = 'Mutagenicity; carcinogenicity (liver, lung in rodents)';
UPDATE food_additives SET health_concerns_he = 'ליפידוזיס שריר הלב; רעילות לבבית בבעלי חיים; השפעות התפתחותיות אפשריות' WHERE health_concerns = 'Myocardial lipidosis; cardiotoxicity in animals; potential developmental effects';
UPDATE food_additives SET health_concerns_he = 'כעת אלרגן מרכזי (חוק FASTER בארה"ב 2023, באיחוד האירופי כבר ברשימה). עשיר בסידן.' WHERE health_concerns = 'NOW a major allergen (US FASTER Act 2023, EU already listed). Rich in calcium.';
UPDATE food_additives SET health_concerns_he = 'נגזרת חומצת אמינו טבעית; ממתיק דור הבא פוטנציאלי' WHERE health_concerns = 'Natural amino acid derivative; potential next-gen sweetener';
UPDATE food_additives SET health_concerns_he = 'טבעי אך תגובות אלרגיות; אורטיקריה; מעורר IBS' WHERE health_concerns = 'Natural but allergic reactions; urticaria; IBS-triggering';
UPDATE food_additives SET health_concerns_he = 'חומצת אמינו מתוקה טבעית; קלורית; חשובה לסינתזת קולגן' WHERE health_concerns = 'Naturally sweet amino acid; caloric; important for collagen synthesis';
UPDATE food_additives SET health_concerns_he = 'בחילה על קיבה ריקה; נתוני בטיחות מוגבלים מאוד בבני אדם' WHERE health_concerns = 'Nausea on empty stomach; very limited safety data in humans';
UPDATE food_additives SET health_concerns_he = 'בחילה, אי נוחות במערכת העיכול, ישנוניות; סיכון לתסמונת סרוטונין' WHERE health_concerns = 'Nausea, GI discomfort, drowsiness; serotonin syndrome risk';
UPDATE food_additives SET health_concerns_he = 'בחילה, שלשול, הזעה, טשטוש ראייה' WHERE health_concerns = 'Nausea, diarrhea, sweating, blurred vision';
UPDATE food_additives SET health_concerns_he = 'בחילה, הקאה, חוסר נחושת בצריכה כרונית >40 מ"ג/יום' WHERE health_concerns = 'Nausea, vomiting, copper deficiency at chronic >40mg/d';
UPDATE food_additives SET health_concerns_he = 'בחילה, הקאה, כאב ראש; תסמיני עודף דופמין במינונים גבוהים' WHERE health_concerns = 'Nausea, vomiting, headache; dopamine excess symptoms at high doses';
UPDATE food_additives SET health_concerns_he = 'בחילה, הקאה, טינטון, דליריום בריכוזים גבוהים' WHERE health_concerns = 'Nausea, vomiting, tinnitus, delirium at higher concentrations';
UPDATE food_additives SET health_concerns_he = 'בחילה; הקאה; שלשול; סירוב לאכילה; רעילות חיסונית; עיכוב גדילה' WHERE health_concerns = 'Nausea; vomiting; diarrhea; feed refusal; immunotoxicity; growth retardation';
UPDATE food_additives SET health_concerns_he = 'רעילות כלייתית (נזק לצינורית פרוקסימלית); אוסטאופורוזיס; סרטנות (ריאה); רעילות רבייתית' WHERE health_concerns = 'Nephrotoxicity (proximal tubule damage); osteoporosis; carcinogenicity (lung); reproductive toxicity';
UPDATE food_additives SET health_concerns_he = 'רעילות כלייתית בכליות מתפתחות; חשש גבוה ביותר לתינוקות' WHERE health_concerns = 'Nephrotoxicity in developing kidneys; highest concern for infants';
UPDATE food_additives SET health_concerns_he = 'רעילות כלייתית; הצטברות ביולוגית ברקמת כליה' WHERE health_concerns = 'Nephrotoxicity; bioaccumulation in kidney tissue';
UPDATE food_additives SET health_concerns_he = 'רעילות כלייתית; השפעות על עצמות; הצטברות כרונית' WHERE health_concerns = 'Nephrotoxicity; bone effects; chronic accumulation';
UPDATE food_additives SET health_concerns_he = 'רעילות כלייתית; רעילות רבייתית זכרית; חשש לסרטנות' WHERE health_concerns = 'Nephrotoxicity; male reproductive toxicity; potential carcinogenicity';
UPDATE food_additives SET health_concerns_he = 'רעילות כלייתית; אוסטאופורוזיס; מחלת איטאי-איטאי' WHERE health_concerns = 'Nephrotoxicity; osteoporosis; itai-itai disease';
UPDATE food_additives SET health_concerns_he = 'רעילות כלייתית; חשש לסרטנות (כליה); רעילות חיסונית; טרטוגניות' WHERE health_concerns = 'Nephrotoxicity; potential carcinogenicity (kidney); immunotoxicity; teratogenicity';
UPDATE food_additives SET health_concerns_he = 'רעילות כלייתית; רעילות אשכית; חשש לסרטנות' WHERE health_concerns = 'Nephrotoxicity; testicular toxicity; potential carcinogenicity';
UPDATE food_additives SET health_concerns_he = 'רעילות נוירו-התפתחותית (ילדים); רעילות כלייתית; השפעות קרדיווסקולריות; רעילות רבייתית; אנמיה' WHERE health_concerns = 'Neurodevelopmental toxicity (children); nephrotoxicity; cardiovascular effects; reproductive toxicity; anemia';
UPDATE food_additives SET health_concerns_he = 'רעילות נוירו-התפתחותית (עובר, ילדים); פגיעה קוגניטיבית; השפעות קרדיווסקולריות' WHERE health_concerns = 'Neurodevelopmental toxicity (fetus, children); cognitive impairment; cardiovascular effects';
UPDATE food_additives SET health_concerns_he = 'רעילות נוירו-התפתחותית בילדים' WHERE health_concerns = 'Neurodevelopmental toxicity in children';
UPDATE food_additives SET health_concerns_he = 'רעילות נוירו-התפתחותית; השפעות קרדיווסקולריות' WHERE health_concerns = 'Neurodevelopmental toxicity; cardiovascular effects';
UPDATE food_additives SET health_concerns_he = 'רעילות נוירו-התפתחותית; פגיעה בקוגניציה' WHERE health_concerns = 'Neurodevelopmental toxicity; impaired cognition';
UPDATE food_additives SET health_concerns_he = 'רעילות עצבית (עיכוב אצטילכולינסטראז); השפעות נוירו-התפתחותיות (ילדים); שיבוש אנדוקריני' WHERE health_concerns = 'Neurotoxicity (acetylcholinesterase inhibition); neurodevelopmental effects (children); endocrine disruption';
UPDATE food_additives SET health_concerns_he = 'רעילות עצבית (במיוחד התפתחות מוח עובר/ילד); רעילות כלייתית; השפעות קרדיווסקולריות' WHERE health_concerns = 'Neurotoxicity (especially fetal/child brain development); nephrotoxicity; cardiovascular effects';
UPDATE food_additives SET health_concerns_he = 'רעילות עצבית בעודף כרוני (במיוחד בשאיפה)' WHERE health_concerns = 'Neurotoxicity at chronic excess (especially inhaled)';
UPDATE food_additives SET health_concerns_he = 'רעילות עצבית בחשיפה גבוהה; חששות הצטברות אלומיניום' WHERE health_concerns = 'Neurotoxicity at high exposure; aluminium accumulation concerns';
UPDATE food_additives SET health_concerns_he = 'רעילות עצבית בשילוב עם MSG; תגובות אלרגיות' WHERE health_concerns = 'Neurotoxicity when combined with MSG; allergic reactions';
UPDATE food_additives SET health_concerns_he = 'רעילות עצבית; רעילות התפתחותית (ילדים); השפעות קרדיווסקולריות' WHERE health_concerns = 'Neurotoxicity; developmental toxicity (children); cardiovascular effects';
UPDATE food_additives SET health_concerns_he = 'רעילות עצבית; רעילות גנטית; סרטנות (גידולי כליה, רחם, שחלות בבעלי חיים)' WHERE health_concerns = 'Neurotoxicity; genotoxicity; carcinogenicity (kidney, endometrial, ovarian tumors in animals)';
UPDATE food_additives SET health_concerns_he = 'רעילות עצבית; רעילות כלייתית; רעילות כבדית (ב/ליד ADI); תגובות אלרגיות; קוליטיס בנטייה מוקדמת; עיכוב אנזימים' WHERE health_concerns = 'Neurotoxicity; nephrotoxicity; hepatotoxicity (at/near ADI); allergic reactions; colitis in predisposed; enzyme inhibition';
UPDATE food_additives SET health_concerns_he = 'אין שימוש מסחרי כממתיק' WHERE health_concerns = 'No commercial use as sweetener';
UPDATE food_additives SET health_concerns_he = 'אין חששות; סיבים מועילים' WHERE health_concerns = 'No concerns; beneficial fiber';
UPDATE food_additives SET health_concerns_he = 'אין חששות; יצירת ג''ל אלסטי' WHERE health_concerns = 'No concerns; elastic gel formation';
UPDATE food_additives SET health_concerns_he = 'אין חששות; עיבוי סינרגיסטי' WHERE health_concerns = 'No concerns; synergistic thickening';
UPDATE food_additives SET health_concerns_he = 'אין רעילות ידועה; עלול להפריע לבדיקות מעבדה (טרופונין, תריס) במינונים גבוהים' WHERE health_concerns = 'No known toxicity; Can interfere with lab tests (troponin, thyroid) at high doses';
UPDATE food_additives SET health_concerns_he = 'אין רעילות ידועה; בטוח מאוד גם במינונים גבוהים' WHERE health_concerns = 'No known toxicity; Very safe even at high doses';
UPDATE food_additives SET health_concerns_he = 'אין חששות אלרגן מרכזיים' WHERE health_concerns = 'No major allergen concerns';
UPDATE food_additives SET health_concerns_he = 'אין חששות אלרגן מרכזיים; חלופה ללא אלרגנים' WHERE health_concerns = 'No major allergen concerns; allergen-free alternative';
UPDATE food_additives SET health_concerns_he = 'אין חשש בטיחותי (EFSA 2017); שיקול חשיפה לאלומיניום' WHERE health_concerns = 'No safety concern (EFSA 2017); aluminium exposure consideration';
UPDATE food_additives SET health_concerns_he = 'אין חשש בטיחותי (EFSA 2017); מקור GMO אפשרי' WHERE health_concerns = 'No safety concern (EFSA 2017); potential GMO source';
UPDATE food_additives SET health_concerns_he = 'אין חששות משמעותיים ברמות שימוש נוכחיות' WHERE health_concerns = 'No significant concerns at current use levels';
UPDATE food_additives SET health_concerns_he = 'אין חששות משמעותיים ברמות מזון' WHERE health_concerns = 'No significant concerns at food-grade levels';
UPDATE food_additives SET health_concerns_he = 'אין חששות משמעותיים; סיכון BSE מופחת' WHERE health_concerns = 'No significant concerns; BSE risk mitigated';
UPDATE food_additives SET health_concerns_he = 'אין חששות משמעותיים; פוטנציאל אלרגני' WHERE health_concerns = 'No significant concerns; allergen potential';
UPDATE food_additives SET health_concerns_he = 'אין חששות משמעותיים; חלופה ללציטין' WHERE health_concerns = 'No significant concerns; alternative to lecithin';
UPDATE food_additives SET health_concerns_he = 'אין חששות משמעותיים; נפיחות בעודף' WHERE health_concerns = 'No significant concerns; bloating at excess';
UPDATE food_additives SET health_concerns_he = 'אין חששות משמעותיים; סיבים בלתי ניתנים לעיכול' WHERE health_concerns = 'No significant concerns; indigestible fiber';
UPDATE food_additives SET health_concerns_he = 'אין חששות משמעותיים; מרכיב מפתח בבשר צמחי' WHERE health_concerns = 'No significant concerns; key ingredient in plant meats';
UPDATE food_additives SET health_concerns_he = 'אין חששות משמעותיים; השפעות פרה-ביוטיות' WHERE health_concerns = 'No significant concerns; prebiotic effects';
UPDATE food_additives SET health_concerns_he = 'אין חששות משמעותיים; דווח על תכונות פרה-ביוטיות' WHERE health_concerns = 'No significant concerns; prebiotic properties reported';
UPDATE food_additives SET health_concerns_he = 'לא גורם עששת; פוטנציאל פרה-ביוטי; סוכר נדיר' WHERE health_concerns = 'Non-cariogenic; prebiotic potential; rare sugar';
UPDATE food_additives SET health_concerns_he = 'לא ניתן לעיכול; מייצר גזים; פרה-ביוטי' WHERE health_concerns = 'Non-digestible; gas-producing; prebiotic';
UPDATE food_additives SET health_concerns_he = 'לא מאושר למזון; שימוש רפואי בלבד' WHERE health_concerns = 'Not approved for food; medicinal use only';
UPDATE food_additives SET health_concerns_he = 'לא מאושר; מגרה עור אפשרי' WHERE health_concerns = 'Not approved; potential skin irritant';
UPDATE food_additives SET health_concerns_he = 'לא בטוח למזון; חשש לרעילות גנטית' WHERE health_concerns = 'Not safe for food; potential genotoxicity';
UPDATE food_additives SET health_concerns_he = 'ממתיק חלבוני חדשני; אישורים רגולטוריים מוגבלים' WHERE health_concerns = 'Novel protein sweetener; limited regulatory approvals';
UPDATE food_additives SET health_concerns_he = 'NutriNet-Sante: סיכון סרטן גבוה יותר (שד, קשור להשמנה)' WHERE health_concerns = 'NutriNet-Sante: higher cancer risk (breast, obesity-related)';
UPDATE food_additives SET health_concerns_he = 'חלבון מהצומח; עלול להכיל אלרגן סויה' WHERE health_concerns = 'Plant-derived protein; may contain soy allergen';
UPDATE food_additives SET health_concerns_he = 'עמילן מהצומח; בטוח בדרך כלל' WHERE health_concerns = 'Plant-derived starch; generally safe';
UPDATE food_additives SET health_concerns_he = 'צורת רבים של טעם טבעי. אותה הגדרה רגולטורית.' WHERE health_concerns = 'Plural form of natural flavor. Same regulatory definition.';
UPDATE food_additives SET health_concerns_he = 'מגרה אפשרי של מערכת העיכול ברמות גבוהות' WHERE health_concerns = 'Potential GI irritant at high levels';
UPDATE food_additives SET health_concerns_he = 'חשש לסרטנות (ריאה, מכתשית/סימפונית בעכברים); עוויתות במינונים גבוהים' WHERE health_concerns = 'Potential carcinogenicity (lung, alveolar/bronchiolar in mice); convulsions at high doses';
UPDATE food_additives SET health_concerns_he = 'חשש לסרטנות (לימפו-המטופויטית); רעילות עצבית; רעילות אוזנית (תעסוקתית)' WHERE health_concerns = 'Potential carcinogenicity (lymphohematopoietic); neurotoxicity; ototoxicity (occupational)';
UPDATE food_additives SET health_concerns_he = 'חשש לסרטנות (ויכוח לימפומה שאינה הודג''קין); שיבוש אנדוקריני; רעילות גנטית (שנוי במחלוקת)' WHERE health_concerns = 'Potential carcinogenicity (non-Hodgkin lymphoma debate); endocrine disruption; genotoxicity (debated)';
UPDATE food_additives SET health_concerns_he = 'חשש לסרטנות; נזק גנטי; היפראקטיביות' WHERE health_concerns = 'Potential carcinogenicity; gene damage; hyperactivity';
UPDATE food_additives SET health_concerns_he = 'חשש לסרטנות; קשר להיפראקטיביות' WHERE health_concerns = 'Potential carcinogenicity; hyperactivity link';
UPDATE food_additives SET health_concerns_he = 'חשש לסרטנות; מוגבל מאוד' WHERE health_concerns = 'Potential carcinogenicity; very restricted';
UPDATE food_additives SET health_concerns_he = 'רעילות תאית אפשרית; רעילות גנטית (שנוי במחלוקת); מחוון לנזקי חום/יישון בדבש' WHERE health_concerns = 'Potential cytotoxicity; genotoxicity (debated); indicator of heat damage/aging in honey';
UPDATE food_additives SET health_concerns_he = 'רעילות תאית אפשרית; רעילות גנטית (שנוי במחלוקת); מחוון איכות לפירוק דבש' WHERE health_concerns = 'Potential cytotoxicity; genotoxicity (disputed); quality indicator for honey degradation';
UPDATE food_additives SET health_concerns_he = 'חשש לשיבוש אנדוקריני; הצטברות חלבון; חששות רעילות גנטית' WHERE health_concerns = 'Potential endocrine disruption; protein aggregation; genotoxicity concerns';
UPDATE food_additives SET health_concerns_he = 'רעילות כלייתית אפשרית; בחקירה' WHERE health_concerns = 'Potential nephrotoxicity; under investigation';
UPDATE food_additives SET health_concerns_he = 'פרה-ביוטי (FOS); עלול לגרום גזים/נפיחות במינונים גבוהים; דל קלוריות' WHERE health_concerns = 'Prebiotic (FOS); may cause gas/bloating at high doses; low calorie';
UPDATE food_additives SET health_concerns_he = 'פרה-ביוטי; גזים ונפיחות במינונים גבוהים; משמש יותר לסיבים/נפח מאשר למתיקות' WHERE health_concerns = 'Prebiotic; gas and bloating at high doses; used more for fiber/bulk than sweetness';
UPDATE food_additives SET health_concerns_he = 'פרה-ביוטי; מתוק במעט; משמש כחומר מילוי בהפחתת סוכר' WHERE health_concerns = 'Prebiotic; mildly sweet; used as bulking agent in sugar reduction';
UPDATE food_additives SET health_concerns_he = 'פרה-ביוטי; מתעכל בקושי; ערך קלורי נמוך' WHERE health_concerns = 'Prebiotic; poorly digested; low caloric value';
UPDATE food_additives SET health_concerns_he = 'פרה-ביוטי; תומך בביפידובקטריה; אי נוחות במערכת העיכול במינונים גבוהים' WHERE health_concerns = 'Prebiotic; supports Bifidobacteria; GI discomfort at high doses';
UPDATE food_additives SET health_concerns_he = 'סרטנות סבירה; שיבוש אנדוקריני; רעילות עצבית; רעילות כבדית; הצטברות ביולוגית' WHERE health_concerns = 'Probable carcinogenicity; endocrine disruption; neurotoxicity; hepatotoxicity; bioaccumulation';
UPDATE food_additives SET health_concerns_he = 'עמילן מעובד; מעלה אינדקס גליקמי מהר יותר מעמילן רגיל' WHERE health_concerns = 'Processed starch; raises glycemic index faster than regular starch';
UPDATE food_additives SET health_concerns_he = 'מקדם עששת; תורם להשמנה, סוכרת סוג 2, תסמונת מטבולית' WHERE health_concerns = 'Promotes dental caries; contributes to obesity, type 2 diabetes, metabolic syndrome';
UPDATE food_additives SET health_concerns_he = 'מקור חלבון; עשיר יותר בשומן רווי' WHERE health_concerns = 'Protein source; higher in saturated fat';
UPDATE food_additives SET health_concerns_he = 'מוכח אנטי-עששתי (נלחם בעששת); משלשל >30-40 גרם/יום; רעיל לכלבים; מחקרי חשש קרדיווסקולרי (קליבלנד קליניק 2023)' WHERE health_concerns = 'Proven anti-cariogenic (fights tooth decay); laxative >30-40g/day; TOXIC to dogs; some cardiovascular concern studies (Cleveland Clinic 2023)';
UPDATE food_additives SET health_concerns_he = 'תגובות אלרגיות נדירות; ADI נמוך מביקסין' WHERE health_concerns = 'Rare allergic reactions; lower ADI than bixin';
UPDATE food_additives SET health_concerns_he = 'אנפילקסיס נדיר; תגובות אלרגיות באנשים רגישים' WHERE health_concerns = 'Rare anaphylaxis; allergic reactions in sensitive individuals';
UPDATE food_additives SET health_concerns_he = 'סוכר נדיר; לא גורם עששת; נתונים מוגבלים' WHERE health_concerns = 'Rare sugar; non-cariogenic; limited data';
UPDATE food_additives SET health_concerns_he = 'ייצור חלבון רקומביננטי בתסיסה; יציב בחום וב-pH' WHERE health_concerns = 'Recombinant protein production via fermentation; heat and pH stable';
UPDATE food_additives SET health_concerns_he = 'שתן אדום (ביטוריה); אי נוחות במערכת העיכול' WHERE health_concerns = 'Red urine (beeturia); GI discomfort';
UPDATE food_additives SET health_concerns_he = 'שתן/צואה אדומים (ביטוריה לא מזיקה); אי נוחות במערכת העיכול בחלק מהאנשים' WHERE health_concerns = 'Red urine/stools (harmless beeturia); GI discomfort in some';
UPDATE food_additives SET health_concerns_he = 'דווח על תסמונת תסמיני MSG באנשים רגישים; ADI של EFSA נחרג בחלק מהאוכלוסיות' WHERE health_concerns = 'Reported MSG symptom complex in sensitive individuals; EFSA ADI exceeded in some populations';
UPDATE food_additives SET health_concerns_he = 'רעילות רבייתית (נתוני בעלי חיים); בחילה; הקאה; שלשול; דרמטיטיס' WHERE health_concerns = 'Reproductive toxicity (animal data); Nausea; Vomiting; Diarrhea; Dermatitis';
UPDATE food_additives SET health_concerns_he = 'רעילות רבייתית (אנטי-אנדרוגנית); שיבוש אנדוקריני; רעילות התפתחותית' WHERE health_concerns = 'Reproductive toxicity (anti-androgenic); endocrine disruption; developmental toxicity';
UPDATE food_additives SET health_concerns_he = 'קבוצה מחקרית המכילה את הממתיקים החזקים הידועים' WHERE health_concerns = 'Research class containing the most potent sweeteners known';