import json
import os

TRANSLATIONS = {
    "Commercial brand name for isomalt; same profile": "שם מסחרי לאיזומלט; אותו פרופיל בטיחות",
    "Common aglycone metabolite; ADI for steviol glycosides expressed as steviol equivalents": "מטבוליט נפוץ; ערך צריכה יומית מותרת לגליקוזידי סטביול מבוטא בשווי ערך סטביול",
    "Common commercial blend; individual safety profiles apply": "תערובת מסחרית נפוצה; פרופיל בטיחות של כל רכיב בנפרד",
    "Contains phenylalanine derivative but at negligible levels; heat stable": "מכיל נגזרת פנילאלנין ברמות זניחות; יציב בחום",
    "Contains phenylalanine; fillers add calories; PKU warning": "מכיל פנילאלנין; חומרי מילוי מוסיפים קלוריות; אזהרת PKU",
    "Contains xylose residue; minor steviol glycoside": "מכיל שאריות קסילוז; גליקוזיד סטביול משני",
    "D-form is sweet while L-form is bitter; research interest": "צורת D מתוקה בעוד צורת L מרה; עניין מחקרי",
    "Degradation product of Reb A; slightly bitter": "תוצר פירוק של Reb A; מעט מר",
    "Derived from citrus; lingering sweet aftertaste; EFSA 2022 confirmed safety": "מופק מהדרים; טעם מתוק מתמשך; EFSA 2022 אישר בטיחות",
    "Dissociates into aspartame and acesulfame in body; PKU warning applies": "מתפרק לאספרטיים ואצסולפיים בגוף; אזהרת PKU חלה",
    "Emerging; antimicrobial properties": "חדש; תכונות אנטי-מיקרוביאליות",
    "Emerging; heat-sensitive": "חדש; רגיש לחום",
    "Enzymatic production route; same safety profile as allulose": "מיוצר בדרך אנזימטית; אותו פרופיל בטיחות כמו אלולוז",
    "Free acid form; potassium salt (E950) is the commercial form": "צורת חומצה חופשית; מלח אשלגן (E950) הוא הצורה המסחרית",
    "General acidity regulator; usually safe food acids": "מווסת חומציות כללי; בדרך כלל חומצות מזון בטוחות",
    "General food acid; usually citric or lactic acid": "חומצת מזון כללית; בדרך כלל חומצת לימון או חומצה לקטית",
    "General stabilizer category; safety depends on specific compound": "קטגוריית מייצב כללית; הבטיחות תלויה בתרכובת הספציפית",
    "General term for bacterial starter cultures.": "מונח כללי לתרביות חיידקים לתסיסה.",
    "General term for food enzymes (amylase, protease, lipase). Processing aids.": "מונח כללי לאנזימי מזון (עמילאז, פרוטאז, ליפאז). חומרי עיבוד.",
    "General term for hot peppers. Contains capsaicin.": "מונח כללי לפלפלים חריפים. מכיל קפסאיצין.",
    "General thickener category; safety depends on specific compound": "קטגוריית מעבה כללית; הבטיחות תלויה בתרכובת הספציפית",
    "Generally considered safe; EFSA 2025 re-evaluation raised ADI to 15 mg/kg": "נחשב בטוח בדרך כלל; הערכה מחדש של EFSA 2025 העלתה ADI ל-15 מ\"ג/ק\"ג",
    "Glycerol safety well-established in food": "בטיחות גליצרול מבוססת היטב במזון",
    "Ground dried peppers. Color and mild flavor. Source of capsanthin.": "פלפלים מיובשים טחונים. צבע וטעם עדין. מקור לקפסנטין.",
    "Gut microbiome disruption reported": "דווח על שיבוש מיקרוביום המעי",
    "Headache, irritability at higher doses": "כאבי ראש, עצבנות במינונים גבוהים",
    "Healthy vegetable; rich in beta-carotene": "ירק בריא; עשיר בבטא-קרוטן",
    "Heat stable; limited commercial production; traditional use in Yunnan Province": "יציב בחום; ייצור מסחרי מוגבל; שימוש מסורתי במחוז יונאן",
    "High GI; used as 'clean label' alternative to corn syrup": "אינדקס גליקמי גבוה; משמש כחלופת 'תווית נקייה' לסירופ תירס",
    "High heat stability; laxative at >20-30g/day; lower GI impact than maltitol": "יציבות גבוהה בחום; משלשל מעל 20-30 גרם/יום; השפעה גליקמית נמוכה יותר ממלטיטול",
    "Highest grade olive oil. Rich in oleic acid, polyphenols.": "שמן זית מהדרגה הגבוהה ביותר. עשיר בחומצה אולאית ופוליפנולים.",
    "Hormone disruption; endocrine disruptor; banned in EU food since 2006": "שיבוש הורמונלי; משבש אנדוקריני; אסור במזון באיחוד האירופי מ-2006",
    "Human milk oligosaccharide; immune benefits; mildly sweet": "אוליגוסכריד מחלב אם; יתרונות חיסוניים; מתוק במעט",
    "IARC 2B July 2023; Weizmann: altered gut microbiota; BGU: toxic to gut bacteria; Israel no warning": "IARC 2B יולי 2023; מכון ויצמן: שינוי מיקרוביוטת המעי; אוניברסיטת בן גוריון: רעיל לחיידקי מעי; ישראל ללא אזהרה",
    "Improved taste profile vs standard steviol glycosides": "פרופיל טעם משופר לעומת גליקוזידי סטביול סטנדרטיים",
    "Improved taste profile; less bitter than Reb A": "פרופיל טעם משופר; פחות מר מ-Reb A",
    "Inert; safe in small quantities": "אינרטי; בטוח בכמויות קטנות",
    "Insufficient data for food use": "אין מספיק נתונים לשימוש במזון",
    "Insufficient safety data for food": "אין מספיק נתוני בטיחות למזון",
    "Iron fortification in flour/cereals. Common in enriched wheat products.": "העשרת ברזל בקמח/דגנים. נפוץ במוצרי חיטה מועשרים.",
    "Iron overload at excess": "עומס ברזל בעודף",
    "Iron overload risk": "סיכון לעומס ברזל",
    "Irritant at high concentrations": "מגרה בריכוזים גבוהים",
    "Japan classifies at 0 kcal/g; approved since 2010 in Japan; Korean approval 2012": "יפן מסווגת כ-0 קלוריות/גרם; מאושר ביפן מאז 2010; אישור קוריאני 2012",
    "Kidney/liver toxicity, banned": "רעילות כליות/כבד, אסור לשימוש",
    "L-Arabinose may inhibit sucrase enzyme; ribose used for energy/sports performance": "L-ארבינוז עשוי לעכב אנזים סוכראז; ריבוז משמש לאנרגיה/ביצועי ספורט",
    "Laboratory compound; world's sweetest known substance": "תרכובת מעבדה; החומר המתוק ביותר הידוע בעולם",
    "Laxative at lower threshold than sorbitol (~10-20g); osmotic effects; cooling sensation": "משלשל בסף נמוך יותר מסורביטול (~10-20 גרם); השפעות אוסמוטיות; תחושת קרירות",
    "Laxative; limited food safety data": "משלשל; נתוני בטיחות מזון מוגבלים",
    "Leavening acid. Used with baking soda. Also prevents darkening in potatoes.": "חומצת תפיחה. משמשת עם סודה לשתייה. גם מונעת השחמת תפוחי אדמה.",
    "Less sweet; more bitter than Reb A; usually minor component": "פחות מתוק; יותר מר מ-Reb A; בדרך כלל רכיב משני",
    "Limited approvals globally; heat stable": "אישורים מוגבלים בעולם; יציב בחום",
    "Limited data; appears well-tolerated at studied doses": "נתונים מוגבלים; נראה נסבל היטב במינונים שנחקרו",
    "Limited data; appears well-tolerated short-term": "נתונים מוגבלים; נראה נסבל היטב בטווח הקצר",
    "Limited food approval": "אישור מזון מוגבל",
    "Limited food safety data": "נתוני בטיחות מזון מוגבלים",
    "Limited safety data; restricted use": "נתוני בטיחות מוגבלים; שימוש מוגבל",
    "Limited toxicological data": "נתונים טוקסיקולוגיים מוגבלים",
    "Lingering sweetness; used to mask bitterness": "מתיקות מתמשכת; משמש להסוואת מרירות",
    "Maltodextrin filler adds calories and raises GI vs pure sucralose": "מלטודקסטרין כמילוי מוסיף קלוריות ומעלה אינדקס גליקמי לעומת סוכרלוז טהור",
    "Masks B12 deficiency; May promote colorectal neoplasms; Seizures in anticonvulsant users": "מסווה חוסר B12; עלול לקדם גידולים קולורקטליים; פרכוסים במשתמשי תרופות נוגדות פרכוסים",
    "May exacerbate inflammatory conditions": "עלול להחמיר מצבים דלקתיים",
    "May reduce drug absorption": "עלול להפחית ספיגת תרופות",
    "May reduce drug/nutrient absorption": "עלול להפחית ספיגת תרופות/תזונה",
    "May reduce medication efficacy; drug interaction warning": "עלול להפחית יעילות תרופות; אזהרת אינטראקציה עם תרופות",
    "Mediterranean herb. Contains carvacrol (antimicrobial).": "עשב ים תיכוני. מכיל קרבקרול (אנטי-מיקרוביאלי).",
    "Medium-hot chili pepper. Contains capsaicin.": "פלפל חריף בינוני. מכיל קפסאיצין.",
    "Minor component of monk fruit extract": "רכיב משני בתמצית פרי הנזיר",
    "Minor steviol glycoside; less sweet than stevioside": "גליקוזיד סטביול משני; פחות מתוק מסטביוזיד",
    "More bitter aftertaste than Reb A; traditional use in South America": "טעם מר יותר מ-Reb A; שימוש מסורתי בדרום אמריקה",
    "Most common form of saccharin used commercially": "הצורה הנפוצה ביותר של סכרין בשימוש מסחרי",
    "Most commonly used steviol glycoside; clean sweet taste": "גליקוזיד הסטביול הנפוץ ביותר; טעם מתוק נקי",
    "N/A": "לא רלוונטי",
    "New approval; considered safe": "אישור חדש; נחשב בטוח",
    "New; safety evaluated by FDA": "חדש; בטיחות הוערכה על ידי FDA",
    "Nitrosamine pathway; EU 500K+ petition for ban": "מסלול ניטרוזאמין; עצומה של 500K+ באיחוד האירופי לאיסור",
    "No known toxicity (excess excreted in urine; yellow discoloration)": "אין רעילות ידועה (עודף מופרש בשתן; צביעה צהובה)",
    "No known toxicity from food or supplements; May impair anticoagulant therapy": "אין רעילות ידועה ממזון או תוספים; עלול לפגוע בטיפול נוגד קרישה",
    "No known toxicity from oral intake": "אין רעילות ידועה מצריכה דרך הפה",
    "Non-cariogenic; laxative at high oral doses": "לא גורם עששת; משלשל במינונים גבוהים",
    "Non-cariogenic; slowly digested": "לא גורם עששת; מתעכל באיטיות",
    "Non-cariogenic; slowly digested; used in Japan since 1970s": "לא גורם עששת; מתעכל באיטיות; בשימוש ביפן מאז שנות ה-70",
    "None at recommended doses": "אין בחשיפה למינונים מומלצים",
    "Not evaluated for food safety": "לא הוערך לבטיחות מזון",
    "Not for food use": "לא לשימוש במזון",
    "Not for food; drug/cosmetic use only": "לא למזון; לשימוש בתרופות/קוסמטיקה בלבד",
    "Not for food; restricted drug use": "לא למזון; שימוש תרופתי מוגבל",
    "Not for human consumption at this grade": "לא לצריכת אדם בדרגה זו",
    "Not for human food consumption": "לא לצריכת מזון אנושית",
    "Only purified steviol glycosides (ג‰¥95%) are approved; whole leaf not permitted in US/EU": "רק גליקוזידי סטביול מזוקקים (≥95%) מאושרים; עלה שלם אסור בארה\"ב/אירופה",
    "Orchid-derived flavoring. Contains vanillin. Most expensive spice by weight.": "תמצית טעם ממשפחת הסחלב. מכיל וניליין. התבלין היקר ביותר לפי משקל.",
    "Part of E471. Emulsifier from glycerol + fatty acid.": "חלק מ-E471. מתחלב מגליצרול + חומצת שומן.",
    "Peripheral neuropathy; Sensory ataxia; Loss of sensation": "נוירופתיה היקפית; אטקסיה חושית; אובדן תחושה",
    "Plant-derived fat; may contain palm oil or hydrogenated fats": "שומן מהצומח; עשוי להכיל שמן דקל או שומנים מוקשים",
    "Plural of Artificial Flavor.": "צורת רבים של טעם מלאכותי.",
    "Plural of Flavoring. Generic term.": "צורת רבים של חומר טעם. מונח כללי.",
    "Plural of Onion. Root vegetable.": "צורת רבים של בצל. ירק שורש.",
    "Polyunsaturated vegetable oil. High omega-6.": "שמן צמחי רב בלתי רווי. עשיר באומגה-6.",
    "Poorly absorbed; used in xylose absorption test; precursor to xylitol": "נספג בצורה גרועה; משמש בבדיקת ספיגת קסילוז; חומר מוצא לקסיליטול",
    "Poorly absorbed; used more for urinary health than sweetness": "נספג בצורה גרועה; משמש יותר לבריאות דרכי השתן מאשר כממתיק",
    "Popular in keto/low-carb diets; erythritol ADI caution applies": "פופולרי בדיאטות קטו/דלות פחמימות; אזהרת ADI של אריתריטול חלה",
    "Popular zero-calorie blend; EFSA erythritol ADI caution applies": "תערובת אפס קלוריות פופולרית; אזהרת ADI של EFSA לאריתריטול חלה",
    "Precursor to lugduname; research only": "חומר מוצא ללוגדונאם; מחקר בלבד",
    "Primarily a texturizer; minimal sweetness contribution": "בעיקר חומר מרקם; תרומת מתיקות מינימלית",
    "Purine metabolite; uric acid elevation in susceptible individuals": "מטבוליט פורין; עליית חומצת שתן באנשים רגישים",
    "Rare allergic/anaphylactic reactions": "תגובות אלרגיות/אנפילקטיות נדירות",
    "Reduced bitterness vs standard steviol glycosides": "מרירות מופחתת לעומת גליקוזידי סטביול סטנדרטיים",
    "Reduced paresthesia vs. instant release": "פרסתזיה מופחתת לעומת שחרור מיידי",
    "Related to monk fruit but different species; limited regulatory evaluation": "קשור לפרי הנזיר אך מין שונה; הערכה רגולטורית מוגבלת",
    "Research class; some members have traditional use": "סוג מחקרי; לחלק מהחברים שימוש מסורתי",
    "Restricted to non-food; limited drug use": "מוגבל לשימוש שאינו מזון; שימוש תרופתי מוגבל",
    "Retinal crystal deposits at high human doses; strict feed limits": "משקעים גבישיים ברשתית במינונים גבוהים; מגבלות מזון מחמירות",
    "Root vegetable. Major crop. Nightshade family.": "ירק שורש. גידול מרכזי. ממשפחת הסולניים.",
    "Saccharin safety reaffirmed by EFSA 2024; fillers add calories": "בטיחות סכרין אושרה מחדש על ידי EFSA 2024; חומרי מילוי מוסיפים קלוריות",
    "Safe as supplement; not as color additive": "בטוח כתוסף תזונה; לא כתוסף צבע",
    "Safe at ADI; copper content monitored": "בטוח ב-ADI; תכולת נחושת מנוטרת",
    "Safe at approved levels": "בטוח ברמות מאושרות",
    "Safe at normal food levels": "בטוח ברמות מזון רגילות",
    "Safe at restricted levels": "בטוח ברמות מוגבלות",
    "Safe for DHA; not a primary colorant": "בטוח ל-DHA; לא צבע ראשי",
    "Safe in cosmetics; not for food coloring": "בטוח בקוסמטיקה; לא לצביעת מזון",
    "Safe in feed use": "בטוח לשימוש בהזנת בעלי חיים",
    "Safe in food; traditional ingredient": "בטוח במזון; מרכיב מסורתי",
    "Safe in moderate amounts. Limit for children and pregnant women.": "בטוח בכמויות מתונות. הגבלה לילדים ונשים בהריון.",
    "Safe in small amounts": "בטוח בכמויות קטנות",
    "Safe in traditional Asian use": "בטוח בשימוש מסורתי אסיאתי",
    "Safe in traditional use; widely used in Japan": "בטוח בשימוש מסורתי; נפוץ ביפן",
    "Safe; acid-stable": "בטוח; יציב בחומצה",
    "Safe; expensive": "בטוח; יקר",
    "Safe; expensive spice": "בטוח; תבלין יקר",
    "Safe; eye health benefits": "בטוח; יתרונות לבריאות העיניים",
    "Safe; gossypol removed": "בטוח; גוסיפול הוסר",
    "Safe; heat and pH sensitive": "בטוח; רגיש לחום ול-pH",
    "Safe; heat stable anthocyanins": "בטוח; אנתוציאנינים יציבים בחום",
    "Safe; heat-sensitive": "בטוח; רגיש לחום",
    "Safe; heat-sensitive; pH-sensitive": "בטוח; רגיש לחום ול-pH",
    "Safe; macular health": "בטוח; בריאות המקולה",
    "Safe; mild sedative properties": "בטוח; תכונות מרגיעות קלות",
    "Safe; minimal processing": "בטוח; עיבוד מינימלי",
    "Safe; must be cooked (raw contains oxalates)": "בטוח; חייב להיות מבושל (גולמי מכיל אוקסלטים)",
    "Safe; nature-identical production": "בטוח; ייצור זהה לטבע",
    "Safe; not the same as E123": "בטוח; לא זהה ל-E123",
    "Safe; novel food ingredient": "בטוח; מרכיב מזון חדשני",
    "Safe; nutrient-dense": "בטוח; עשיר בערכים תזונתיים",
    "Safe; nutritional supplement": "בטוח; תוסף תזונה",
    "Safe; nutritious leafy green": "בטוח; ירק עלים מזין",
    "Safe; pH indicator properties": "בטוח; תכונות מחוון pH",
    "Safe; pH-dependent blue color": "בטוח; צבע כחול תלוי pH",
    "Safe; pH-sensitive": "בטוח; רגיש ל-pH",
    "Safe; pH-sensitive color": "בטוח; צבע רגיש ל-pH",
    "Safe; rich in anthocyanins": "בטוח; עשיר באנתוציאנינים",
    "Safe; standardized for consistent color": "בטוח; מתוקנן לצבע אחיד",
    "Safe; superfood": "בטוח; סופרפוד",
    "Safe; traditional Japanese ingredient": "בטוח; מרכיב יפני מסורתי",
    "Safe; very high carotenoid content": "בטוח; תכולת קרוטנואידים גבוהה מאוד",
    "Salt form of saccharin": "צורת מלח של סכרין",
    "Same as Corn Starch. Alternate spelling.": "זהה לעמילן תירס. איות חלופי.",
    "Same as Garlic Powder but coarser.": "זהה לאבקת שום אך גס יותר.",
    "Same as Modified Food Starch. US labeling variant.": "זהה לעמילן מזון מותאם. וריאנט תיוג אמריקאי.",
    "Same as liquid allulose; crystalline form for direct substitution; Maillard browning capacity": "זהה לאלולוז נוזלי; צורה גבישית להחלפה ישירה; יכולת השחמת מאייר",
    "Same as standard aspartame; coating improves thermal stability": "זהה לאספרטיים רגיל; ציפוי משפר יציבות תרמית",
    "Severe lead poisoning; historical curiosity only; extremely toxic": "הרעלת עופרת חמורה; סקרנות היסטורית בלבד; רעיל ביותר",
    "Similar to E473": "דומה ל-E473",
    "Single form. Bacterial starter culture for cheese production.": "צורת יחיד. תרבית חיידקים לייצור גבינה.",
    "Singular form of Spices.": "צורת יחיד של תבלינים.",
    "Singular form.": "צורת יחיד.",
    "Singular of Egg Yolks.": "צורת יחיד של חלמונים.",
    "Singular of Eggs.": "צורת יחיד של ביצים.",
    "Sodium salt form of cyclamate; banned in US since 1969": "צורת מלח נתרן של ציקלמט; אסור בארה\"ב מאז 1969",
    "Starch modified for food applications. Source varies (corn, potato, tapioca).": "עמילן מותאם לשימושי מזון. המקור משתנה (תירס, תפוח אדמה, טפיוקה).",
    "Structurally similar to stevioside; traditional use in China": "דומה מבנית לסטביוזיד; שימוש מסורתי בסין",
    "Sub-sweetening doses enhance and round out flavors": "מינונים תת-ממתיקים משפרים ומעגלים טעמים",
    "Sucralose masks stevia bitterness; popular formulation approach": "סוכרלוז מסווה את מרירות הסטיביה; גישת ניסוח פופולרית",
    "Sulfite sensitivity": "רגישות לסולפיטים",
    "Synergistic blend used in most major diet beverage brands; masks off-flavors": "תערובת סינרגיסטית המשמשת ברוב מותגי משקאות הדיאט; מסווה טעמי לוואי",
    "Synergistic sweetness; individual component safety applies": "מתיקות סינרגיסטית; בטיחות כל רכיב בנפרד",
    "Syrup form for liquid applications; same safety as crystalline": "צורת סירופ ליישומים נוזליים; אותה בטיחות כמו גבישי",
    "Thyroid disruption; hemolytic anemia \u2013 infants most vulnerable": "שיבוש בלוטת התריס; אנמיה המוליטית - תינוקות הכי פגיעים",
    "Thyroid dysfunction at excess": "הפרעת בלוטת תריס בעודף",
    "Thyroid function disruption (inhibits iodine uptake); developmental effects in fetuses/infants": "שיבוש תפקוד בלוטת התריס (מעכב קליטת יוד); השפעות התפתחותיות בעוברים/תינוקות",
    "Thyroid iodine uptake inhibition \u2013 critical for neurodevelopment in infants": "עיכוב קליטת יוד בתריס - קריטי להתפתחות עצבית בתינוקות",
    "Thyroid tumors in rats; FDA banned under Delaney Clause": "גידולי תריס בחולדות; FDA אסר לפי סעיף דילייני",
    "Traditional spice with sweet notes; limited characterization": "תבלין מסורתי עם גוונים מתוקים; אפיון מוגבל",
    "Traditional use for centuries; whole fruit form (not extract)": "שימוש מסורתי במשך מאות שנים; צורת פרי שלם (לא תמצית)",
    "Unique taste-modifying properties; makes sour taste sweet": "תכונות שינוי טעם ייחודיות; הופך חמוץ למתוק",
    "Universal solvent, base ingredient in most processed foods.": "ממס אוניברסלי, מרכיב בסיס ברוב המזונות המעובדים.",
    "Unstable; difficult to produce commercially": "לא יציב; קשה לייצור מסחרי",
    "Variable GI depending on maltitol content; laxative effects": "אינדקס גליקמי משתנה בהתאם לתכולת מלטיטול; השפעות משלשלות",
    "Variable composition; laxative effects similar to other polyols": "הרכב משתנה; השפעות משלשלות דומות לפוליאולים אחרים",
    "Very low sweetness intensity; minor component": "עוצמת מתיקות נמוכה מאוד; רכיב משני",
    "Water filtered for purity. Common base ingredient.": "מים מסוננים לטוהר. מרכיב בסיס נפוץ.",
    "Water with dissolved CO2. Base for soft drinks.": "מים עם CO2 מומס. בסיס למשקאות קלים.",
    "White meat. Not halal/kosher without certification.": "בשר לבן. לא חלאל/כשר ללא הסמכה.",
    "Whole food vegetable. Common in most cuisines.": "ירק מזון שלם. נפוץ ברוב המטבחים.",
    # Handle the mangled Hebrew encoding variants
    "Thyroid disruption; hemolytic anemia ג€\" infants most vulnerable": "שיבוש בלוטת התריס; אנמיה המוליטית - תינוקות הכי פגיעים",
    "Thyroid iodine uptake inhibition ג€\" critical for neurodevelopment in infants": "עיכוב קליטת יוד בתריס - קריטי להתפתחות עצבית בתינוקות",
    "Only purified steviol glycosides (ג‰¥95%) are approved; whole leaf not permitted in US/EU": "רק גליקוזידי סטביול מזוקקים (≥95%) מאושרים; עלה שלם אסור בארה\"ב/אירופה",
}

def escape_sql(text):
    return text.replace("'", "''")

def main():
    sql_lines = []
    for eng, heb in TRANSLATIONS.items():
        eng_escaped = escape_sql(eng)
        heb_escaped = escape_sql(heb)
        sql_lines.append(f"UPDATE food_additives SET health_concerns_he = '{heb_escaped}' WHERE health_concerns = '{eng_escaped}';")

    sql_dir = os.path.join(os.path.dirname(__file__), "sql")
    os.makedirs(sql_dir, exist_ok=True)
    sql_path = os.path.join(sql_dir, "health_concerns_he_batch4.sql")
    with open(sql_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))
    print(f"Written {len(sql_lines)} UPDATE statements to {sql_path}")

if __name__ == "__main__":
    main()
