"""
Final comprehensive batch: translate ALL remaining 524 health_concerns texts to Hebrew.
"""
import json
import os

TRANSLATIONS = {
    # === 4-MEI/California ===
    "4-MEI and THI concerns; California Prop 65": "חששות 4-MEI ו-THI; California Prop 65",
    "4-methylimidazole (4-MEI) concerns; California Prop 65 listed": "חששות 4-מתילאימידזול (4-MEI); רשום ב-California Prop 65",

    # === Citrus/Sweetener compounds ===
    "Citrus derivative; lingering sweetness; antioxidant properties": "נגזרת הדרים; מתיקות מתמשכת; תכונות נוגדות חמצון",
    "Class of compounds derived from flavonoids; lingering sweetness": "קבוצת תרכובות הנגזרות מפלבנואידים; מתיקות מתמשכת",
    "Closest to sugar taste among steviol glycosides; produced via fermentation or enzymatic conversion": "הקרוב ביותר לטעם סוכר בין גליקוזידי הסטביול; מיוצר בתסיסה או המרה אנזימטית",

    # === GI/Constipation ===
    "Constipation, GI discomfort; hypercalcemia; kidney stone risk": "עצירות, אי נוחות במערכת העיכול; היפרקלצמיה; סיכון לאבני כליות",
    "Constipation, nausea, black stools, GI upset; iron overload risk": "עצירות, בחילה, צואה שחורה, הפרעה במערכת העיכול; סיכון לעומס ברזל",

    # === Contact dermatitis ===
    "Contact dermatitis; oral nickel allergy symptoms in sensitized individuals": "דרמטיטיס מגע; תסמיני אלרגיה לניקל דרך הפה באנשים רגישים",
    "Contact dermatitis; systemic effects in sensitized individuals": "דרמטיטיס מגע; השפעות מערכתיות באנשים רגישים",

    # === Contains... ===
    "Contains 4-MEI possibly carcinogenic; California Prop 65 warning": "מכיל 4-MEI אפשרי מסרטן; אזהרת California Prop 65",
    "Contains beta-glucan; moderate GI; not gluten-free": "מכיל בטא-גלוקן; אינדקס גליקמי בינוני; לא ללא גלוטן",
    "Contains bran, germ, endosperm. More fiber than white flour. Gluten allergen.": "מכיל סובין, נבט, אנדוספרם. יותר סיבים מקמח לבן. אלרגן גלוטן.",
    "Contains cocoa solids, cocoa butter, sugar. Common allergen concern (milk).": "מכיל מוצקי קקאו, חמאת קקאו, סוכר. חשש אלרגן נפוץ (חלב).",
    "Contains curcumin (E100). Anti-inflammatory claims. Yellow color.": "מכיל כורכומין (E100). טענות אנטי-דלקתיות. צבע צהוב.",
    "Contains enzymes for bread making. Source of amylase. Contains gluten.": "מכיל אנזימים לאפיית לחם. מקור לעמילאז. מכיל גלוטן.",
    "Contains fructose; lower GI than maple syrup; mineral content": "מכיל פרוקטוז; אינדקס גליקמי נמוך מסירופ מייפל; תכולת מינרלים",
    "Contains gluten (not suitable for celiac disease); lower GI than rice syrup": "מכיל גלוטן (לא מתאים לצליאק); אינדקס גליקמי נמוך מסירופ אורז",
    "Contains inulin fiber; lower GI than sucrose but still caloric sugar": "מכיל סיבי אינולין; אינדקס גליקמי נמוך מסוכרוז אך עדיין סוכר קלורי",
    "Contains lactose; unsuitable for lactose intolerant; mild sweetness; cost-effective bulking agent": "מכיל לקטוז; לא מתאים לרגישי לקטוז; מתיקות עדינה; חומר מילוי חסכוני",
    "Contains minerals (manganese, zinc) and antioxidants; still a caloric sugar": "מכיל מינרלים (מנגן, אבץ) ונוגדי חמצון; עדיין סוכר קלורי",
    "Contains minerals and polyphenols; associated with Okinawan longevity (unproven); caloric": "מכיל מינרלים ופוליפנולים; קשור לאריכות ימים אוקינאווית (לא מוכח); קלורי",
    "Contains polyphenols; lower GI than refined sugar; still cariogenic": "מכיל פוליפנולים; אינדקס גליקמי נמוך מסוכר מזוקק; עדיין גורם עששת",

    # === Crystalline/Cytotoxicity ===
    "Crystalline form; closest bulk and texture to sucrose among polyols": "צורה גבישית; הנפח והמרקם הקרובים ביותר לסוכרוז בין הפוליאולים",
    "Cytotoxicity (in vitro); generally safe at ADI": "רעילות תאית (במבחנה); בטוח בדרך כלל ב-ADI",
    "Cytotoxicity; potential immunotoxicity; ion channel disruption": "רעילות תאית; רעילות חיסונית אפשרית; שיבוש תעלות יונים",
    "Cytotoxicity; potential immunotoxicity; ionophoric activity": "רעילות תאית; רעילות חיסונית אפשרית; פעילות יונופורית",

    # === D-form/Denatures ===
    "D-form amino acid; sweet taste; not used commercially as sweetener": "חומצת אמינו בצורת D; טעם מתוק; לא בשימוש מסחרי כממתיק",
    "Denatures easily; not commercially viable yet": "מתפרק בקלות; עדיין לא ישים מסחרית",

    # === Dental ===
    "Dental erosion; reduced bone mineral density; kidney problems; osteoporosis": "שחיקת שיניים; ירידה בצפיפות מינרלים בעצמות; בעיות כליות; אוסטאופורוזיס",
    "Dental fluorosis (children); Skeletal fluorosis (chronic); Nausea; Bone pain; Stiffness": "פלואורוזיס שיניים (ילדים); פלואורוזיס שלדי (כרוני); בחילה; כאבי עצמות; נוקשות",

    # === Dermatitis/Diarrhea ===
    "Dermatitis (sensitized individuals); reproductive/developmental toxicity; potential carcinogenicity (respiratory)": "דרמטיטיס (אנשים רגישים); רעילות רבייתית/התפתחותית; חשש לסרטנות (נשימתית)",
    "Diarrhea (most common); Nausea; Abdominal cramping; Hypermagnesemia (renal impairment): hypotension, respiratory depression": "שלשול (הנפוץ ביותר); בחילה; התכווצויות בטן; היפרמגנזמיה (אי ספיקת כליות): לחץ דם נמוך, דיכוי נשימתי",
    "Diarrhea at very high doses (>10g); Generally very safe": "שלשול במינונים גבוהים מאוד (>10 גרם); בטוח מאוד בדרך כלל",
    "Diarrhea, GI cramping (especially oxide form)": "שלשול, התכווצויות במערכת העיכול (במיוחד צורת אוקסיד)",
    "Diarrhea; Nausea; Kidney stones (oxalate); Iron overload risk in hemochromatosis": "שלשול; בחילה; אבני כליות (אוקסלט); סיכון לעומס ברזל בהמוכרומטוזיס",

    # === Dioxin/Dizziness ===
    "Dioxin-like toxicity; hepatotoxicity; immunotoxicity; skin effects (chloracne)": "רעילות דמוית דיאוקסין; רעילות כבדית; רעילות חיסונית; השפעות עור (כלוראקנה)",
    "Dizziness, dry mouth, insomnia if taken late": "סחרחורת, יובש בפה, נדודי שינה אם נלקח מאוחר",

    # === EFSA ===
    "EFSA 2025 could not establish safety (data gaps); FDA considers safe; GI discomfort >50g/serving; promising for blood sugar management": "EFSA 2025 לא יכל לקבוע בטיחות (פערי נתונים); FDA מחשיב כבטוח; אי נוחות במערכת העיכול >50 גרם/מנה; מבטיח לניהול סוכר בדם",
    "EFSA data gaps noted; under re-evaluation": "צוינו פערי נתונים ב-EFSA; בהערכה מחדש",
    "EFSA lowered ADI to 0.5g/kg in 2023 due to laxative effects; Cleveland Clinic studies linked to cardiovascular risk (observational; EFSA found no causal evidence); nearly zero calories": "EFSA הוריד ADI ל-0.5 גרם/ק\"ג ב-2023 בשל השפעות משלשלות; מחקרי קליבלנד קליניק קשרו לסיכון קרדיווסקולרי (תצפיתי; EFSA לא מצא ראיות סיבתיות); כמעט אפס קלוריות",
    "EFSA: no longer safe; potential genotoxicity; 36% nano-sized; Maya recall June 2025": "EFSA: כבר לא בטוח; חשש לרעילות גנטית; 36% בגודל ננו; ריקול Maya יוני 2025",

    # === EU/Emerging ===
    "EU term for HFCS; same metabolic concerns; production quota restrictions removed in 2017": "מונח אירופי ל-HFCS; אותם חששות מטבוליים; הגבלות מכסת ייצור הוסרו ב-2017",
    "Emerging blend; allulose not approved in EU": "תערובת חדשה; אלולוז לא מאושר באיחוד האירופי",
    "Emerging class of natural sweet compounds from various plant sources": "קבוצה חדשה של תרכובות מתוקות טבעיות ממקורות צמחיים שונים",
    "Emerging natural pigment; not food-approved": "פיגמנט טבעי חדש; לא מאושר למזון",
    "Emerging; antimicrobial properties; not food-approved": "חדש; תכונות אנטי-מיקרוביאליות; לא מאושר למזון",
    "Emerging; antioxidant properties": "חדש; תכונות נוגדות חמצון",

    # === Endocrine ===
    "Endocrine disruption (estrogenic activity similar to BPA); reproductive effects": "שיבוש אנדוקריני (פעילות אסטרוגנית דומה ל-BPA); השפעות רבייתיות",
    "Endocrine disruption; kidney/liver damage in animals; often used with BHA/BHT": "שיבוש אנדוקריני; נזק לכליות/כבד בבעלי חיים; לעיתים משמש עם BHA/BHT",
    "Endocrine disruption; reproductive toxicity (anti-androgenic); hepatotoxicity; potential carcinogenicity": "שיבוש אנדוקריני; רעילות רבייתית (אנטי-אנדרוגנית); רעילות כבדית; חשש לסרטנות",
    "Enhanced bioavailability; nano concerns parallel to TiO2 debate": "זמינות ביולוגית משופרת; חששות ננו מקבילים לוויכוח TiO2",

    # === Experimental ===
    "Experimental dipeptide sweetener; academic interest": "ממתיק דיפפטיד ניסיוני; עניין אקדמי",
    "Experimental sweetener; not commercially available": "ממתיק ניסיוני; לא זמין מסחרית",
    "Experimental; among most potent sweeteners known": "ניסיוני; מבין הממתיקים החזקים הידועים",
    "Extremely limited data; not commercially available": "נתונים מוגבלים ביותר; לא זמין מסחרית",

    # === FD&C/Fermented ===
    "FD&C Red No. 3. E127. FDA ban pending (thyroid tumors in rats).": "FD&C Red No. 3. E127. איסור FDA ממתין (גידולי תריס בחולדות).",
    "Fermented; contains B vitamins; high GI; traditionally consumed warm": "מותסס; מכיל ויטמיני B; אינדקס גליקמי גבוה; נצרך חם באופן מסורתי",

    # === Fishy/Flushing ===
    "Fishy body odor; Sweating; GI distress; Hypotension; Hepatotoxicity": "ריח גוף דגי; הזעה; מצוקת מערכת עיכול; לחץ דם נמוך; רעילות כבדית",
    "Fishy burps, GI discomfort, loose stools; increased bleeding risk at high doses": "גיהוקים דגיים, אי נוחות במערכת העיכול, צואה רכה; סיכון מוגבר לדימום במינונים גבוהים",
    "Fishy burps; GI upset; Increased bleeding time; Possible LDL increase; Immunosuppression at very high doses": "גיהוקים דגיים; הפרעת מערכת עיכול; זמן דימום מוגבר; עלייה אפשרית ב-LDL; דיכוי חיסוני במינונים גבוהים מאוד",
    "Flushing (nicotinic acid); Liver damage; Hyperglycemia; GI distress": "סמקה (חומצה ניקוטינית); נזק לכבד; היפרגליקמיה; מצוקת מערכת עיכול",
    "Flushing, itching, GI upset (nicotinic acid form); hepatotoxicity at very high doses": "סמקה, גרד, הפרעת מערכת עיכול (צורת חומצה ניקוטינית); רעילות כבדית במינונים גבוהים מאוד",
    "Flushing; Hepatotoxicity; GI upset; Hyperglycemia": "סמקה; רעילות כבדית; הפרעת מערכת עיכול; היפרגליקמיה",

    # === GI concerns ===
    "GI concerns at high doses; gut microbiome disruption in animal studies": "חששות מערכת עיכול במינונים גבוהים; שיבוש מיקרוביום המעי במחקרי בעלי חיים",
    "GI concerns debated; often avoided in clean-label": "חששות מערכת עיכול שנויים במחלוקת; לעיתים נמנע בתיוג נקי",
    "GI discomfort (less frequent per claims)": "אי נוחות במערכת העיכול (פחות תכוף לפי הטענות)",
    "GI discomfort (less than monohydrate per marketing claims)": "אי נוחות במערכת העיכול (פחות ממונוהידרט לפי טענות שיווקיות)",
    "GI discomfort (nausea, diarrhea), unpleasant taste": "אי נוחות במערכת העיכול (בחילה, שלשול), טעם לא נעים",
    "GI discomfort at high doses; individual AA interactions": "אי נוחות במערכת העיכול במינונים גבוהים; אינטראקציות חומצות אמינו בודדות",
    "GI discomfort at high doses; theoretical tryptophan competition": "אי נוחות במערכת העיכול במינונים גבוהים; תחרות תיאורטית עם טריפטופן",
    "GI discomfort, bloating; milk allergy risk": "אי נוחות במערכת העיכול, נפיחות; סיכון לאלרגיה לחלב",
    "GI discomfort, diarrhea; contamination risk": "אי נוחות במערכת העיכול, שלשול; סיכון זיהום",
    "GI discomfort, drowsiness; liver injury reported (rare); thyroid hormone alteration": "אי נוחות במערכת העיכול, ישנוניות; דווח על פגיעה בכבד (נדיר); שינוי הורמוני תריס",
    "GI discomfort, electrolyte imbalance at high doses, salty taste": "אי נוחות במערכת העיכול, חוסר איזון אלקטרוליטים במינונים גבוהים, טעם מלוח",
    "GI discomfort, fishy body odor, diarrhea at high doses": "אי נוחות במערכת העיכול, ריח גוף דגי, שלשול במינונים גבוהים",
    "GI discomfort, fishy odor (betaine)": "אי נוחות במערכת העיכול, ריח דגי (בטאין)",
    "GI discomfort, fishy taste": "אי נוחות במערכת העיכול, טעם דגי",
    "GI discomfort, gas": "אי נוחות במערכת העיכול, גזים",
    "GI discomfort, headache; anti-androgenic": "אי נוחות במערכת העיכול, כאב ראש; אנטי-אנדרוגני",
    "GI discomfort, headache; may darken urine": "אי נוחות במערכת העיכול, כאב ראש; עלול להכהות שתן",
    "GI discomfort, headache; shellfish allergy (if shellfish-derived)": "אי נוחות במערכת העיכול, כאב ראש; אלרגיה לרכיכות (אם מופק מרכיכות)",
    "GI discomfort, heartburn, decreased appetite": "אי נוחות במערכת העיכול, צרבת, ירידה בתיאבון",
    "GI discomfort, insomnia, fishy odor": "אי נוחות במערכת העיכול, נדודי שינה, ריח דגי",
    "GI discomfort, maple syrup-like body odor, diarrhea": "אי נוחות במערכת העיכול, ריח גוף דמוי סירופ מייפל, שלשול",
    "GI discomfort, nausea if taken without fluid": "אי נוחות במערכת העיכול, בחילה אם נלקח ללא נוזל",
    "GI discomfort, nausea, diarrhea; rare: anaphylactoid reactions": "אי נוחות במערכת העיכול, בחילה, שלשול; נדיר: תגובות אנפילקטואידיות",
    "GI discomfort, skin rash; hypoglycemia risk with diabetes meds": "אי נוחות במערכת העיכול, פריחה בעור; סיכון להיפוגליקמיה עם תרופות סוכרת",
    "GI discomfort, sweating; may affect blood sugar": "אי נוחות במערכת העיכול, הזעה; עלול להשפיע על סוכר בדם",
    "GI discomfort, vivid dreams (B6), drowsiness": "אי נוחות במערכת העיכול, חלומות חיים (B6), ישנוניות",
    "GI discomfort; concern for thyroid function (glucosinolates)": "אי נוחות במערכת העיכול; חשש לתפקוד תריס (גלוקוזינולטים)",
    "GI discomfort; contamination risk (heavy metals, microcystin)": "אי נוחות במערכת העיכול; סיכון זיהום (מתכות כבדות, מיקרוציסטין)",
    "GI discomfort; contamination risk with growth factors": "אי נוחות במערכת העיכול; סיכון זיהום בגורמי גדילה",
    "GI discomfort; converts to creatinine faster than monohydrate": "אי נוחות במערכת העיכול; מומר לקריאטינין מהר יותר ממונוהידרט",
    "GI discomfort; high sodium": "אי נוחות במערכת העיכול; נתרן גבוה",
    "GI discomfort; high sugar in juice form": "אי נוחות במערכת העיכול; סוכר גבוה בצורת מיץ",
    "GI discomfort; hypocalcemia at very high doses": "אי נוחות במערכת העיכול; היפוקלצמיה במינונים גבוהים מאוד",
    "GI discomfort; incomplete amino acid profile": "אי נוחות במערכת העיכול; פרופיל חומצות אמינו לא שלם",
    "GI discomfort; limited evidence of superiority over maltodextrin": "אי נוחות במערכת העיכול; ראיות מוגבלות לעדיפות על מלטודקסטרין",
    "GI discomfort; limited oral bioavailability": "אי נוחות במערכת העיכול; זמינות ביולוגית דרך הפה מוגבלת",
    "GI discomfort; lower bioavailability than L-tyrosine": "אי נוחות במערכת העיכול; זמינות ביולוגית נמוכה מ-L-טירוזין",
    "GI discomfort; lower sodium than sports drinks": "אי נוחות במערכת העיכול; נתרן נמוך ממשקאות ספורט",
    "GI discomfort; not a complete protein (lacks tryptophan)": "אי נוחות במערכת העיכול; לא חלבון שלם (חסר טריפטופן)",
    "GI discomfort; one case report of harm from unverified product": "אי נוחות במערכת העיכול; דוח מקרה אחד של נזק ממוצר לא מאומת",
    "GI discomfort; potential blood pressure reduction": "אי נוחות במערכת העיכול; הפחתת לחץ דם אפשרית",
    "GI discomfort; quality varies (some derived from collagen, not muscle)": "אי נוחות במערכת העיכול; איכות משתנה (חלק מופק מקולגן, לא מרקמת שריר)",
    "GI discomfort; rare: skin rash in sensitive individuals": "אי נוחות במערכת העיכול; נדיר: פריחה בעור באנשים רגישים",
    "GI distress, nausea at high intake without adaptation": "מצוקת מערכת עיכול, בחילה בצריכה גבוהה ללא הסתגלות",
    "GI distress; Nausea/vomiting; Constipation; Hemochromatosis; Organ damage (liver/heart); Grey skin": "מצוקת מערכת עיכול; בחילה/הקאה; עצירות; המוכרומטוזיס; נזק לאיברים (כבד/לב); עור אפרפר",
    "GI inflammation debate; most studied for adverse effects": "ויכוח על דלקת במערכת העיכול; הנחקר ביותר להשפעות שליליות",
    "GI inflammation; intestinal lesions; colon cancer in lab; FDA ban petition; removed from USDA organic 2016": "דלקת במערכת העיכול; נגעים במעי; סרטן מעי גס במעבדה; עצומת איסור FDA; הוסר מאורגני USDA 2016",
    "GI irritation at high doses; alters drug metabolism": "גירוי מערכת העיכול במינונים גבוהים; משנה מטבוליזם תרופות",
    "GI irritation, heartburn if taken without food": "גירוי מערכת העיכול, צרבת אם נלקח ללא אוכל",
    "GI reference (100); rapid blood sugar spike; promotes dental caries": "אינדקס גליקמי ייחוס (100); עליית סוכר מהירה בדם; מקדם עששת",
    "GI upset, hair loss, nail brittleness, selenosis at excess": "הפרעת מערכת עיכול, נשירת שיער, שבריריות ציפורניים, סלנוזיס בעודף",
    "GI upset, liver damage at chronic excess": "הפרעת מערכת עיכול, נזק לכבד בעודף כרוני",
    "GI upset; potential for excess if combined with fortified foods": "הפרעת מערכת עיכול; פוטנציאל לעודף בשילוב עם מזונות מועשרים",
    "Gas, bloating initially; rare infections in immunocompromised": "גזים, נפיחות בהתחלה; זיהומים נדירים במדוכאי חיסון",

    # === Gastrointestinal/General ===
    "Gastrointestinal irritation (nausea, vomiting, diarrhea) at high doses": "גירוי מערכת העיכול (בחילה, הקאה, שלשול) במינונים גבוהים",
    "Gastrointestinal toxicity (nausea, vomiting, diarrhea); neurological effects (confusion, headache); hemolytic activity at high doses": "רעילות מערכת העיכול (בחילה, הקאה, שלשול); השפעות נוירולוגיות (בלבול, כאב ראש); פעילות המוליטית במינונים גבוהים",
    "Gastrointestinal toxicity; immunotoxicity; neurotoxicity; genotoxicity": "רעילות מערכת העיכול; רעילות חיסונית; רעילות עצבית; רעילות גנטית",
    "General antioxidant category; most are safe": "קטגוריית נוגדי חמצון כללית; רובם בטוחים",
    "General dairy ingredients; contains allergens": "מרכיבי חלב כלליים; מכיל אלרגנים",
    "General emulsifier category; safety depends on specific compound": "קטגוריית מתחלב כללית; הבטיחות תלויה בתרכובת הספציפית",
    "General food coloring; some artificial colors linked to hyperactivity": "צביעת מזון כללית; חלק מהצבעים המלאכותיים קשורים להיפראקטיביות",
    "General preservative category; safety depends on specific compound": "קטגוריית משמר כללית; הבטיחות תלויה בתרכובת הספציפית",
    "General term for sugars; excessive intake linked to obesity and diabetes": "מונח כללי לסוכרים; צריכה מופרזת קשורה להשמנה וסוכרת",
    "Generally considered safe; rare contact dermatitis": "נחשב בטוח בדרך כלל; דרמטיטיס מגע נדירה",
    "Generally considered safer than folic acid; Fewer masking concerns": "נחשב בטוח יותר מחומצה פולית; פחות חששות הסוואה",
    "Generally low-risk; ultra-processing concerns": "סיכון נמוך בדרך כלל; חששות עיבוד-יתר",
    "Generally recognized as safe. Environmental concerns.": "מוכר בדרך כלל כבטוח. חששות סביבתיים.",
    "Generally recognized as safe. Excessive consumption linked to hypertension.": "מוכר בדרך כלל כבטוח. צריכה מופרזת קשורה ליתר לחץ דם.",
    "Generally recognized as safe. Excessive consumption linked to obesity and diabetes.": "מוכר בדרך כלל כבטוח. צריכה מופרזת קשורה להשמנה וסוכרת.",
    "Generally recognized as safe. Excessive consumption linked to obesity.": "מוכר בדרך כלל כבטוח. צריכה מופרזת קשורה להשמנה.",
    "Generally recognized as safe. Excessive consumption may affect liver metabolism.": "מוכר בדרך כלל כבטוח. צריכה מופרזת עלולה להשפיע על מטבוליזם הכבד.",
    "Generally safe (vitamin C derivative); benzene risk with sodium benzoate": "בטוח בדרך כלל (נגזרת ויטמין C); סיכון בנזן עם נתרן בנזואט",
    "Generally safe at approved levels": "בטוח בדרך כלל ברמות מאושרות",
    "Generally safe topically, limited food use": "בטוח בדרך כלל במריחה, שימוש מוגבל במזון",

    # === Generally safe, [compound] — batch ===
    "Generally safe, B vitamin form": "בטוח בדרך כלל, צורת ויטמין B",
    "Generally safe, S-allyl cysteine": "בטוח בדרך כלל, S-אליל ציסטאין",
    "Generally safe, acetic acid salt": "בטוח בדרך כלל, מלח חומצה אצטית",
    "Generally safe, allicin": "בטוח בדרך כלל, אליצין",
    "Generally safe, amino sulfonic acid": "בטוח בדרך כלל, חומצה אמינו סולפונית",
    "Generally safe, annatto": "בטוח בדרך כלל, אנאטו",
    "Generally safe, anthocyanosides": "בטוח בדרך כלל, אנתוציאנוזידים",
    "Generally safe, antimicrobial": "בטוח בדרך כלל, אנטי-מיקרוביאלי",
    "Generally safe, antimicrobial fatty acid": "בטוח בדרך כלל, חומצת שומן אנטי-מיקרוביאלית",
    "Generally safe, ascaridole": "בטוח בדרך כלל, אסקרידול",
    "Generally safe, aspalathin": "בטוח בדרך כלל, אספלטין",
    "Generally safe, avenanthramides": "בטוח בדרך כלל, אוונאנתרמידים",
    "Generally safe, bacteriocin peptide": "בטוח בדרך כלל, פפטיד בקטריוצין",
    "Generally safe, bee resin": "בטוח בדרך כלל, שרף דבורים",
    "Generally safe, bee secretion": "בטוח בדרך כלל, הפרשת דבורים",
    "Generally safe, betulin": "בטוח בדרך כלל, בטולין",
    "Generally safe, bromelain": "בטוח בדרך כלל, ברומלאין",
    "Generally safe, brown algae": "בטוח בדרך כלל, אצות חומות",
    "Generally safe, browning products": "בטוח בדרך כלל, תוצרי השחמה",
    "Generally safe, carotenoids": "בטוח בדרך כלל, קרוטנואידים",
    "Generally safe, carvacrol": "בטוח בדרך כלל, קרבקרול",
    "Generally safe, carvone": "בטוח בדרך כלל, קרוון",
    "Generally safe, cationic polypeptide": "בטוח בדרך כלל, פוליפפטיד קטיוני",
    "Generally safe, chlorogenic acids": "בטוח בדרך כלל, חומצות כלורוגניות",
    "Generally safe, chlorophyll": "בטוח בדרך כלל, כלורופיל",
    "Generally safe, cinnamaldehyde": "בטוח בדרך כלל, קינמאלדהיד",
    "Generally safe, cinnamon component": "בטוח בדרך כלל, מרכיב קינמון",
    "Generally safe, citrus flavonoid": "בטוח בדרך כלל, פלבנואיד הדרים",
    "Generally safe, citrus flavonoids": "בטוח בדרך כלל, פלבנואידי הדרים",
    "Generally safe, citrus oil component": "בטוח בדרך כלל, מרכיב שמן הדרים",
    "Generally safe, clove oil component": "בטוח בדרך כלל, מרכיב שמן ציפורן",
    "Generally safe, contains acetic acid": "בטוח בדרך כלל, מכיל חומצה אצטית",
    "Generally safe, contains minerals": "בטוח בדרך כלל, מכיל מינרלים",
    "Generally safe, contains monacolins": "בטוח בדרך כלל, מכיל מונקולינים",
    "Generally safe, contains trace minerals": "בטוח בדרך כלל, מכיל מינרלים בכמות עקבית",
    "Generally safe, cuminaldehyde": "בטוח בדרך כלל, קומינאלדהיד",
    "Generally safe, curcuminoids": "בטוח בדרך כלל, כורכומינואידים",
    "Generally safe, delphinidins": "בטוח בדרך כלל, דלפינידינים",
    "Generally safe, dithiol compound": "בטוח בדרך כלל, תרכובת דיתיול",
    "Generally safe, ellagitannins": "בטוח בדרך כלל, אלגיטנינים",
    "Generally safe, enzyme from egg white": "בטוח בדרך כלל, אנזים מחלבון ביצה",
    "Generally safe, estragole": "בטוח בדרך כלל, אסטרגול",
    "Generally safe, eucalyptol": "בטוח בדרך כלל, אוקליפטול",
    "Generally safe, flavan-3-ol": "בטוח בדרך כלל, פלבן-3-אול",
    "Generally safe, flavanols": "בטוח בדרך כלל, פלבנולים",
    "Generally safe, flavonoid glycoside": "בטוח בדרך כלל, גליקוזיד פלבנואיד",
    "Generally safe, flavonoid pigments": "בטוח בדרך כלל, פיגמנטי פלבנואיד",
    "Generally safe, fruit fiber": "בטוח בדרך כלל, סיבי פרי",
    "Generally safe, ginsenosides": "בטוח בדרך כלל, ג'ינסנוזידים",
    "Generally safe, glutamate source": "בטוח בדרך כלל, מקור גלוטמט",
    "Generally safe, glycyrrhizin": "בטוח בדרך כלל, גליצירהיזין",
    "Generally safe, hesperidin": "בטוח בדרך כלל, הספרידין",
    "Generally safe, highly refined": "בטוח בדרך כלל, מזוקק מאוד",
    "Generally safe, hormone": "בטוח בדרך כלל, הורמון",
    "Generally safe, hydrolyzable tannin": "בטוח בדרך כלל, טנין הניתן להידרוליזה",
    "Generally safe, hydroxytyrosol": "בטוח בדרך כלל, הידרוקסיטירוזול",
    "Generally safe, inert mineral": "בטוח בדרך כלל, מינרל אינרטי",
    "Generally safe, insect secretion": "בטוח בדרך כלל, הפרשת חרקים",
    "Generally safe, intoxicating": "בטוח בדרך כלל, משכר",
    "Generally safe, inulin": "בטוח בדרך כלל, אינולין",
    "Generally safe, lactic acid bacteria": "בטוח בדרך כלל, חיידקי חומצה לקטית",
    "Generally safe, lactose content": "בטוח בדרך כלל, תכולת לקטוז",
    "Generally safe, legume seed": "בטוח בדרך כלל, זרע קטנית",
    "Generally safe, lipid antioxidant": "בטוח בדרך כלל, נוגד חמצון שומני",
    "Generally safe, lutein": "בטוח בדרך כלל, לוטאין",
    "Generally safe, lycopene": "בטוח בדרך כלל, ליקופן",
    "Generally safe, lysine": "בטוח בדרך כלל, ליזין",
    "Generally safe, macamides": "בטוח בדרך כלל, מקמידים",
    "Generally safe, mangiferin": "בטוח בדרך כלל, מנגיפרין",
    "Generally safe, marine carotenoid": "בטוח בדרך כלל, קרוטנואיד ימי",
    "Generally safe, menthol": "בטוח בדרך כלל, מנטול",
    "Generally safe, methyl salicylate": "בטוח בדרך כלל, מתיל סליצילט",
    "Generally safe, methylglyoxal": "בטוח בדרך כלל, מתילגליאוקסל",
    "Generally safe, milk protein": "בטוח בדרך כלל, חלבון חלב",
    "Generally safe, mineral source": "בטוח בדרך כלל, מקור מינרלי",
    "Generally safe, mushroom sugar": "בטוח בדרך כלל, סוכר פטריות",
    "Generally safe, myristicin": "בטוח בדרך כלל, מיריסטיצין",
    "Generally safe, naringin": "בטוח בדרך כלל, נרינגין",
    "Generally safe, nasunin": "בטוח בדרך כלל, נסונין",
    "Generally safe, nattokinase": "בטוח בדרך כלל, נטוקינאז",
    "Generally safe, natural milk enzyme system": "בטוח בדרך כלל, מערכת אנזימי חלב טבעית",
    "Generally safe, natural sweetener": "בטוח בדרך כלל, ממתיק טבעי",
    "Generally safe, natural wood smoke": "בטוח בדרך כלל, עשן עץ טבעי",
    "Generally safe, nucleoside": "בטוח בדרך כלל, נוקלאוזיד",
    "Generally safe, oligomeric flavonoids": "בטוח בדרך כלל, פלבנואידים אוליגומריים",
    "Generally safe, omega-3": "בטוח בדרך כלל, אומגה-3",
    "Generally safe, omega-7": "בטוח בדרך כלל, אומגה-7",
    "Generally safe, oregano/thyme": "בטוח בדרך כלל, אורגנו/קורנית",
    "Generally safe, organic acids": "בטוח בדרך כלל, חומצות אורגניות",
    "Generally safe, oryzanol": "בטוח בדרך כלל, אוריזנול",
    "Generally safe, palm wax": "בטוח בדרך כלל, שעוות דקל",
    "Generally safe, papain": "בטוח בדרך כלל, פפאין",
    "Generally safe, peptide fragment": "בטוח בדרך כלל, שבר פפטידי",
    "Generally safe, phenolics": "בטוח בדרך כלל, פנוליות",
    "Generally safe, phycocyanin": "בטוח בדרך כלל, פיקוציאנין",
    "Generally safe, piperine": "בטוח בדרך כלל, פיפרין",
    "Generally safe, plant wax": "בטוח בדרך כלל, שעוות צמחים",
    "Generally safe, polysaccharide": "בטוח בדרך כלל, פוליסכריד",
    "Generally safe, probiotic": "בטוח בדרך כלל, פרוביוטי",
    "Generally safe, protein pigment": "בטוח בדרך כלל, פיגמנט חלבוני",
    "Generally safe, rosavins": "בטוח בדרך כלל, רוזווינים",
    "Generally safe, rutin": "בטוח בדרך כלל, רוטין",
    "Generally safe, salicin": "בטוח בדרך כלל, סליצין",
    "Generally safe, seaweed extract": "בטוח בדרך כלל, תמצית אצות",
    "Generally safe, sesamol/sesamolin": "בטוח בדרך כלל, ססמול/ססמולין",
    "Generally safe, shellfish derivative": "בטוח בדרך כלל, נגזרת רכיכות",
    "Generally safe, silymarin": "בטוח בדרך כלל, סילימרין",
    "Generally safe, squalene": "בטוח בדרך כלל, סקוואלן",
    "Generally safe, sulforaphane": "בטוח בדרך כלל, סולפורפן",
    "Generally safe, terpenes": "בטוח בדרך כלל, טרפנים",
    "Generally safe, theaflavins": "בטוח בדרך כלל, תיאפלבינים",
    "Generally safe, thymol": "בטוח בדרך כלל, תימול",
    "Generally safe, tree exudate": "בטוח בדרך כלל, הפרשת עץ",
    "Generally safe, trihydroxybenzoic acid": "בטוח בדרך כלל, חומצה טריהידרוקסיבנזואית",
    "Generally safe, tripeptide": "בטוח בדרך כלל, טריפפטיד",
    "Generally safe, triterpene": "בטוח בדרך כלל, טריטרפן",
    "Generally safe, valerenic acid": "בטוח בדרך כלל, חומצה ולריאנית",
    "Generally safe, vitamin C derivative": "בטוח בדרך כלל, נגזרת ויטמין C",
    "Generally safe, vitamin E": "בטוח בדרך כלל, ויטמין E",
    "Generally safe, zeaxanthin": "בטוח בדרך כלל, זאקסנטין",

    # === Generally safe; [detail] ===
    "Generally safe; Mild nausea at high doses; Flushing is rare": "בטוח בדרך כלל; בחילה קלה במינונים גבוהים; סמקה נדירה",
    "Generally safe; Possible increased prostate cancer risk debated (high-dose studies); GI distress": "בטוח בדרך כלל; סיכון מוגבר לסרטן ערמונית שנוי במחלוקת (מחקרי מינון גבוה); מצוקת מערכת עיכול",
    "Generally safe; amino acid": "בטוח בדרך כלל; חומצת אמינו",
    "Generally safe; antacid use": "בטוח בדרך כלל; שימוש כנוגד חומצה",
    "Generally safe; common buffering agent": "בטוח בדרך כלל; חומר חוצץ נפוץ",
    "Generally safe; delisted for technical reasons": "בטוח בדרך כלל; הוסר מהרשימה מסיבות טכניות",
    "Generally safe; essential amino acid": "בטוח בדרך כלל; חומצת אמינו חיונית",
    "Generally safe; high doses may be nephrotoxic": "בטוח בדרך כלל; מינונים גבוהים עלולים להיות רעילים לכליות",
    "Generally safe; may cause skin allergies": "בטוח בדרך כלל; עלול לגרום אלרגיות עור",
    "Generally safe; may reduce drug absorption": "בטוח בדרך כלל; עלול להפחית ספיגת תרופות",
    "Generally safe; natural fruit acid": "בטוח בדרך כלל; חומצת פרי טבעית",
    "Generally safe; potassium source": "בטוח בדרך כלל; מקור אשלגן",
    "Generally safe; rare allergies; ethylene oxide contamination concern": "בטוח בדרך כלל; אלרגיות נדירות; חשש זיהום אתילן אוקסיד",
    "Generally safe; rare bloating; NEC concern in premature infants": "בטוח בדרך כלל; נפיחות נדירה; חשש NEC בפגים",
    "Generally safe; slow acidifier": "בטוח בדרך כלל; מחמצן איטי",
    "Generally safe; sulfite-sensitive individuals should be cautious": "בטוח בדרך כלל; אנשים רגישים לסולפיטים צריכים להיזהר",
    "Generally safe; toxicity at very high doses": "בטוח בדרך כלל; רעילות במינונים גבוהים מאוד",
    "Generally safe; used to treat kidney stones": "בטוח בדרך כלל; משמש לטיפול באבני כליות",
    "Generally very safe; Kidney stones at extremely high doses (theoretical)": "בטוח מאוד בדרך כלל; אבני כליות במינונים גבוהים ביותר (תיאורטי)",
    "Generally very safe; Mild GI upset at high doses; Possible insomnia; May reduce warfarin efficacy": "בטוח מאוד בדרך כלל; הפרעת מערכת עיכול קלה במינונים גבוהים; נדודי שינה אפשריים; עלול להפחית יעילות וורפרין",
    "Generally well-tolerated; mild drowsiness possible": "נסבל היטב בדרך כלל; ישנוניות קלה אפשרית",
    "Generally well-tolerated; no significant adverse effects reported": "נסבל היטב בדרך כלל; לא דווח על תופעות לוואי משמעותיות",
    "Generally well-tolerated; rare GI discomfort at very high doses": "נסבל היטב בדרך כלל; אי נוחות במערכת העיכול נדירה במינונים גבוהים מאוד",
    "Generally well-tolerated; rare kidney/liver concerns at high doses": "נסבל היטב בדרך כלל; חששות כליות/כבד נדירים במינונים גבוהים",
    "Generally well-tolerated; tingling, flushing": "נסבל היטב בדרך כלל; עקצוץ, סמקה",

    # === Generic terms ===
    "Generic label declaration meaning artificial or natural colors added.": "הצהרת תיוג כללית שמשמעותה צבעים מלאכותיים או טבעיים נוספו.",
    "Generic term for FD&C or other synthetic colors.": "מונח כללי לצבעים סינתטיים FD&C או אחרים.",
    "Generic term for added flavor. Could be natural or artificial.": "מונח כללי לטעם מוסף. יכול להיות טבעי או מלאכותי.",

    # === Genotoxicity ===
    "Genotoxicity at high concentrations; generally safe at ADI; anti-inflammatory potential": "רעילות גנטית בריכוזים גבוהים; בטוח בדרך כלל ב-ADI; פוטנציאל אנטי-דלקתי",
    "Genotoxicity; carcinogenicity (multiple organs in rodents)": "רעילות גנטית; סרטנות (מספר איברים במכרסמים)",
    "Genotoxicity; carcinogenicity (via glycidol metabolite)": "רעילות גנטית; סרטנות (דרך מטבוליט גליצידול)",
    "Genotoxicity; estrogenic activity": "רעילות גנטית; פעילות אסטרוגנית",
    "Genotoxicity; estrogenic activity; cytotoxicity": "רעילות גנטית; פעילות אסטרוגנית; רעילות תאית",
    "Genotoxicity; potential carcinogenicity (3+ ring MOAH fraction)": "רעילות גנטית; חשש לסרטנות (פרקציית MOAH בעלת 3+ טבעות)",

    # === Food descriptions ===
    "Glucose syrup from corn starch hydrolysis. High glycemic index.": "סירופ גלוקוז מהידרוליזה של עמילן תירס. אינדקס גליקמי גבוה.",
    "Gluten-free flour. Common in Asian cuisine and GF products.": "קמח ללא גלוטן. נפוץ במטבח האסיאתי ובמוצרים ללא גלוטן.",
    "Gluten-free thickener. Common in processed foods.": "מעבה ללא גלוטן. נפוץ במזונות מעובדים.",
    "Ground wheat. Contains gluten. Major allergen (celiac/wheat allergy).": "חיטה טחונה. מכיל גלוטן. אלרגן מרכזי (צליאק/אלרגיה לחיטה).",
    "Herb. Rich in vitamin K. Common garnish.": "עשב. עשיר בוויטמין K. קישוט נפוץ.",
    "Healthy fruit; rich in fiber and vitamins": "פרי בריא; עשיר בסיבים וויטמינים",
    "Isolated wheat protein. Major allergen for celiac disease.": "חלבון חיטה מבודד. אלרגן מרכזי לצליאק.",
    "Juice from tomatoes. Rich in lycopene.": "מיץ עגבניות. עשיר בליקופן.",
    "Leafy green. High in oxalates, iron, vitamin K.": "ירק עלים. עשיר באוקסלטים, ברזל, ויטמין K.",
    "Liquid smoke. Contains PAHs at low levels.": "עשן נוזלי. מכיל PAHs ברמות נמוכות.",
    "Major allergen (anaphylaxis risk). Legume technically. High in protein, fat.": "אלרגן מרכזי (סיכון אנפילקסיס). טכנית קטנית. עשיר בחלבון ושומן.",
    "Major allergen. Complete protein source. Contains lecithin.": "אלרגן מרכזי. מקור חלבון מלא. מכיל לציטין.",
    "Major allergen. Contains isoflavones (phytoestrogens). Complete protein.": "אלרגן מרכזי. מכיל איזופלבונים (פיטואסטרוגנים). חלבון מלא.",
    "Milk with fat removed. Same protein/calcium as whole milk.": "חלב ללא שומן. אותו חלבון/סידן כמו חלב מלא.",
    "Most traded spice. Contains piperine (bioavailability enhancer).": "התבלין הנסחר ביותר. מכיל פיפרין (משפר זמינות ביולוגית).",
    "Natural acidulant. Rich in vitamin C.": "מחמצן טבעי. עשיר בוויטמין C.",
    "Natural citrus fruit; rich in vitamin C": "פרי הדר טבעי; עשיר בוויטמין C",
    "Natural food coloring from paprika; generally safe": "צבע מזון טבעי מפפריקה; בטוח בדרך כלל",
    "Natural starch from cassava; generally safe": "עמילן טבעי מקסווה; בטוח בדרך כלל",
    "Natural sweetener from sugarcane/beet. 4 kcal/g. WHO recommends <25g/day added sugars.": "ממתיק טבעי מקנה סוכר/סלק. 4 קלוריות/גרם. WHO ממליץ <25 גרם/יום סוכרים מוספים.",
    "Natural vitamin C source, safe": "מקור טבעי לוויטמין C, בטוח",
    "Organic-certified sugar. Same nutritionally as conventional.": "סוכר מאושר אורגנית. זהה תזונתית לרגיל.",
    "Processed cacao. Contains flavanols, theobromine. Antioxidant properties.": "קקאו מעובד. מכיל פלבנולים, תיאוברומין. תכונות נוגדות חמצון.",
    "Pure cocoa mass. Not alcoholic despite name. Base for chocolate.": "מסת קקאו טהורה. לא אלכוהולי למרות השם. בסיס לשוקולד.",
    "Red meat. Complete protein. Contains heme iron.": "בשר אדום. חלבון מלא. מכיל ברזל המי.",
    "Refined peanut oil generally safe for peanut-allergic (proteins removed). Raw is not.": "שמן בוטנים מזוקק בדרך כלל בטוח לאלרגיים לבוטנים (חלבונים הוסרו). גולמי לא.",

    # === Gout ===
    "Gout-like symptoms (elevated uric acid); Copper depletion; GI distress; Diarrhea": "תסמינים דמויי שיגדון (חומצת שתן מוגברת); דלדול נחושת; מצוקת מערכת עיכול; שלשול",
    "Purine content; avoid with gout": "תכולת פורין; להימנע עם שיגדון",
    "Purine content; avoid with gout or hyperuricemia": "תכולת פורין; להימנע עם שיגדון או היפראוריצמיה",
    "Purine content; high uric acid risk for gout patients": "תכולת פורין; סיכון גבוה לחומצת שתן בחולי שיגדון",

    # === Gut/Microbiome ===
    "Gut microbiome disruption in animal and human studies; may promote inflammation": "שיבוש מיקרוביום המעי במחקרי בעלי חיים ובני אדם; עלול לקדם דלקת",
    "Intestinal inflammation; alters gut microbiota; increases permeability": "דלקת מעי; משנה מיקרוביוטת המעי; מגביר חדירות",
    "Intestinal inflammation; metabolic syndrome in animals; gut dysbiosis": "דלקת מעי; תסמונת מטבולית בבעלי חיים; דיסביוזיס מעי",
    "Inhibits gut bacteria; previously linked to bladder cancer; Weizmann: glucose intolerance": "מעכב חיידקי מעי; בעבר קשור לסרטן שלפוחית; מכון ויצמן: אי סבילות לגלוקוז",
    "Inhibits gut bacterial communication; BGU: disrupts microbiome; NutriNet-Sante: cancer risk": "מעכב תקשורת חיידקי מעי; אוניברסיטת בן גוריון: משבש מיקרוביום; NutriNet-Sante: סיכון לסרטן",
    "May promote bacterial encroachment into mucus layer; increased LPS in animal studies": "עלול לקדם חדירת חיידקים לשכבת הריר; עליית LPS במחקרי בעלי חיים",
    "Metabolic disorder and gut dysbiosis in animal studies; EFSA re-evaluation ongoing": "הפרעה מטבולית ודיסביוזיס מעי במחקרי בעלי חיים; הערכה מחדש של EFSA מתבצעת",

    # === Gynecomastia/Headache ===
    "Gynecomastia, liver damage, cardiovascular risks, hormonal disruption": "גינקומסטיה, נזק לכבד, סיכונים קרדיווסקולריים, שיבוש הורמונלי",
    "Headache, dizziness, GI discomfort": "כאב ראש, סחרחורת, אי נוחות במערכת העיכול",
    "Headache, dizziness, GI discomfort; fishy body odor": "כאב ראש, סחרחורת, אי נוחות במערכת העיכול; ריח גוף דגי",
    "Headache, muscle tension, insomnia; teratogenic concerns in animal studies": "כאב ראש, מתח שרירים, נדודי שינה; חששות טרטוגניים במחקרי בעלי חיים",
    "Headache, sleep disturbances, GI disorders; estrogenic effects possible": "כאב ראש, הפרעות שינה, הפרעות מערכת עיכול; השפעות אסטרוגניות אפשריות",
    "Headache, sweating; milder stimulant than caffeine": "כאב ראש, הזעה; ממריץ מתון יותר מקפאין",
    "Headache; Liver damage; Birth defects; Bone loss; Skin desquamation": "כאב ראש; נזק לכבד; מומים מולדים; אובדן עצם; קילוף עור",

    # === Heat/Hematotoxicity ===
    "Heat stable protein sweetener; limited safety data": "ממתיק חלבוני יציב בחום; נתוני בטיחות מוגבלים",
    "Heat-stable sweet protein; potential next-gen sweetener": "חלבון מתוק יציב בחום; ממתיק דור הבא פוטנציאלי",
    "Hematotoxicity; immunotoxicity; dermatotoxicity (alimentary toxic aleukia); growth retardation": "רעילות המטולוגית; רעילות חיסונית; רעילות עורית (אלוקיה רעילה תזונתית); עיכוב גדילה",

    # === Hepatic ===
    "Hepatic angiosarcoma; hepatotoxicity; carcinogenicity": "אנגיוסרקומה כבדית; רעילות כבדית; סרטנות",
    "Hepatocellular carcinoma; acute aflatoxicosis; immunosuppression; growth impairment (children)": "קרצינומה כבדית; אפלטוקסיקוזיס חריפה; דיכוי חיסוני; פגיעה בגדילה (ילדים)",
    "Hepatocellular carcinoma; immunosuppression; mutagenicity": "קרצינומה כבדית; דיכוי חיסוני; מוטגניות",
    "Hepatotoxicity (veno-occlusive disease); genotoxicity; carcinogenicity": "רעילות כבדית (מחלה ונו-אוקלוסיבית); רעילות גנטית; סרטנות",
    "Hepatotoxicity (veno-occlusive disease); genotoxicity; carcinogenicity (liver)": "רעילות כבדית (מחלה ונו-אוקלוסיבית); רעילות גנטית; סרטנות (כבד)",
    "Hepatotoxicity at very high doses (>3g/day); Nausea": "רעילות כבדית במינונים גבוהים מאוד (>3 גרם/יום); בחילה",
    "Hepatotoxicity, hypervitaminosis A at chronic high doses; teratogenic": "רעילות כבדית, היפרויטמינוזיס A במינונים כרוניים גבוהים; טרטוגני",
    "Hepatotoxicity; carcinogenicity (liver, kidney, lung); genotoxicity": "רעילות כבדית; סרטנות (כבד, כליה, ריאה); רעילות גנטית",
    "Hepatotoxicity; immunotoxicity; bioaccumulation": "רעילות כבדית; רעילות חיסונית; הצטברות ביולוגית",
    "Hepatotoxicity; immunotoxicity; thyroid disease; kidney cancer; testicular cancer": "רעילות כבדית; רעילות חיסונית; מחלת תריס; סרטן כליה; סרטן אשכים",
    "Hepatotoxicity; nephrotoxicity; liver cancer in animals": "רעילות כבדית; רעילות כלייתית; סרטן כבד בבעלי חיים",
    "Hepatotoxicity; nephrotoxicity; neural tube defect risk": "רעילות כבדית; רעילות כלייתית; סיכון למומי צינור עצבי",
    "Hepatotoxicity; nephrotoxicity; thyroid disruption; potential carcinogenicity": "רעילות כבדית; רעילות כלייתית; שיבוש תריס; חשש לסרטנות",
    "Hepatotoxicity; potential carcinogenicity (sulfotransferase-mediated metabolite)": "רעילות כבדית; חשש לסרטנות (מטבוליט בתיווך סולפוטרנספראז)",
    "Hepatotoxicity; potential liver carcinogenicity": "רעילות כבדית; חשש לסרטנות כבדית",
    "Hepatotoxicity; thyroid disruption; potential carcinogenicity; endocrine disruption": "רעילות כבדית; שיבוש תריס; חשש לסרטנות; שיבוש אנדוקריני",

    # === High GI/fiber ===
    "High GI (95-136); blood sugar spikes; suppresses beneficial gut bacteria": "אינדקס גליקמי גבוה (95-136); עליות חדות בסוכר הדם; מדכא חיידקי מעי מועילים",
    "High GI; arsenic concerns from rice; fructose-free": "אינדקס גליקמי גבוה; חששות ארסן מאורז; ללא פרוקטוז",
    "High GI; contributes to obesity; not same as HFCS (lower fructose)": "אינדקס גליקמי גבוה; תורם להשמנה; לא זהה ל-HFCS (פחות פרוקטוז)",
    "High GI; primarily used as texturizer rather than sweetener": "אינדקס גליקמי גבוה; משמש בעיקר כחומר מרקם ולא כממתיק",
    "High fiber; low GI; rich in minerals; traditional indigenous food": "סיבים גבוהים; אינדקס גליקמי נמוך; עשיר במינרלים; מזון ילידי מסורתי",
    "High sugar content; GI discomfort": "תכולת סוכר גבוהה; אי נוחות במערכת העיכול",
    "High-dose supplements linked to lung cancer in smokers; safe in food": "תוספים במינון גבוה קשורים לסרטן ריאות במעשנים; בטוח במזון",
    "Highest GI among sugar alcohols (35); laxative >25-30g/day; closest texture to sucrose": "אינדקס גליקמי גבוה ביותר בין סוכרי הכהל (35); משלשל >25-30 גרם/יום; המרקם הקרוב ביותר לסוכרוז",

    # === Hyperactivity/Hyper conditions ===
    "Hyperactivity; DNA damage; contains benzidine (carcinogen) at low levels": "היפראקטיביות; נזק ל-DNA; מכיל בנזידין (מסרטן) ברמות נמוכות",
    "Hyperactivity; kidney/adrenal tumors; 2014 Israeli M&M lawsuit (5x permitted levels)": "היפראקטיביות; גידולי כליות/אדרנל; תביעת M&M ישראלית 2014 (פי 5 מהמותר)",
    "Hypercalcemia; Kidney damage; Soft tissue calcification; Nausea; Arrhythmias": "היפרקלצמיה; נזק לכליות; הסתיידות רקמות רכות; בחילה; הפרעות קצב",
    "Hypercalcemia; Kidney stones; Constipation; Impaired iron/zinc absorption; Vascular calcification": "היפרקלצמיה; אבני כליות; עצירות; פגיעה בספיגת ברזל/אבץ; הסתיידות כלי דם",
    "Hyperchloremia; Usually tied to excess sodium intake; Metabolic acidosis": "היפרכלורמיה; בדרך כלל קשור לצריכת נתרן מופרזת; חמצת מטבולית",
    "Hyperkalemia at excess; GI discomfort": "היפרקלמיה בעודף; אי נוחות במערכת העיכול",
    "Hyperkalemia; Cardiac arrest; Nausea; Tingling; Dangerous with renal impairment": "היפרקלמיה; דום לב; בחילה; עקצוץ; מסוכן עם אי ספיקת כליות",
    "Hyperphosphatemia; Calcification of tissues; Impaired calcium metabolism; Secondary hyperparathyroidism": "היפרפוספטמיה; הסתיידות רקמות; פגיעה במטבוליזם סידן; היפרפאראתירואידיזם משני",
    "Hypertension risk at high doses (>100mg glycyrrhizic acid/day); hypokalemia": "סיכון ליתר לחץ דם במינונים גבוהים (>100 מ\"ג חומצה גליצירהיזית/יום); היפוקלמיה",
    "Hypertension with chronic excess; edema": "יתר לחץ דם עם עודף כרוני; בצקת",
    "Hypertension, tachycardia, stroke, cardiac arrest, death": "יתר לחץ דם, טכיקרדיה, שבץ, דום לב, מוות",
    "Hypertension, tachycardia, stroke, heart attack, death": "יתר לחץ דם, טכיקרדיה, שבץ, התקף לב, מוות",
    "Hypertension; Edema; Stroke risk; Kidney damage; Stomach cancer risk": "יתר לחץ דם; בצקת; סיכון לשבץ; נזק לכליות; סיכון לסרטן קיבה",
    "Hypertensive crisis (especially with MAO inhibitor drugs); headache; migraine": "משבר יתר לחץ דם (במיוחד עם תרופות מעכבות MAO); כאב ראש; מיגרנה",
    "Hyperthyroidism; liver enlargement; may vaporize from packaging into food": "יתר פעילות תריס; הגדלת כבד; עלול להתאדות מאריזה למזון",
    "Hypoglycemia, headache, edema, joint pain": "היפוגליקמיה, כאב ראש, בצקת, כאבי מפרקים",

    # === IARC/Immuno ===
    "IARC 2B since 1999; kidney cancer; banned in EU, UK, Canada, Brazil": "IARC 2B מאז 1999; סרטן כליה; אסור באיחוד האירופי, בריטניה, קנדה, ברזיל",
    "IARC possible carcinogen; NTP reasonably anticipated carcinogen; California carcinogen since 1990": "IARC מסרטן אפשרי; NTP מסרטן צפוי סבירה; מסרטן בקליפורניה מאז 1990",
    "Immunostimulatory properties reported; limited safety data": "דווח על תכונות ממריצות חיסון; נתוני בטיחות מוגבלים",
    "Immunotoxicity; developmental effects; thyroid disruption": "רעילות חיסונית; השפעות התפתחותיות; שיבוש תריס",
    "Immunotoxicity; hematotoxicity; GI toxicity (more toxic than DON in some models)": "רעילות חיסונית; רעילות המטולוגית; רעילות מערכת עיכול (רעיל יותר מ-DON בחלק מהמודלים)",
    "Immunotoxicity; hepatotoxicity; elevated cholesterol; thyroid disruption; developmental effects; potential carcinogenicity": "רעילות חיסונית; רעילות כבדית; כולסטרול מוגבר; שיבוש תריס; השפעות התפתחותיות; חשש לסרטנות",
    "Immunotoxicity; thyroid disruption; hepatotoxicity": "רעילות חיסונית; שיבוש תריס; רעילות כבדית",
    "Increased bleeding risk; Hemorrhagic stroke; May increase all-cause mortality at very high doses": "סיכון מוגבר לדימום; שבץ דימומי; עלול להגביר תמותה מכל סיבה במינונים גבוהים מאוד",
    "Increased heart rate, blood pressure (especially with caffeine)": "עלייה בדופק, לחץ דם (במיוחד עם קפאין)",

    # === Inhibits/Insomnia ===
    "Inhibits sucrase enzyme; reduces sugar absorption when co-consumed; anti-diabetic potential": "מעכב אנזים סוכראז; מפחית ספיגת סוכר בצריכה משותפת; פוטנציאל אנטי-סוכרתי",
    "Insomnia, anxiety, tachycardia, GI upset, tremors, dependence": "נדודי שינה, חרדה, טכיקרדיה, הפרעת מערכת עיכול, רעידות, תלות",
    "Insomnia, restlessness, GI discomfort; mercury contamination risk in low-quality products": "נדודי שינה, אי שקט, אי נוחות במערכת העיכול; סיכון זיהום כספית במוצרים באיכות נמוכה",
    "Irritant; generally safe at food levels": "מגרה; בטוח בדרך כלל ברמות מזון",

    # === Kidney ===
    "Kidney damage (case reports with picolinate at very high doses); Cr(III) generally safe; Cr(VI) is carcinogenic (not a supplement form)": "נזק לכליות (דוחות מקרה עם פיקולינט במינונים גבוהים מאוד); Cr(III) בטוח בדרך כלל; Cr(VI) מסרטן (לא צורת תוסף)",
    "Kidney effects at high doses; ADI withdrawn due to very low/single use": "השפעות כליות במינונים גבוהים; ADI נמשך בשל שימוש נמוך מאוד/בודד",
    "Kidney stones; renal failure; bladder cancer (with cyanuric acid); reproductive toxicity at high doses": "אבני כליות; אי ספיקת כליות; סרטן שלפוחית (עם חומצה ציאנורית); רעילות רבייתית במינונים גבוהים",

    # === Lactose/Laxative/Less/Leukemia ===
    "Lactose intolerance common; fermentable; promotes dental caries less than sucrose": "אי סבילות ללקטוז נפוצה; ניתן לתסיסה; מקדם עששת פחות מסוכרוז",
    "Laxative; generally safe at food levels": "משלשל; בטוח בדרך כלל ברמות מזון",
    "Less GI distress than maltodextrin; fast gastric emptying": "פחות מצוקת מערכת עיכול ממלטודקסטרין; ריקון קיבה מהיר",
    "Less GI irritation than ascorbic acid; same UL applies": "פחות גירוי מערכת עיכול מחומצת אסקורבית; אותו UL חל",
    "Leukemia (AML); bone marrow toxicity; carcinogenicity": "לוקמיה (AML); רעילות מח עצם; סרטנות",
    "Licorice-like aftertaste; limited commercial use; from perilla plant": "טעם לוואי דמוי ליקריץ; שימוש מסחרי מוגבל; מצמח פרילה",

    # === Limited/Linked/Liver ===
    "Limited data; Generally safe in studied doses": "נתונים מוגבלים; בטוח בדרך כלל במינונים שנחקרו",
    "Limited data; potential cardiovascular stimulation": "נתונים מוגבלים; גירוי קרדיווסקולרי אפשרי",
    "Limited recent toxicology data; potential high child intake": "נתוני טוקסיקולוגיה עדכניים מוגבלים; צריכה גבוהה אפשרית בילדים",
    "Limited safety concerns; not evaluated by EFSA (banned in EU)": "חששות בטיחות מוגבלים; לא הוערך על ידי EFSA (אסור באיחוד האירופי)",
    "Limited use as sweetener; rare sugar classification": "שימוש מוגבל כממתיק; סיווג סוכר נדיר",
    "Linked to obesity and metabolic syndrome; similar metabolic impact to sucrose": "קשור להשמנה ותסמונת מטבולית; השפעה מטבולית דומה לסוכרוז",
    "Liver and kidney effects at high doses; less reproductive toxicity than DEHP": "השפעות כבד וכליות במינונים גבוהים; פחות רעילות רבייתית מ-DEHP",
    "Liver and kidney toxicity; neural tube defects (animals); esophageal cancer association; equine leukoencephalomalacia": "רעילות כבד וכליות; מומי צינור עצבי (בעלי חיים); קשר לסרטן הוושט; לויקואנצפלומלציה בסוסים",
    "Liver toxicity, cardiovascular risks, hormonal suppression, unknown long-term effects": "רעילות כבדית, סיכונים קרדיווסקולריים, דיכוי הורמונלי, השפעות ארוכות טווח לא ידועות",
    "Loose stools at high doses": "צואה רכה במינונים גבוהים",
    "Low-sodium alternative to sodium saccharin": "חלופה דלת נתרן לנתרן סכרין",
    "Lower GI than sugar; rich in potassium, magnesium; still caloric": "אינדקס גליקמי נמוך מסוכר; עשיר באשלגן, מגנזיום; עדיין קלורי",
    "Lower GI than white sugar; contains minerals; still caloric": "אינדקס גליקמי נמוך מסוכר לבן; מכיל מינרלים; עדיין קלורי",
    "Lower flushing risk; Otherwise see Vitamin B3": "סיכון סמקה נמוך יותר; ראה ויטמין B3",

    # === Marker/May ===
    "Marker for ergot alkaloid contamination risk": "סמן לסיכון זיהום אלקלואיד ארגוט",
    "May cause headache and flushing in sensitive individuals at high doses": "עלול לגרום לכאב ראש וסמקה באנשים רגישים במינונים גבוהים",
    "May contain carcinogenic PAHs; EFSA concerns; cytotoxicity in cell studies": "עלול להכיל PAHs מסרטנים; חששות EFSA; רעילות תאית במחקרי תאים",
    "May contain trans fats; high in saturated fat": "עלול להכיל שומני טרנס; עשיר בשומן רווי",
    "May lower blood sugar; anti-fertility effects in animal studies": "עלול להוריד סוכר בדם; השפעות אנטי-פוריות במחקרי בעלי חיים",

    # === Metabolic/Mild/Mineral ===
    "Metabolically similar to sugar despite 'natural' marketing; retains some nutrients": "דומה מטבולית לסוכר למרות שיווק 'טבעי'; שומר על חלק מהתזונה",
    "Mild GI discomfort": "אי נוחות קלה במערכת העיכול",
    "Mineral-rich but still caloric sugar; promotes dental caries": "עשיר במינרלים אך עדיין סוכר קלורי; מקדם עששת",
    "Minor metabolite of erythritol; limited data": "מטבוליט משני של אריתריטול; נתונים מוגבלים",
    "Mirror sugar; not metabolized; too expensive for commercial use": "סוכר מראה; לא עובר מטבוליזם; יקר מדי לשימוש מסחרי",
    "Mouth/skin irritation; GI discomfort if ingested in large amounts": "גירוי פה/עור; אי נוחות במערכת העיכול אם נבלע בכמויות גדולות",

    # === Mutagenicity/Myocardial ===
    "Mutagenicity (one of the most potent mutagens known); potential carcinogenicity": "מוטגניות (אחד המוטגנים החזקים הידועים); חשש לסרטנות",
    "Mutagenicity; carcinogenicity (liver, lung in rodents)": "מוטגניות; סרטנות (כבד, ריאה במכרסמים)",
    "Myocardial lipidosis; cardiotoxicity in animals; potential developmental effects": "ליפידוזיס שריר הלב; רעילות לבבית בבעלי חיים; השפעות התפתחותיות אפשריות",

    # === NOW/Natural/Naturally ===
    "NOW a major allergen (US FASTER Act 2023, EU already listed). Rich in calcium.": "כעת אלרגן מרכזי (חוק FASTER בארה\"ב 2023, באיחוד האירופי כבר ברשימה). עשיר בסידן.",
    "Natural amino acid derivative; potential next-gen sweetener": "נגזרת חומצת אמינו טבעית; ממתיק דור הבא פוטנציאלי",
    "Natural but allergic reactions; urticaria; IBS-triggering": "טבעי אך תגובות אלרגיות; אורטיקריה; מעורר IBS",
    "Naturally sweet amino acid; caloric; important for collagen synthesis": "חומצת אמינו מתוקה טבעית; קלורית; חשובה לסינתזת קולגן",

    # === Nausea ===
    "Nausea on empty stomach; very limited safety data in humans": "בחילה על קיבה ריקה; נתוני בטיחות מוגבלים מאוד בבני אדם",
    "Nausea, GI discomfort, drowsiness; serotonin syndrome risk": "בחילה, אי נוחות במערכת העיכול, ישנוניות; סיכון לתסמונת סרוטונין",
    "Nausea, diarrhea, sweating, blurred vision": "בחילה, שלשול, הזעה, טשטוש ראייה",
    "Nausea, vomiting, copper deficiency at chronic >40mg/d": "בחילה, הקאה, חוסר נחושת בצריכה כרונית >40 מ\"ג/יום",
    "Nausea, vomiting, headache; dopamine excess symptoms at high doses": "בחילה, הקאה, כאב ראש; תסמיני עודף דופמין במינונים גבוהים",
    "Nausea, vomiting, tinnitus, delirium at higher concentrations": "בחילה, הקאה, טינטון, דליריום בריכוזים גבוהים",
    "Nausea; vomiting; diarrhea; feed refusal; immunotoxicity; growth retardation": "בחילה; הקאה; שלשול; סירוב לאכילה; רעילות חיסונית; עיכוב גדילה",

    # === Nephrotoxicity ===
    "Nephrotoxicity (proximal tubule damage); osteoporosis; carcinogenicity (lung); reproductive toxicity": "רעילות כלייתית (נזק לצינורית פרוקסימלית); אוסטאופורוזיס; סרטנות (ריאה); רעילות רבייתית",
    "Nephrotoxicity in developing kidneys; highest concern for infants": "רעילות כלייתית בכליות מתפתחות; חשש גבוה ביותר לתינוקות",
    "Nephrotoxicity; bioaccumulation in kidney tissue": "רעילות כלייתית; הצטברות ביולוגית ברקמת כליה",
    "Nephrotoxicity; bone effects; chronic accumulation": "רעילות כלייתית; השפעות על עצמות; הצטברות כרונית",
    "Nephrotoxicity; male reproductive toxicity; potential carcinogenicity": "רעילות כלייתית; רעילות רבייתית זכרית; חשש לסרטנות",
    "Nephrotoxicity; osteoporosis; itai-itai disease": "רעילות כלייתית; אוסטאופורוזיס; מחלת איטאי-איטאי",
    "Nephrotoxicity; potential carcinogenicity (kidney); immunotoxicity; teratogenicity": "רעילות כלייתית; חשש לסרטנות (כליה); רעילות חיסונית; טרטוגניות",
    "Nephrotoxicity; testicular toxicity; potential carcinogenicity": "רעילות כלייתית; רעילות אשכית; חשש לסרטנות",

    # === Neurodevelopmental/Neurotoxicity ===
    "Neurodevelopmental toxicity (children); nephrotoxicity; cardiovascular effects; reproductive toxicity; anemia": "רעילות נוירו-התפתחותית (ילדים); רעילות כלייתית; השפעות קרדיווסקולריות; רעילות רבייתית; אנמיה",
    "Neurodevelopmental toxicity (fetus, children); cognitive impairment; cardiovascular effects": "רעילות נוירו-התפתחותית (עובר, ילדים); פגיעה קוגניטיבית; השפעות קרדיווסקולריות",
    "Neurodevelopmental toxicity in children": "רעילות נוירו-התפתחותית בילדים",
    "Neurodevelopmental toxicity; cardiovascular effects": "רעילות נוירו-התפתחותית; השפעות קרדיווסקולריות",
    "Neurodevelopmental toxicity; impaired cognition": "רעילות נוירו-התפתחותית; פגיעה בקוגניציה",
    "Neurotoxicity (acetylcholinesterase inhibition); neurodevelopmental effects (children); endocrine disruption": "רעילות עצבית (עיכוב אצטילכולינסטראז); השפעות נוירו-התפתחותיות (ילדים); שיבוש אנדוקריני",
    "Neurotoxicity (especially fetal/child brain development); nephrotoxicity; cardiovascular effects": "רעילות עצבית (במיוחד התפתחות מוח עובר/ילד); רעילות כלייתית; השפעות קרדיווסקולריות",
    "Neurotoxicity at chronic excess (especially inhaled)": "רעילות עצבית בעודף כרוני (במיוחד בשאיפה)",
    "Neurotoxicity at high exposure; aluminium accumulation concerns": "רעילות עצבית בחשיפה גבוהה; חששות הצטברות אלומיניום",
    "Neurotoxicity when combined with MSG; allergic reactions": "רעילות עצבית בשילוב עם MSG; תגובות אלרגיות",
    "Neurotoxicity; developmental toxicity (children); cardiovascular effects": "רעילות עצבית; רעילות התפתחותית (ילדים); השפעות קרדיווסקולריות",
    "Neurotoxicity; genotoxicity; carcinogenicity (kidney, endometrial, ovarian tumors in animals)": "רעילות עצבית; רעילות גנטית; סרטנות (גידולי כליה, רחם, שחלות בבעלי חיים)",
    "Neurotoxicity; nephrotoxicity; hepatotoxicity (at/near ADI); allergic reactions; colitis in predisposed; enzyme inhibition": "רעילות עצבית; רעילות כלייתית; רעילות כבדית (ב/ליד ADI); תגובות אלרגיות; קוליטיס בנטייה מוקדמת; עיכוב אנזימים",

    # === No concerns/major ===
    "No commercial use as sweetener": "אין שימוש מסחרי כממתיק",
    "No concerns; beneficial fiber": "אין חששות; סיבים מועילים",
    "No concerns; elastic gel formation": "אין חששות; יצירת ג'ל אלסטי",
    "No concerns; synergistic thickening": "אין חששות; עיבוי סינרגיסטי",
    "No known toxicity; Can interfere with lab tests (troponin, thyroid) at high doses": "אין רעילות ידועה; עלול להפריע לבדיקות מעבדה (טרופונין, תריס) במינונים גבוהים",
    "No known toxicity; Very safe even at high doses": "אין רעילות ידועה; בטוח מאוד גם במינונים גבוהים",
    "No major allergen concerns": "אין חששות אלרגן מרכזיים",
    "No major allergen concerns; allergen-free alternative": "אין חששות אלרגן מרכזיים; חלופה ללא אלרגנים",
    "No safety concern (EFSA 2017); aluminium exposure consideration": "אין חשש בטיחותי (EFSA 2017); שיקול חשיפה לאלומיניום",
    "No safety concern (EFSA 2017); potential GMO source": "אין חשש בטיחותי (EFSA 2017); מקור GMO אפשרי",
    "No significant concerns at current use levels": "אין חששות משמעותיים ברמות שימוש נוכחיות",
    "No significant concerns at food-grade levels": "אין חששות משמעותיים ברמות מזון",
    "No significant concerns; BSE risk mitigated": "אין חששות משמעותיים; סיכון BSE מופחת",
    "No significant concerns; allergen potential": "אין חששות משמעותיים; פוטנציאל אלרגני",
    "No significant concerns; alternative to lecithin": "אין חששות משמעותיים; חלופה ללציטין",
    "No significant concerns; bloating at excess": "אין חששות משמעותיים; נפיחות בעודף",
    "No significant concerns; indigestible fiber": "אין חששות משמעותיים; סיבים בלתי ניתנים לעיכול",
    "No significant concerns; key ingredient in plant meats": "אין חששות משמעותיים; מרכיב מפתח בבשר צמחי",
    "No significant concerns; prebiotic effects": "אין חששות משמעותיים; השפעות פרה-ביוטיות",
    "No significant concerns; prebiotic properties reported": "אין חששות משמעותיים; דווח על תכונות פרה-ביוטיות",

    # === Non-cariogenic/Not/Novel/NutriNet ===
    "Non-cariogenic; prebiotic potential; rare sugar": "לא גורם עששת; פוטנציאל פרה-ביוטי; סוכר נדיר",
    "Non-digestible; gas-producing; prebiotic": "לא ניתן לעיכול; מייצר גזים; פרה-ביוטי",
    "Not approved for food; medicinal use only": "לא מאושר למזון; שימוש רפואי בלבד",
    "Not approved; potential skin irritant": "לא מאושר; מגרה עור אפשרי",
    "Not safe for food; potential genotoxicity": "לא בטוח למזון; חשש לרעילות גנטית",
    "Novel protein sweetener; limited regulatory approvals": "ממתיק חלבוני חדשני; אישורים רגולטוריים מוגבלים",
    "NutriNet-Sante: higher cancer risk (breast, obesity-related)": "NutriNet-Sante: סיכון סרטן גבוה יותר (שד, קשור להשמנה)",

    # === Plant/Plural/Potential ===
    "Plant-derived protein; may contain soy allergen": "חלבון מהצומח; עלול להכיל אלרגן סויה",
    "Plant-derived starch; generally safe": "עמילן מהצומח; בטוח בדרך כלל",
    "Plural form of natural flavor. Same regulatory definition.": "צורת רבים של טעם טבעי. אותה הגדרה רגולטורית.",
    "Potential GI irritant at high levels": "מגרה אפשרי של מערכת העיכול ברמות גבוהות",
    "Potential carcinogenicity (lung, alveolar/bronchiolar in mice); convulsions at high doses": "חשש לסרטנות (ריאה, מכתשית/סימפונית בעכברים); עוויתות במינונים גבוהים",
    "Potential carcinogenicity (lymphohematopoietic); neurotoxicity; ototoxicity (occupational)": "חשש לסרטנות (לימפו-המטופויטית); רעילות עצבית; רעילות אוזנית (תעסוקתית)",
    "Potential carcinogenicity (non-Hodgkin lymphoma debate); endocrine disruption; genotoxicity (debated)": "חשש לסרטנות (ויכוח לימפומה שאינה הודג'קין); שיבוש אנדוקריני; רעילות גנטית (שנוי במחלוקת)",
    "Potential carcinogenicity; gene damage; hyperactivity": "חשש לסרטנות; נזק גנטי; היפראקטיביות",
    "Potential carcinogenicity; hyperactivity link": "חשש לסרטנות; קשר להיפראקטיביות",
    "Potential carcinogenicity; very restricted": "חשש לסרטנות; מוגבל מאוד",
    "Potential cytotoxicity; genotoxicity (debated); indicator of heat damage/aging in honey": "רעילות תאית אפשרית; רעילות גנטית (שנוי במחלוקת); מחוון לנזקי חום/יישון בדבש",
    "Potential cytotoxicity; genotoxicity (disputed); quality indicator for honey degradation": "רעילות תאית אפשרית; רעילות גנטית (שנוי במחלוקת); מחוון איכות לפירוק דבש",
    "Potential endocrine disruption; protein aggregation; genotoxicity concerns": "חשש לשיבוש אנדוקריני; הצטברות חלבון; חששות רעילות גנטית",
    "Potential nephrotoxicity; under investigation": "רעילות כלייתית אפשרית; בחקירה",

    # === Prebiotic ===
    "Prebiotic (FOS); may cause gas/bloating at high doses; low calorie": "פרה-ביוטי (FOS); עלול לגרום גזים/נפיחות במינונים גבוהים; דל קלוריות",
    "Prebiotic; gas and bloating at high doses; used more for fiber/bulk than sweetness": "פרה-ביוטי; גזים ונפיחות במינונים גבוהים; משמש יותר לסיבים/נפח מאשר למתיקות",
    "Prebiotic; mildly sweet; used as bulking agent in sugar reduction": "פרה-ביוטי; מתוק במעט; משמש כחומר מילוי בהפחתת סוכר",
    "Prebiotic; poorly digested; low caloric value": "פרה-ביוטי; מתעכל בקושי; ערך קלורי נמוך",
    "Prebiotic; supports Bifidobacteria; GI discomfort at high doses": "פרה-ביוטי; תומך בביפידובקטריה; אי נוחות במערכת העיכול במינונים גבוהים",

    # === Probable/Processed/Promotes/Protein/Proven ===
    "Probable carcinogenicity; endocrine disruption; neurotoxicity; hepatotoxicity; bioaccumulation": "סרטנות סבירה; שיבוש אנדוקריני; רעילות עצבית; רעילות כבדית; הצטברות ביולוגית",
    "Processed starch; raises glycemic index faster than regular starch": "עמילן מעובד; מעלה אינדקס גליקמי מהר יותר מעמילן רגיל",
    "Promotes dental caries; contributes to obesity, type 2 diabetes, metabolic syndrome": "מקדם עששת; תורם להשמנה, סוכרת סוג 2, תסמונת מטבולית",
    "Protein source; higher in saturated fat": "מקור חלבון; עשיר יותר בשומן רווי",
    "Proven anti-cariogenic (fights tooth decay); laxative >30-40g/day; TOXIC to dogs; some cardiovascular concern studies (Cleveland Clinic 2023)": "מוכח אנטי-עששתי (נלחם בעששת); משלשל >30-40 גרם/יום; רעיל לכלבים; מחקרי חשש קרדיווסקולרי (קליבלנד קליניק 2023)",

    # === Rare/Recombinant/Red/Reported/Reproductive/Research ===
    "Rare allergic reactions; lower ADI than bixin": "תגובות אלרגיות נדירות; ADI נמוך מביקסין",
    "Rare anaphylaxis; allergic reactions in sensitive individuals": "אנפילקסיס נדיר; תגובות אלרגיות באנשים רגישים",
    "Rare sugar; non-cariogenic; limited data": "סוכר נדיר; לא גורם עששת; נתונים מוגבלים",
    "Recombinant protein production via fermentation; heat and pH stable": "ייצור חלבון רקומביננטי בתסיסה; יציב בחום וב-pH",
    "Red urine (beeturia); GI discomfort": "שתן אדום (ביטוריה); אי נוחות במערכת העיכול",
    "Red urine/stools (harmless beeturia); GI discomfort in some": "שתן/צואה אדומים (ביטוריה לא מזיקה); אי נוחות במערכת העיכול בחלק מהאנשים",
    "Reported MSG symptom complex in sensitive individuals; EFSA ADI exceeded in some populations": "דווח על תסמונת תסמיני MSG באנשים רגישים; ADI של EFSA נחרג בחלק מהאוכלוסיות",
    "Reproductive toxicity (animal data); Nausea; Vomiting; Diarrhea; Dermatitis": "רעילות רבייתית (נתוני בעלי חיים); בחילה; הקאה; שלשול; דרמטיטיס",
    "Reproductive toxicity (anti-androgenic); endocrine disruption; developmental toxicity": "רעילות רבייתית (אנטי-אנדרוגנית); שיבוש אנדוקריני; רעילות התפתחותית",
    "Research class containing the most potent sweeteners known": "קבוצה מחקרית המכילה את הממתיקים החזקים הידועים",
}

def escape_sql(text):
    return text.replace("'", "''")

def main():
    sql_lines = []
    for eng, heb in TRANSLATIONS.items():
        eng_escaped = escape_sql(eng)
        heb_escaped = escape_sql(heb)
        sql_lines.append(f"UPDATE food_additives SET health_concerns_he = '{heb_escaped}' WHERE health_concerns = '{eng_escaped}';")

    sql_dir = os.path.join(os.path.dirname(__file__), "sql")
    os.makedirs(sql_dir, exist_ok=True)
    sql_path = os.path.join(sql_dir, "health_concerns_he_final.sql")
    with open(sql_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))
    print(f"Written {len(sql_lines)} UPDATE statements to {sql_path}")

if __name__ == "__main__":
    main()
